// AUTO-GENERATED by scripts/build-edge-function.mjs — DO NOT EDIT
// Regenerate: node scripts/build-edge-function.mjs

export interface EmailTemplate {
  subject: string;
  html: string;
}

export const TEMPLATES: Record<string, EmailTemplate> = {
  "welcome": {
    subject: "Chào mừng đến với Hàn Quốc Ơi!",
    html: `<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>Chào mừng đến với Hàn Quốc Ơi!</title></head>
<body style="margin:0;padding:0;background-color:#0f1117;font-family:'Be Vietnam Pro','Segoe UI',Roboto,Arial,sans-serif;color:#ffffff;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#0f1117;padding:32px 16px;"><tr><td align="center">
<table role="presentation" width="560" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;width:100%;background-color:#141720;border:1px solid rgba(255,255,255,0.08);border-radius:16px;overflow:hidden;">
<tr><td style="padding:32px 32px 16px 32px;text-align:center;border-bottom:1px solid rgba(255,255,255,0.06);">
<div style="display:inline-block;width:56px;height:56px;background:linear-gradient(135deg,#e8c84a,#d4b43a);border-radius:16px;line-height:56px;font-size:28px;font-weight:700;color:#0f1117;">한</div>
<h1 style="margin:16px 0 4px 0;font-size:22px;font-weight:700;color:#ffffff;">Hàn Quốc Ơi!</h1>
<p style="margin:0;font-size:13px;color:#9ca3af;">Học tiếng Hàn mỗi ngày</p>
</td></tr>
<tr><td style="padding:32px;">
<div style="text-align:center;font-size:48px;margin-bottom:16px;">🎉</div>
<h2 style="margin:0 0 16px 0;font-size:22px;font-weight:700;color:#e8c84a;text-align:center;">Chào mừng {{USER_NAME}}!</h2>
<p style="margin:0 0 16px 0;font-size:14px;line-height:1.6;color:#d1d5db;">Cảm ơn bạn đã gia nhập cộng đồng học tiếng Hàn <strong style="color:#e8c84a;">Hàn Quốc Ơi!</strong> — nơi hàng ngàn học viên đang chinh phục TOPIK, EPS-TOPIK và khám phá văn hoá Hàn Quốc mỗi ngày.</p>
<p style="margin:0 0 16px 0;font-size:14px;line-height:1.6;color:#d1d5db;"><strong style="color:#ffffff;">Bắt đầu ngay với:</strong></p>
<ul style="margin:0 0 20px 0;padding-left:20px;color:#d1d5db;font-size:14px;line-height:1.8;">
<li>📝 <strong>Bảng chữ cái Hangul</strong> — học trong 15 phút</li>
<li>📚 <strong>Từ vựng theo chủ đề</strong> — 5,000+ từ thông dụng</li>
<li>🎯 <strong>Luyện đề TOPIK</strong> — ngân hàng đề cập nhật mới nhất</li>
<li>🔥 <strong>Streak mỗi ngày</strong> — giữ động lực học đều đặn</li>
</ul>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:24px auto;"><tr><td style="background-color:#e8c84a;border-radius:12px;">
<a href="{{SITE_URL}}/dashboard" style="display:inline-block;padding:14px 32px;font-size:15px;font-weight:700;color:#0f1117;text-decoration:none;">Bắt đầu học ngay</a>
</td></tr></table>
<div style="border-top:1px solid rgba(255,255,255,0.06);margin:24px 0;"></div>
<p style="margin:0;font-size:12px;line-height:1.6;color:#6b7280;text-align:center;">Có thắc mắc? Trả lời email này hoặc liên hệ qua mục <strong style="color:#d1d5db;">Góp ý</strong> trong app.</p>
</td></tr>
<tr><td style="padding:20px 32px;background-color:rgba(255,255,255,0.02);border-top:1px solid rgba(255,255,255,0.06);text-align:center;">
<p style="margin:0 0 4px 0;font-size:12px;color:#9ca3af;">© Hàn Quốc Ơi! — Học tiếng Hàn online</p>
<p style="margin:0;font-size:11px;color:#6b7280;">Email này được gửi tự động, vui lòng không trả lời trực tiếp.</p>
</td></tr></table></td></tr></table></body></html>
`,
  },
  "vip-success": {
    subject: "Kích hoạt VIP thành công — Hàn Quốc Ơi!",
    html: `<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>Kích hoạt VIP thành công!</title></head>
<body style="margin:0;padding:0;background-color:#0f1117;font-family:'Be Vietnam Pro','Segoe UI',Roboto,Arial,sans-serif;color:#ffffff;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#0f1117;padding:32px 16px;"><tr><td align="center">
<table role="presentation" width="560" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;width:100%;background-color:#141720;border:1px solid rgba(255,255,255,0.08);border-radius:16px;overflow:hidden;">
<tr><td style="padding:32px 32px 16px 32px;text-align:center;border-bottom:1px solid rgba(255,255,255,0.06);">
<div style="display:inline-block;width:56px;height:56px;background:linear-gradient(135deg,#e8c84a,#d4b43a);border-radius:16px;line-height:56px;font-size:28px;font-weight:700;color:#0f1117;">한</div>
<h1 style="margin:16px 0 4px 0;font-size:22px;font-weight:700;color:#ffffff;">Hàn Quốc Ơi!</h1>
<p style="margin:0;font-size:13px;color:#9ca3af;">Học tiếng Hàn mỗi ngày</p>
</td></tr>
<tr><td style="padding:32px;">
<div style="text-align:center;font-size:48px;margin-bottom:16px;">👑</div>
<h2 style="margin:0 0 8px 0;font-size:22px;font-weight:700;color:#e8c84a;text-align:center;">Chào mừng VIP {{USER_NAME}}!</h2>
<p style="margin:0 0 20px 0;font-size:14px;line-height:1.6;color:#d1d5db;text-align:center;">Cảm ơn bạn đã tin tưởng và nâng cấp tài khoản VIP.</p>
<div style="background:linear-gradient(135deg,rgba(232,200,74,0.12),rgba(232,200,74,0.04));border:1px solid rgba(232,200,74,0.25);border-radius:12px;padding:20px;margin:20px 0;">
<p style="margin:0 0 8px 0;font-size:12px;color:#9ca3af;">HOÁ ĐƠN THANH TOÁN</p>
<table width="100%" cellpadding="0" cellspacing="0" style="font-size:13px;color:#d1d5db;">
<tr><td style="padding:4px 0;">Gói đăng ký</td><td style="padding:4px 0;text-align:right;color:#ffffff;font-weight:600;">{{PLAN_NAME}}</td></tr>
<tr><td style="padding:4px 0;">Số tiền</td><td style="padding:4px 0;text-align:right;color:#e8c84a;font-weight:700;font-size:16px;">{{AMOUNT}}</td></tr>
<tr><td style="padding:4px 0;">Ngày thanh toán</td><td style="padding:4px 0;text-align:right;color:#ffffff;">{{PAYMENT_DATE}}</td></tr>
<tr><td style="padding:4px 0;">Hết hạn</td><td style="padding:4px 0;text-align:right;color:#ffffff;">{{EXPIRES_AT}}</td></tr>
</table></div>
<p style="margin:16px 0;font-size:14px;line-height:1.6;color:#d1d5db;"><strong style="color:#e8c84a;">Quyền lợi VIP:</strong></p>
<ul style="margin:0 0 20px 0;padding-left:20px;color:#d1d5db;font-size:14px;line-height:1.8;">
<li>✨ Mở khoá toàn bộ bài học, đề thi TOPIK cao cấp</li>
<li>🚀 Không quảng cáo, tốc độ load nhanh hơn</li>
<li>🎁 Voucher & phần thưởng độc quyền hàng tháng</li>
<li>💬 Hỗ trợ ưu tiên 24/7</li>
</ul>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:24px auto;"><tr><td style="background-color:#e8c84a;border-radius:12px;">
<a href="{{SITE_URL}}/vip-history" style="display:inline-block;padding:14px 32px;font-size:15px;font-weight:700;color:#0f1117;text-decoration:none;">Xem lịch sử VIP</a>
</td></tr></table>
<div style="border-top:1px solid rgba(255,255,255,0.06);margin:24px 0;"></div>
<p style="margin:0;font-size:12px;line-height:1.6;color:#6b7280;text-align:center;">Cần hỗ trợ về thanh toán? Liên hệ qua mục <strong style="color:#d1d5db;">Góp ý</strong> hoặc trả lời email này.</p>
</td></tr>
<tr><td style="padding:20px 32px;background-color:rgba(255,255,255,0.02);border-top:1px solid rgba(255,255,255,0.06);text-align:center;">
<p style="margin:0 0 4px 0;font-size:12px;color:#9ca3af;">© Hàn Quốc Ơi! — Học tiếng Hàn online</p>
<p style="margin:0;font-size:11px;color:#6b7280;">Email này được gửi tự động, vui lòng không trả lời trực tiếp.</p>
</td></tr></table></td></tr></table></body></html>
`,
  },
  "vip-expiring": {
    subject: "VIP sắp hết hạn — Gia hạn ngay để không gián đoạn",
    html: `<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>VIP sắp hết hạn</title></head>
<body style="margin:0;padding:0;background-color:#0f1117;font-family:'Be Vietnam Pro','Segoe UI',Roboto,Arial,sans-serif;color:#ffffff;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#0f1117;padding:32px 16px;"><tr><td align="center">
<table role="presentation" width="560" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;width:100%;background-color:#141720;border:1px solid rgba(255,255,255,0.08);border-radius:16px;overflow:hidden;">
<tr><td style="padding:32px 32px 16px 32px;text-align:center;border-bottom:1px solid rgba(255,255,255,0.06);">
<div style="display:inline-block;width:56px;height:56px;background:linear-gradient(135deg,#e8c84a,#d4b43a);border-radius:16px;line-height:56px;font-size:28px;font-weight:700;color:#0f1117;">한</div>
<h1 style="margin:16px 0 4px 0;font-size:22px;font-weight:700;color:#ffffff;">Hàn Quốc Ơi!</h1>
<p style="margin:0;font-size:13px;color:#9ca3af;">Học tiếng Hàn mỗi ngày</p>
</td></tr>
<tr><td style="padding:32px;">
<div style="display:inline-block;padding:6px 12px;background-color:rgba(251,146,60,0.12);border:1px solid rgba(251,146,60,0.25);border-radius:999px;margin-bottom:16px;">
<span style="font-size:12px;font-weight:600;color:#fb923c;">⏰ Sắp hết hạn</span></div>
<h2 style="margin:0 0 16px 0;font-size:22px;font-weight:700;color:#ffffff;">{{USER_NAME}} ơi, VIP sắp hết hạn!</h2>
<p style="margin:0 0 16px 0;font-size:14px;line-height:1.6;color:#d1d5db;">Tài khoản VIP của bạn sẽ hết hạn trong <strong style="color:#fb923c;font-size:18px;">{{DAYS_LEFT}} ngày</strong> ({{EXPIRES_AT}}).</p>
<p style="margin:0 0 16px 0;font-size:14px;line-height:1.6;color:#d1d5db;">Gia hạn ngay để tiếp tục tận hưởng:</p>
<ul style="margin:0 0 20px 0;padding-left:20px;color:#d1d5db;font-size:14px;line-height:1.8;">
<li>✨ Toàn bộ đề thi TOPIK cao cấp</li>
<li>🚀 Trải nghiệm không quảng cáo</li>
<li>🎁 Voucher độc quyền hàng tháng</li>
<li>💬 Hỗ trợ ưu tiên</li>
</ul>
<div style="background:linear-gradient(135deg,rgba(232,200,74,0.12),rgba(232,200,74,0.04));border:1px solid rgba(232,200,74,0.25);border-radius:12px;padding:16px;margin:20px 0;text-align:center;">
<p style="margin:0 0 8px 0;font-size:13px;color:#e8c84a;font-weight:600;">🎉 Ưu đãi gia hạn sớm</p>
<p style="margin:0;font-size:12px;color:#d1d5db;">Gia hạn trước khi hết hạn để nhận thêm <strong style="color:#e8c84a;">7 ngày miễn phí</strong></p></div>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:24px auto;"><tr><td style="background-color:#e8c84a;border-radius:12px;">
<a href="{{SITE_URL}}/vip" style="display:inline-block;padding:14px 32px;font-size:15px;font-weight:700;color:#0f1117;text-decoration:none;">Gia hạn VIP ngay</a>
</td></tr></table>
<div style="border-top:1px solid rgba(255,255,255,0.06);margin:24px 0;"></div>
<p style="margin:0;font-size:12px;line-height:1.6;color:#6b7280;text-align:center;">Không muốn nhận email nhắc nhở? <a href="{{SITE_URL}}/settings" style="color:#9ca3af;text-decoration:underline;">Tắt trong cài đặt</a></p>
</td></tr>
<tr><td style="padding:20px 32px;background-color:rgba(255,255,255,0.02);border-top:1px solid rgba(255,255,255,0.06);text-align:center;">
<p style="margin:0 0 4px 0;font-size:12px;color:#9ca3af;">© Hàn Quốc Ơi! — Học tiếng Hàn online</p>
<p style="margin:0;font-size:11px;color:#6b7280;">Email này được gửi tự động, vui lòng không trả lời trực tiếp.</p>
</td></tr></table></td></tr></table></body></html>
`,
  },
  "streak-warning": {
    subject: "🔥 Đừng để mất streak — chỉ 5 phút thôi!",
    html: `<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>Streak sắp mất!</title></head>
<body style="margin:0;padding:0;background-color:#0f1117;font-family:'Be Vietnam Pro','Segoe UI',Roboto,Arial,sans-serif;color:#ffffff;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#0f1117;padding:32px 16px;"><tr><td align="center">
<table role="presentation" width="560" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;width:100%;background-color:#141720;border:1px solid rgba(255,255,255,0.08);border-radius:16px;overflow:hidden;">
<tr><td style="padding:32px 32px 16px 32px;text-align:center;border-bottom:1px solid rgba(255,255,255,0.06);">
<div style="display:inline-block;width:56px;height:56px;background:linear-gradient(135deg,#e8c84a,#d4b43a);border-radius:16px;line-height:56px;font-size:28px;font-weight:700;color:#0f1117;">한</div>
<h1 style="margin:16px 0 4px 0;font-size:22px;font-weight:700;color:#ffffff;">Hàn Quốc Ơi!</h1>
<p style="margin:0;font-size:13px;color:#9ca3af;">Học tiếng Hàn mỗi ngày</p>
</td></tr>
<tr><td style="padding:32px;">
<div style="text-align:center;font-size:56px;margin-bottom:16px;">🔥</div>
<h2 style="margin:0 0 16px 0;font-size:22px;font-weight:700;color:#f97316;text-align:center;">Đừng để mất streak!</h2>
<p style="margin:0 0 16px 0;font-size:14px;line-height:1.6;color:#d1d5db;text-align:center;">{{USER_NAME}} ơi, bạn đã duy trì streak được:</p>
<div style="text-align:center;margin:20px 0;">
<div style="display:inline-block;background:linear-gradient(135deg,rgba(249,115,22,0.2),rgba(249,115,22,0.05));border:2px solid rgba(249,115,22,0.4);border-radius:20px;padding:20px 40px;">
<div style="font-size:48px;font-weight:800;color:#f97316;line-height:1;">{{STREAK_COUNT}}</div>
<div style="font-size:13px;color:#9ca3af;margin-top:4px;">ngày liên tiếp</div>
</div></div>
<p style="margin:0 0 16px 0;font-size:14px;line-height:1.6;color:#d1d5db;text-align:center;">Nếu không học hôm nay, streak sẽ bị reset về 0. Chỉ cần <strong style="color:#e8c84a;">5 phút</strong> để giữ streak!</p>
<div style="background-color:rgba(249,115,22,0.08);border:1px solid rgba(249,115,22,0.2);border-radius:12px;padding:14px;margin:20px 0;text-align:center;">
<p style="margin:0;font-size:13px;color:#fb923c;">⏰ Còn <strong>{{HOURS_LEFT}} giờ</strong> trước khi hết ngày</p></div>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:24px auto;"><tr><td style="background-color:#e8c84a;border-radius:12px;">
<a href="{{SITE_URL}}/daily-words" style="display:inline-block;padding:14px 32px;font-size:15px;font-weight:700;color:#0f1117;text-decoration:none;">Học ngay 5 phút</a>
</td></tr></table>
<div style="border-top:1px solid rgba(255,255,255,0.06);margin:24px 0;"></div>
<p style="margin:0;font-size:12px;line-height:1.6;color:#6b7280;text-align:center;">Không muốn nhận nhắc nhở streak? <a href="{{SITE_URL}}/settings" style="color:#9ca3af;text-decoration:underline;">Tắt trong cài đặt</a></p>
</td></tr>
<tr><td style="padding:20px 32px;background-color:rgba(255,255,255,0.02);border-top:1px solid rgba(255,255,255,0.06);text-align:center;">
<p style="margin:0 0 4px 0;font-size:12px;color:#9ca3af;">© Hàn Quốc Ơi! — Học tiếng Hàn online</p>
<p style="margin:0;font-size:11px;color:#6b7280;">Email này được gửi tự động, vui lòng không trả lời trực tiếp.</p>
</td></tr></table></td></tr></table></body></html>
`,
  },
  "streak-milestone": {
    subject: "🏆 Chúc mừng đạt cột mốc mới!",
    html: `<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>Chúc mừng đạt cột mốc!</title></head>
<body style="margin:0;padding:0;background-color:#0f1117;font-family:'Be Vietnam Pro','Segoe UI',Roboto,Arial,sans-serif;color:#ffffff;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#0f1117;padding:32px 16px;"><tr><td align="center">
<table role="presentation" width="560" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;width:100%;background-color:#141720;border:1px solid rgba(255,255,255,0.08);border-radius:16px;overflow:hidden;">
<tr><td style="padding:32px 32px 16px 32px;text-align:center;border-bottom:1px solid rgba(255,255,255,0.06);">
<div style="display:inline-block;width:56px;height:56px;background:linear-gradient(135deg,#e8c84a,#d4b43a);border-radius:16px;line-height:56px;font-size:28px;font-weight:700;color:#0f1117;">한</div>
<h1 style="margin:16px 0 4px 0;font-size:22px;font-weight:700;color:#ffffff;">Hàn Quốc Ơi!</h1>
<p style="margin:0;font-size:13px;color:#9ca3af;">Học tiếng Hàn mỗi ngày</p>
</td></tr>
<tr><td style="padding:32px;">
<div style="text-align:center;font-size:56px;margin-bottom:16px;">🏆</div>
<h2 style="margin:0 0 8px 0;font-size:24px;font-weight:800;color:#e8c84a;text-align:center;">Chúc mừng {{USER_NAME}}!</h2>
<p style="margin:0 0 20px 0;font-size:16px;line-height:1.6;color:#d1d5db;text-align:center;">Bạn vừa đạt cột mốc đáng nể:</p>
<div style="text-align:center;margin:20px 0;">
<div style="display:inline-block;background:linear-gradient(135deg,rgba(232,200,74,0.2),rgba(232,200,74,0.05));border:2px solid rgba(232,200,74,0.4);border-radius:20px;padding:24px 48px;">
<div style="font-size:64px;font-weight:800;color:#e8c84a;line-height:1;">{{MILESTONE}}</div>
<div style="font-size:14px;color:#d1d5db;margin-top:8px;font-weight:600;">NGÀY STREAK 🔥</div>
</div></div>
<p style="margin:20px 0 16px 0;font-size:14px;line-height:1.6;color:#d1d5db;text-align:center;">{{MILESTONE_MESSAGE}}</p>
<div style="background:linear-gradient(135deg,rgba(232,200,74,0.08),rgba(232,200,74,0.02));border:1px solid rgba(232,200,74,0.2);border-radius:12px;padding:16px;margin:20px 0;text-align:center;">
<p style="margin:0 0 4px 0;font-size:13px;color:#e8c84a;font-weight:600;">🎁 Phần thưởng</p>
<p style="margin:0;font-size:12px;color:#d1d5db;">+{{XP_REWARD}} XP và huy hiệu <strong style="color:#e8c84a;">{{BADGE_NAME}}</strong> đã vào tài khoản</p></div>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:24px auto;"><tr><td style="background-color:#e8c84a;border-radius:12px;">
<a href="{{SITE_URL}}/share-progress" style="display:inline-block;padding:14px 32px;font-size:15px;font-weight:700;color:#0f1117;text-decoration:none;">Chia sẻ thành tích</a>
</td></tr></table>
<div style="border-top:1px solid rgba(255,255,255,0.06);margin:24px 0;"></div>
<p style="margin:0;font-size:12px;line-height:1.6;color:#6b7280;text-align:center;">화이팅! Tiếp tục phát huy phong độ nhé 💪</p>
</td></tr>
<tr><td style="padding:20px 32px;background-color:rgba(255,255,255,0.02);border-top:1px solid rgba(255,255,255,0.06);text-align:center;">
<p style="margin:0 0 4px 0;font-size:12px;color:#9ca3af;">© Hàn Quốc Ơi! — Học tiếng Hàn online</p>
<p style="margin:0;font-size:11px;color:#6b7280;">Email này được gửi tự động, vui lòng không trả lời trực tiếp.</p>
</td></tr></table></td></tr></table></body></html>
`,
  },
  "weekly-summary": {
    subject: "📊 Tổng kết tuần học tập của bạn",
    html: `<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>Tổng kết tuần học tập</title></head>
<body style="margin:0;padding:0;background-color:#0f1117;font-family:'Be Vietnam Pro','Segoe UI',Roboto,Arial,sans-serif;color:#ffffff;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#0f1117;padding:32px 16px;"><tr><td align="center">
<table role="presentation" width="560" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;width:100%;background-color:#141720;border:1px solid rgba(255,255,255,0.08);border-radius:16px;overflow:hidden;">
<tr><td style="padding:32px 32px 16px 32px;text-align:center;border-bottom:1px solid rgba(255,255,255,0.06);">
<div style="display:inline-block;width:56px;height:56px;background:linear-gradient(135deg,#e8c84a,#d4b43a);border-radius:16px;line-height:56px;font-size:28px;font-weight:700;color:#0f1117;">한</div>
<h1 style="margin:16px 0 4px 0;font-size:22px;font-weight:700;color:#ffffff;">Hàn Quốc Ơi!</h1>
<p style="margin:0;font-size:13px;color:#9ca3af;">Tổng kết tuần {{WEEK_RANGE}}</p>
</td></tr>
<tr><td style="padding:32px;">
<div style="text-align:center;font-size:48px;margin-bottom:16px;">📊</div>
<h2 style="margin:0 0 20px 0;font-size:22px;font-weight:700;color:#ffffff;text-align:center;">{{USER_NAME}} đã làm tốt tuần này!</h2>
<table width="100%" cellpadding="0" cellspacing="0" style="margin:20px 0;">
<tr>
<td width="50%" style="padding:4px;"><div style="background-color:rgba(74,222,128,0.08);border:1px solid rgba(74,222,128,0.2);border-radius:12px;padding:16px;text-align:center;">
<div style="font-size:12px;color:#9ca3af;margin-bottom:4px;">📝 Từ mới</div>
<div style="font-size:28px;font-weight:800;color:#4ade80;">{{WORDS_LEARNED}}</div></div></td>
<td width="50%" style="padding:4px;"><div style="background-color:rgba(56,189,248,0.08);border:1px solid rgba(56,189,248,0.2);border-radius:12px;padding:16px;text-align:center;">
<div style="font-size:12px;color:#9ca3af;margin-bottom:4px;">📚 Bài học</div>
<div style="font-size:28px;font-weight:800;color:#38bdf8;">{{LESSONS_DONE}}</div></div></td>
</tr>
<tr>
<td width="50%" style="padding:4px;"><div style="background-color:rgba(249,115,22,0.08);border:1px solid rgba(249,115,22,0.2);border-radius:12px;padding:16px;text-align:center;">
<div style="font-size:12px;color:#9ca3af;margin-bottom:4px;">🔥 Streak</div>
<div style="font-size:28px;font-weight:800;color:#f97316;">{{STREAK_COUNT}}</div></div></td>
<td width="50%" style="padding:4px;"><div style="background-color:rgba(232,200,74,0.08);border:1px solid rgba(232,200,74,0.2);border-radius:12px;padding:16px;text-align:center;">
<div style="font-size:12px;color:#9ca3af;margin-bottom:4px;">⭐ XP kiếm được</div>
<div style="font-size:28px;font-weight:800;color:#e8c84a;">{{XP_EARNED}}</div></div></td>
</tr></table>
<div style="background-color:rgba(255,255,255,0.04);border:1px solid rgba(255,255,255,0.08);border-radius:12px;padding:16px;margin:20px 0;">
<p style="margin:0 0 8px 0;font-size:12px;color:#9ca3af;">🏆 THÀNH TÍCH TUẦN</p>
<p style="margin:0 0 4px 0;font-size:14px;color:#ffffff;"><strong style="color:#e8c84a;">Top #{{RANK}}</strong> bảng xếp hạng tuần</p>
<p style="margin:0;font-size:13px;color:#d1d5db;">⏱️ Thời gian học: <strong style="color:#ffffff;">{{STUDY_TIME}}</strong></p></div>
<p style="margin:16px 0;font-size:14px;line-height:1.6;color:#d1d5db;text-align:center;">{{MOTIVATION_MESSAGE}}</p>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:24px auto;"><tr><td style="background-color:#e8c84a;border-radius:12px;">
<a href="{{SITE_URL}}/study-stats" style="display:inline-block;padding:14px 32px;font-size:15px;font-weight:700;color:#0f1117;text-decoration:none;">Xem thống kê chi tiết</a>
</td></tr></table>
<div style="border-top:1px solid rgba(255,255,255,0.06);margin:24px 0;"></div>
<p style="margin:0;font-size:12px;line-height:1.6;color:#6b7280;text-align:center;">Không muốn nhận tổng kết tuần? <a href="{{SITE_URL}}/settings" style="color:#9ca3af;text-decoration:underline;">Tắt trong cài đặt</a></p>
</td></tr>
<tr><td style="padding:20px 32px;background-color:rgba(255,255,255,0.02);border-top:1px solid rgba(255,255,255,0.06);text-align:center;">
<p style="margin:0 0 4px 0;font-size:12px;color:#9ca3af;">© Hàn Quốc Ơi! — Học tiếng Hàn online</p>
<p style="margin:0;font-size:11px;color:#6b7280;">Email này được gửi tự động, vui lòng không trả lời trực tiếp.</p>
</td></tr></table></td></tr></table></body></html>
`,
  },
  "leaderboard-up": {
    subject: "🚀 Bạn vừa lên hạng!",
    html: `<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>Bạn vừa lên hạng!</title></head>
<body style="margin:0;padding:0;background-color:#0f1117;font-family:'Be Vietnam Pro','Segoe UI',Roboto,Arial,sans-serif;color:#ffffff;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#0f1117;padding:32px 16px;"><tr><td align="center">
<table role="presentation" width="560" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;width:100%;background-color:#141720;border:1px solid rgba(255,255,255,0.08);border-radius:16px;overflow:hidden;">
<tr><td style="padding:32px 32px 16px 32px;text-align:center;border-bottom:1px solid rgba(255,255,255,0.06);">
<div style="display:inline-block;width:56px;height:56px;background:linear-gradient(135deg,#e8c84a,#d4b43a);border-radius:16px;line-height:56px;font-size:28px;font-weight:700;color:#0f1117;">한</div>
<h1 style="margin:16px 0 4px 0;font-size:22px;font-weight:700;color:#ffffff;">Hàn Quốc Ơi!</h1>
<p style="margin:0;font-size:13px;color:#9ca3af;">Học tiếng Hàn mỗi ngày</p>
</td></tr>
<tr><td style="padding:32px;">
<div style="text-align:center;font-size:56px;margin-bottom:16px;">🚀</div>
<h2 style="margin:0 0 8px 0;font-size:22px;font-weight:700;color:#e8c84a;text-align:center;">{{USER_NAME}} vừa lên hạng!</h2>
<p style="margin:0 0 20px 0;font-size:14px;line-height:1.6;color:#d1d5db;text-align:center;">Chúc mừng bạn đã thăng tiến trên bảng xếp hạng tuần:</p>
<div style="text-align:center;margin:24px 0;">
<table cellpadding="0" cellspacing="0" style="margin:0 auto;"><tr>
<td style="padding:0 12px;text-align:center;opacity:0.5;">
<div style="font-size:14px;color:#9ca3af;">Trước</div>
<div style="font-size:32px;font-weight:800;color:#9ca3af;">#{{OLD_RANK}}</div></td>
<td style="padding:0 12px;font-size:28px;color:#e8c84a;">→</td>
<td style="padding:0 12px;text-align:center;">
<div style="font-size:14px;color:#e8c84a;font-weight:600;">Bây giờ</div>
<div style="font-size:48px;font-weight:800;color:#e8c84a;">#{{NEW_RANK}}</div></td>
</tr></table></div>
<div style="background:linear-gradient(135deg,rgba(232,200,74,0.08),rgba(232,200,74,0.02));border:1px solid rgba(232,200,74,0.2);border-radius:12px;padding:16px;margin:20px 0;text-align:center;">
<p style="margin:0;font-size:13px;color:#d1d5db;">🎯 Lên <strong style="color:#e8c84a;">{{RANK_JUMP}} bậc</strong> với <strong style="color:#e8c84a;">{{XP_EARNED}} XP</strong></p></div>
<p style="margin:16px 0;font-size:14px;line-height:1.6;color:#d1d5db;text-align:center;">Tiếp tục phong độ này để vào <strong style="color:#e8c84a;">Top 10</strong> cuối tuần nhé!</p>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:24px auto;"><tr><td style="background-color:#e8c84a;border-radius:12px;">
<a href="{{SITE_URL}}/leaderboard" style="display:inline-block;padding:14px 32px;font-size:15px;font-weight:700;color:#0f1117;text-decoration:none;">Xem bảng xếp hạng</a>
</td></tr></table>
<div style="border-top:1px solid rgba(255,255,255,0.06);margin:24px 0;"></div>
<p style="margin:0;font-size:12px;line-height:1.6;color:#6b7280;text-align:center;">Không muốn nhận email thăng hạng? <a href="{{SITE_URL}}/settings" style="color:#9ca3af;text-decoration:underline;">Tắt trong cài đặt</a></p>
</td></tr>
<tr><td style="padding:20px 32px;background-color:rgba(255,255,255,0.02);border-top:1px solid rgba(255,255,255,0.06);text-align:center;">
<p style="margin:0 0 4px 0;font-size:12px;color:#9ca3af;">© Hàn Quốc Ơi! — Học tiếng Hàn online</p>
<p style="margin:0;font-size:11px;color:#6b7280;">Email này được gửi tự động, vui lòng không trả lời trực tiếp.</p>
</td></tr></table></td></tr></table></body></html>
`,
  },
  "daily-reminder": {
    subject: "☀️ Nhắc học tiếng Hàn hôm nay",
    html: `<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>Nhắc học hôm nay</title></head>
<body style="margin:0;padding:0;background-color:#0f1117;font-family:'Be Vietnam Pro','Segoe UI',Roboto,Arial,sans-serif;color:#ffffff;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#0f1117;padding:32px 16px;"><tr><td align="center">
<table role="presentation" width="560" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;width:100%;background-color:#141720;border:1px solid rgba(255,255,255,0.08);border-radius:16px;overflow:hidden;">
<tr><td style="padding:32px 32px 16px 32px;text-align:center;border-bottom:1px solid rgba(255,255,255,0.06);">
<div style="display:inline-block;width:56px;height:56px;background:linear-gradient(135deg,#e8c84a,#d4b43a);border-radius:16px;line-height:56px;font-size:28px;font-weight:700;color:#0f1117;">한</div>
<h1 style="margin:16px 0 4px 0;font-size:22px;font-weight:700;color:#ffffff;">Hàn Quốc Ơi!</h1>
<p style="margin:0;font-size:13px;color:#9ca3af;">Học tiếng Hàn mỗi ngày</p>
</td></tr>
<tr><td style="padding:32px;">
<div style="text-align:center;font-size:48px;margin-bottom:16px;">☀️</div>
<h2 style="margin:0 0 16px 0;font-size:22px;font-weight:700;color:#ffffff;text-align:center;">Chào {{USER_NAME}}!</h2>
<p style="margin:0 0 16px 0;font-size:14px;line-height:1.6;color:#d1d5db;text-align:center;">Bạn chưa học hôm nay. Chỉ cần <strong style="color:#e8c84a;">5 phút</strong> để giữ streak <strong style="color:#f97316;">{{STREAK_COUNT}} ngày 🔥</strong></p>
<div style="background-color:rgba(255,255,255,0.04);border:1px solid rgba(255,255,255,0.08);border-radius:12px;padding:20px;margin:20px 0;">
<p style="margin:0 0 12px 0;font-size:12px;color:#9ca3af;text-align:center;">💡 TỪ CỦA NGÀY</p>
<div style="text-align:center;">
<div style="font-size:32px;font-weight:700;color:#e8c84a;margin-bottom:4px;">{{KOREAN_WORD}}</div>
<div style="font-size:14px;color:#9ca3af;margin-bottom:8px;">[{{PRONUNCIATION}}]</div>
<div style="font-size:15px;color:#ffffff;font-weight:500;">{{MEANING_VI}}</div>
<div style="font-size:13px;color:#d1d5db;margin-top:8px;font-style:italic;">{{EXAMPLE_SENTENCE}}</div>
</div></div>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:24px auto;"><tr><td style="background-color:#e8c84a;border-radius:12px;">
<a href="{{SITE_URL}}/daily-words" style="display:inline-block;padding:14px 32px;font-size:15px;font-weight:700;color:#0f1117;text-decoration:none;">Học từ mới hôm nay</a>
</td></tr></table>
<p style="margin:16px 0 0 0;font-size:12px;line-height:1.6;color:#6b7280;text-align:center;">화이팅! Mỗi ngày một chút, tiến bộ không ngừng 💪</p>
<div style="border-top:1px solid rgba(255,255,255,0.06);margin:24px 0;"></div>
<p style="margin:0;font-size:12px;line-height:1.6;color:#6b7280;text-align:center;">Không muốn nhận nhắc nhở hằng ngày? <a href="{{SITE_URL}}/settings" style="color:#9ca3af;text-decoration:underline;">Tắt trong cài đặt</a></p>
</td></tr>
<tr><td style="padding:20px 32px;background-color:rgba(255,255,255,0.02);border-top:1px solid rgba(255,255,255,0.06);text-align:center;">
<p style="margin:0 0 4px 0;font-size:12px;color:#9ca3af;">© Hàn Quốc Ơi! — Học tiếng Hàn online</p>
<p style="margin:0;font-size:11px;color:#6b7280;">Email này được gửi tự động, vui lòng không trả lời trực tiếp.</p>
</td></tr></table></td></tr></table></body></html>
`,
  },
  "coupon-received": {
    subject: "🎁 Bạn nhận được mã giảm giá mới!",
    html: `<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>Bạn nhận được mã giảm giá!</title></head>
<body style="margin:0;padding:0;background-color:#0f1117;font-family:'Be Vietnam Pro','Segoe UI',Roboto,Arial,sans-serif;color:#ffffff;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#0f1117;padding:32px 16px;"><tr><td align="center">
<table role="presentation" width="560" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;width:100%;background-color:#141720;border:1px solid rgba(255,255,255,0.08);border-radius:16px;overflow:hidden;">
<tr><td style="padding:32px 32px 16px 32px;text-align:center;border-bottom:1px solid rgba(255,255,255,0.06);">
<div style="display:inline-block;width:56px;height:56px;background:linear-gradient(135deg,#e8c84a,#d4b43a);border-radius:16px;line-height:56px;font-size:28px;font-weight:700;color:#0f1117;">한</div>
<h1 style="margin:16px 0 4px 0;font-size:22px;font-weight:700;color:#ffffff;">Hàn Quốc Ơi!</h1>
<p style="margin:0;font-size:13px;color:#9ca3af;">Học tiếng Hàn mỗi ngày</p>
</td></tr>
<tr><td style="padding:32px;">
<div style="text-align:center;font-size:56px;margin-bottom:16px;">🎁</div>
<h2 style="margin:0 0 16px 0;font-size:22px;font-weight:700;color:#e8c84a;text-align:center;">{{USER_NAME}} ơi, quà đến rồi!</h2>
<p style="margin:0 0 20px 0;font-size:14px;line-height:1.6;color:#d1d5db;text-align:center;">{{COUPON_DESCRIPTION}}</p>
<div style="background:linear-gradient(135deg,rgba(232,200,74,0.15),rgba(232,200,74,0.05));border:2px dashed rgba(232,200,74,0.5);border-radius:12px;padding:24px;margin:20px 0;text-align:center;">
<p style="margin:0 0 8px 0;font-size:12px;color:#9ca3af;">MÃ GIẢM GIÁ</p>
<div style="font-size:32px;font-weight:800;color:#e8c84a;letter-spacing:4px;font-family:'Courier New',monospace;margin-bottom:8px;">{{COUPON_CODE}}</div>
<div style="display:inline-block;background-color:rgba(232,200,74,0.15);border-radius:999px;padding:4px 12px;">
<span style="font-size:14px;font-weight:700;color:#e8c84a;">{{DISCOUNT_VALUE}}</span></div>
</div>
<div style="background-color:rgba(255,255,255,0.04);border:1px solid rgba(255,255,255,0.08);border-radius:12px;padding:16px;margin:20px 0;">
<p style="margin:0 0 8px 0;font-size:13px;color:#d1d5db;"><strong style="color:#ffffff;">📋 Điều kiện áp dụng:</strong></p>
<ul style="margin:0;padding-left:20px;color:#9ca3af;font-size:12px;line-height:1.8;">
<li>Hết hạn: <strong style="color:#fb923c;">{{EXPIRES_AT}}</strong></li>
<li>Chỉ dùng được <strong style="color:#d1d5db;">1 lần duy nhất</strong></li>
<li>Áp dụng cho: <strong style="color:#d1d5db;">{{APPLICABLE_PLANS}}</strong></li>
</ul></div>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:24px auto;"><tr><td style="background-color:#e8c84a;border-radius:12px;">
<a href="{{SITE_URL}}/coupon" style="display:inline-block;padding:14px 32px;font-size:15px;font-weight:700;color:#0f1117;text-decoration:none;">Sử dụng mã ngay</a>
</td></tr></table>
<div style="border-top:1px solid rgba(255,255,255,0.06);margin:24px 0;"></div>
<p style="margin:0;font-size:12px;line-height:1.6;color:#6b7280;text-align:center;">Gặp vấn đề khi áp mã? Liên hệ qua mục Góp ý trong app.</p>
</td></tr>
<tr><td style="padding:20px 32px;background-color:rgba(255,255,255,0.02);border-top:1px solid rgba(255,255,255,0.06);text-align:center;">
<p style="margin:0 0 4px 0;font-size:12px;color:#9ca3af;">© Hàn Quốc Ơi! — Học tiếng Hàn online</p>
<p style="margin:0;font-size:11px;color:#6b7280;">Email này được gửi tự động, vui lòng không trả lời trực tiếp.</p>
</td></tr></table></td></tr></table></body></html>
`,
  },
  "feedback-reply": {
    subject: "💬 Admin đã phản hồi góp ý của bạn",
    html: `<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>Admin đã phản hồi góp ý của bạn</title></head>
<body style="margin:0;padding:0;background-color:#0f1117;font-family:'Be Vietnam Pro','Segoe UI',Roboto,Arial,sans-serif;color:#ffffff;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#0f1117;padding:32px 16px;"><tr><td align="center">
<table role="presentation" width="560" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;width:100%;background-color:#141720;border:1px solid rgba(255,255,255,0.08);border-radius:16px;overflow:hidden;">
<tr><td style="padding:32px 32px 16px 32px;text-align:center;border-bottom:1px solid rgba(255,255,255,0.06);">
<div style="display:inline-block;width:56px;height:56px;background:linear-gradient(135deg,#e8c84a,#d4b43a);border-radius:16px;line-height:56px;font-size:28px;font-weight:700;color:#0f1117;">한</div>
<h1 style="margin:16px 0 4px 0;font-size:22px;font-weight:700;color:#ffffff;">Hàn Quốc Ơi!</h1>
<p style="margin:0;font-size:13px;color:#9ca3af;">Học tiếng Hàn mỗi ngày</p>
</td></tr>
<tr><td style="padding:32px;">
<div style="display:inline-block;padding:6px 12px;background-color:rgba(52,211,153,0.12);border:1px solid rgba(52,211,153,0.25);border-radius:999px;margin-bottom:16px;">
<span style="font-size:12px;font-weight:600;color:#34d399;">💬 Phản hồi từ Admin</span></div>
<h2 style="margin:0 0 16px 0;font-size:20px;font-weight:600;color:#ffffff;">Chào {{USER_NAME}}!</h2>
<p style="margin:0 0 16px 0;font-size:14px;line-height:1.6;color:#d1d5db;">Cảm ơn bạn đã góp ý cho <strong style="color:#e8c84a;">Hàn Quốc Ơi!</strong> Admin đã phản hồi góp ý của bạn:</p>
<div style="background-color:rgba(255,255,255,0.03);border-left:3px solid rgba(255,255,255,0.2);border-radius:4px;padding:12px 16px;margin:20px 0;">
<p style="margin:0 0 4px 0;font-size:11px;color:#6b7280;">👤 GÓP Ý CỦA BẠN ({{FEEDBACK_DATE}})</p>
<p style="margin:0;font-size:13px;color:#9ca3af;line-height:1.6;">{{ORIGINAL_FEEDBACK}}</p></div>
<div style="background:linear-gradient(135deg,rgba(52,211,153,0.08),rgba(52,211,153,0.02));border:1px solid rgba(52,211,153,0.2);border-radius:12px;padding:16px;margin:20px 0;">
<p style="margin:0 0 8px 0;font-size:12px;color:#34d399;font-weight:600;">💬 ADMIN TRẢ LỜI</p>
<p style="margin:0;font-size:14px;color:#ffffff;line-height:1.6;">{{ADMIN_REPLY}}</p></div>
<p style="margin:16px 0;font-size:13px;line-height:1.6;color:#d1d5db;">Mọi góp ý của bạn đều giúp chúng mình cải thiện ứng dụng tốt hơn mỗi ngày. Cảm ơn bạn rất nhiều! 🙏</p>
<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:24px auto;"><tr><td style="background-color:#e8c84a;border-radius:12px;">
<a href="{{SITE_URL}}/feedback" style="display:inline-block;padding:14px 32px;font-size:15px;font-weight:700;color:#0f1117;text-decoration:none;">Xem chi tiết trong app</a>
</td></tr></table>
<div style="border-top:1px solid rgba(255,255,255,0.06);margin:24px 0;"></div>
<p style="margin:0;font-size:12px;line-height:1.6;color:#6b7280;text-align:center;">Có thêm góp ý? Gửi tiếp qua mục <strong style="color:#d1d5db;">Góp ý</strong> trong app nhé!</p>
</td></tr>
<tr><td style="padding:20px 32px;background-color:rgba(255,255,255,0.02);border-top:1px solid rgba(255,255,255,0.06);text-align:center;">
<p style="margin:0 0 4px 0;font-size:12px;color:#9ca3af;">© Hàn Quốc Ơi! — Học tiếng Hàn online</p>
<p style="margin:0;font-size:11px;color:#6b7280;">Email này được gửi tự động, vui lòng không trả lời trực tiếp.</p>
</td></tr></table></td></tr></table></body></html>
`,
  },
};
