// Batch 2: Sports, Arts, Geography, History, Culture, Daily life
export const BATCH2_SPORTS = [
  { korean: "운동", hanja: "運動", vietnamese: "Vận động, Thể thao" },
  { korean: "체육", hanja: "體育", vietnamese: "Thể dục" },
  { korean: "선수", hanja: "選手", vietnamese: "Tuyển thủ, Vận động viên" },
  { korean: "감독", hanja: "監督", vietnamese: "Giám đốc, Huấn luyện viên" },
  { korean: "코치", hanja: "", vietnamese: "Huấn luyện viên" },
  { korean: "심판", hanja: "審判", vietnamese: "Thẩm phán, Trọng tài" },
  { korean: "경기장", hanja: "競技場", vietnamese: "Sân thi đấu" },
  { korean: "체육관", hanja: "體育館", vietnamese: "Nhà thể thao" },
  { korean: "운동장", hanja: "運動場", vietnamese: "Sân vận động" },
  { korean: "야구", hanja: "野球", vietnamese: "Dã cầu, Bóng chày" },
  { korean: "축구", hanja: "蹴球", vietnamese: "Túc cầu, Bóng đá" },
  { korean: "농구", hanja: "籠球", vietnamese: "Lung cầu, Bóng rổ" },
  { korean: "배구", hanja: "排球", vietnamese: "Bài cầu, Bóng chuyền" },
  { korean: "탁구", hanja: "卓球", vietnamese: "Trác cầu, Bóng bàn" },
  { korean: "정구", hanja: "庭球", vietnamese: "Đình cầu, Tennis" },
  { korean: "골프", hanja: "", vietnamese: "Golf" },
  { korean: "수영", hanja: "水泳", vietnamese: "Thủy vĩnh, Bơi lội" },
  { korean: "육상", hanja: "陸上", vietnamese: "Lục thượng, Điền kinh" },
  { korean: "권투", hanja: "拳鬪", vietnamese: "Quyền đấu, Đấm bốc" },
  { korean: "유도", hanja: "柔道", vietnamese: "Nhu đạo" },
  { korean: "태권도", hanja: "跆拳道", vietnamese: "Thái quyền đạo" },
  { korean: "검도", hanja: "劍道", vietnamese: "Kiếm đạo" },
  { korean: "무술", hanja: "武術", vietnamese: "Võ thuật" },
  { korean: "무예", hanja: "武藝", vietnamese: "Võ nghệ" },
  { korean: "체조", hanja: "體操", vietnamese: "Thể thao, Thể dục dụng cụ" },
  { korean: "사격", hanja: "射擊", vietnamese: "Xạ kích, Bắn súng" },
  { korean: "승마", hanja: "乘馬", vietnamese: "Thừa mã, Cưỡi ngựa" },
  { korean: "경주", hanja: "競走", vietnamese: "Cạnh tẩu, Chạy đua" },
  { korean: "대회", hanja: "大會", vietnamese: "Đại hội" },
  { korean: "올림픽", hanja: "", vietnamese: "Olympic" },
  { korean: "월드컵", hanja: "", vietnamese: "World Cup" },
  { korean: "결승", hanja: "決勝", vietnamese: "Quyết thắng, Chung kết" },
  { korean: "준결승", hanja: "準決勝", vietnamese: "Chuẩn quyết thắng, Bán kết" },
  { korean: "예선", hanja: "豫選", vietnamese: "Dự tuyển, Vòng loại" },
  { korean: "본선", hanja: "本選", vietnamese: "Bản tuyển, Vòng chính" },
  { korean: "우승", hanja: "優勝", vietnamese: "Ưu thắng, Vô địch" },
  { korean: "준우승", hanja: "準優勝", vietnamese: "Chuẩn ưu thắng, Á quân" },
  { korean: "금메달", hanja: "金", vietnamese: "Huy chương vàng" },
  { korean: "은메달", hanja: "銀", vietnamese: "Huy chương bạc" },
  { korean: "동메달", hanja: "銅", vietnamese: "Huy chương đồng" },
  { korean: "입상", hanja: "入賞", vietnamese: "Nhập thưởng, Đoạt giải" },
  { korean: "상금", hanja: "賞金", vietnamese: "Thưởng kim, Tiền thưởng" },
  { korean: "응원", hanja: "應援", vietnamese: "Ứng viện, Cổ vũ" },
  { korean: "관중", hanja: "觀衆", vietnamese: "Quan chúng, Khán giả" },
  { korean: "기록", hanja: "記錄", vietnamese: "Ký lục, Kỷ lục" },
  { korean: "경신", hanja: "更新", vietnamese: "Canh tân, Cập nhật, Phá kỷ lục" },
  { korean: "체력", hanja: "體力", vietnamese: "Thể lực" },
  { korean: "지구력", hanja: "持久力", vietnamese: "Trì cửu lực, Sức bền" },
  { korean: "근력", hanja: "筋力", vietnamese: "Cân lực, Sức cơ" },
  { korean: "훈련", hanja: "訓鍊", vietnamese: "Huấn luyện" },
  { korean: "연습", hanja: "練習", vietnamese: "Luyện tập" },
  { korean: "승부", hanja: "勝負", vietnamese: "Thắng phụ, Thắng thua" },
  { korean: "승리", hanja: "勝利", vietnamese: "Thắng lợi" },
  { korean: "패배", hanja: "敗北", vietnamese: "Bại bắc, Thua cuộc" },
  { korean: "무승부", hanja: "無勝負", vietnamese: "Vô thắng phụ, Hòa" },
  { korean: "전적", hanja: "戰績", vietnamese: "Chiến tích, Thành tích thi đấu" },
];

export const BATCH2_ARTS = [
  // Âm nhạc
  { korean: "악기", hanja: "樂器", vietnamese: "Nhạc khí, Nhạc cụ" },
  { korean: "악보", hanja: "樂譜", vietnamese: "Nhạc phổ, Bản nhạc" },
  { korean: "작곡", hanja: "作曲", vietnamese: "Tác khúc, Sáng tác" },
  { korean: "작곡가", hanja: "作曲家", vietnamese: "Nhà soạn nhạc" },
  { korean: "작사", hanja: "作詞", vietnamese: "Tác từ, Viết lời" },
  { korean: "작사가", hanja: "作詞家", vietnamese: "Người viết lời" },
  { korean: "가수", hanja: "歌手", vietnamese: "Ca thủ, Ca sĩ" },
  { korean: "가창력", hanja: "歌唱力", vietnamese: "Khả năng ca hát" },
  { korean: "음반", hanja: "音盤", vietnamese: "Âm bàn, Đĩa nhạc" },
  { korean: "음색", hanja: "音色", vietnamese: "Âm sắc" },
  { korean: "음조", hanja: "音調", vietnamese: "Âm điệu" },
  { korean: "음악회", hanja: "音樂會", vietnamese: "Nhạc hội, Buổi hòa nhạc" },
  { korean: "공연", hanja: "公演", vietnamese: "Công diễn, Biểu diễn" },
  { korean: "독주", hanja: "獨奏", vietnamese: "Độc tấu" },
  { korean: "합주", hanja: "合奏", vietnamese: "Hợp tấu" },
  { korean: "합창", hanja: "合唱", vietnamese: "Hợp xướng" },
  { korean: "독창", hanja: "獨唱", vietnamese: "Độc xướng, Đơn ca" },
  { korean: "관현악", hanja: "管絃樂", vietnamese: "Quản huyền nhạc, Nhạc giao hưởng" },
  { korean: "교향곡", hanja: "交響曲", vietnamese: "Giao hưởng khúc" },
  { korean: "가곡", hanja: "歌曲", vietnamese: "Ca khúc" },
  { korean: "가요제", hanja: "歌謠祭", vietnamese: "Lễ hội âm nhạc" },
  { korean: "민요", hanja: "民謠", vietnamese: "Dân dao, Dân ca" },
  { korean: "동요", hanja: "童謠", vietnamese: "Đồng dao" },
  { korean: "국악", hanja: "國樂", vietnamese: "Quốc nhạc, Nhạc cổ truyền Hàn" },
  { korean: "양악", hanja: "洋樂", vietnamese: "Dương nhạc, Nhạc phương Tây" },
  
  // Mỹ thuật
  { korean: "화가", hanja: "畵家", vietnamese: "Họa gia, Họa sĩ" },
  { korean: "화풍", hanja: "畵風", vietnamese: "Họa phong, Phong cách vẽ" },
  { korean: "작화", hanja: "作畵", vietnamese: "Tác họa, Vẽ tranh" },
  { korean: "초상화", hanja: "肖像畵", vietnamese: "Tranh chân dung" },
  { korean: "풍경화", hanja: "風景畵", vietnamese: "Tranh phong cảnh" },
  { korean: "정물화", hanja: "靜物畵", vietnamese: "Tranh tĩnh vật" },
  { korean: "추상화", hanja: "抽象畵", vietnamese: "Tranh trừu tượng" },
  { korean: "동양화", hanja: "東洋畵", vietnamese: "Tranh Đông phương" },
  { korean: "서양화", hanja: "西洋畵", vietnamese: "Tranh phương Tây" },
  { korean: "수채화", hanja: "水彩畵", vietnamese: "Tranh thủy mặc, Màu nước" },
  { korean: "유화", hanja: "油畵", vietnamese: "Du họa, Tranh sơn dầu" },
  { korean: "벽화", hanja: "壁畵", vietnamese: "Bích họa, Tranh tường" },
  { korean: "만화", hanja: "漫畵", vietnamese: "Mạn họa, Truyện tranh" },
  { korean: "삽화", hanja: "揷畵", vietnamese: "Sáp họa, Tranh minh họa" },
  { korean: "전시", hanja: "展示", vietnamese: "Trưng bày" },
  { korean: "전시회", hanja: "展示會", vietnamese: "Triển lãm" },
  { korean: "미술관", hanja: "美術館", vietnamese: "Bảo tàng mỹ thuật" },
  { korean: "박물관", hanja: "博物館", vietnamese: "Bảo tàng" },
  { korean: "유물", hanja: "遺物", vietnamese: "Di vật" },
  { korean: "골동품", hanja: "骨董品", vietnamese: "Cổ vật, Đồ cổ" },
  { korean: "작품집", hanja: "作品集", vietnamese: "Tuyển tập tác phẩm" },
  
  // Sân khấu
  { korean: "배우", hanja: "俳優", vietnamese: "Bài ưu, Diễn viên" },
  { korean: "주연", hanja: "主演", vietnamese: "Chủ diễn, Vai chính" },
  { korean: "조연", hanja: "助演", vietnamese: "Trợ diễn, Vai phụ" },
  { korean: "단역", hanja: "端役", vietnamese: "Đoan dịch, Vai nhỏ" },
  { korean: "연기", hanja: "演技", vietnamese: "Diễn kỹ, Diễn xuất" },
  { korean: "연출", hanja: "演出", vietnamese: "Diễn xuất, Đạo diễn" },
  { korean: "공연장", hanja: "公演場", vietnamese: "Hội trường biểu diễn" },
  { korean: "극장", hanja: "劇場", vietnamese: "Kịch trường, Rạp hát" },
  { korean: "무대", hanja: "舞臺", vietnamese: "Vũ đài, Sân khấu" },
  { korean: "관객", hanja: "觀客", vietnamese: "Quan khách, Khán giả" },
  { korean: "입장권", hanja: "入場券", vietnamese: "Nhập trường khuyến, Vé vào" },
  { korean: "매표소", hanja: "賣票所", vietnamese: "Mại phiếu sở, Quầy bán vé" },
  
  // Thời trang
  { korean: "의상", hanja: "衣裳", vietnamese: "Y thường, Trang phục" },
  { korean: "복장", hanja: "服裝", vietnamese: "Phục trang, Trang phục" },
  { korean: "한복", hanja: "韓服", vietnamese: "Hàn phục, Trang phục Hàn" },
  { korean: "양복", hanja: "洋服", vietnamese: "Dương phục, Âu phục" },
  { korean: "교복", hanja: "校服", vietnamese: "Đồng phục học sinh" },
  { korean: "군복", hanja: "軍服", vietnamese: "Quân phục" },
  { korean: "예복", hanja: "禮服", vietnamese: "Lễ phục" },
  { korean: "정장", hanja: "正裝", vietnamese: "Chính trang, Com-lê" },
  { korean: "액세서리", hanja: "", vietnamese: "Phụ kiện" },
  { korean: "장신구", hanja: "裝身具", vietnamese: "Trang thân cụ, Đồ trang sức" },
];

export const BATCH2_GEOGRAPHY = [
  { korean: "지리", hanja: "地理", vietnamese: "Địa lý" },
  { korean: "지도", hanja: "地圖", vietnamese: "Địa đồ, Bản đồ" },
  { korean: "지형", hanja: "地形", vietnamese: "Địa hình" },
  { korean: "지역", hanja: "地域", vietnamese: "Địa vực, Khu vực" },
  { korean: "구역", hanja: "區域", vietnamese: "Khu vực" },
  { korean: "영역", hanja: "領域", vietnamese: "Lãnh vực" },
  { korean: "지구", hanja: "地球", vietnamese: "Địa cầu, Trái Đất" },
  { korean: "대륙", hanja: "大陸", vietnamese: "Đại lục, Lục địa" },
  { korean: "반도", hanja: "半島", vietnamese: "Bán đảo" },
  { korean: "섬", hanja: "島", vietnamese: "Đảo" },
  { korean: "열도", hanja: "列島", vietnamese: "Liệt đảo, Quần đảo" },
  { korean: "해협", hanja: "海峽", vietnamese: "Hải hiệp, Eo biển" },
  { korean: "만", hanja: "灣", vietnamese: "Vịnh" },
  { korean: "항구", hanja: "港口", vietnamese: "Cảng khẩu, Hải cảng" },
  { korean: "해안", hanja: "海岸", vietnamese: "Hải ngạn, Bờ biển" },
  { korean: "해변", hanja: "海邊", vietnamese: "Bờ biển" },
  { korean: "해양", hanja: "海洋", vietnamese: "Hải dương, Biển" },
  { korean: "태평양", hanja: "太平洋", vietnamese: "Thái Bình Dương" },
  { korean: "대서양", hanja: "大西洋", vietnamese: "Đại Tây Dương" },
  { korean: "인도양", hanja: "印度洋", vietnamese: "Ấn Độ Dương" },
  { korean: "북극", hanja: "北極", vietnamese: "Bắc Cực" },
  { korean: "남극", hanja: "南極", vietnamese: "Nam Cực" },
  { korean: "적도", hanja: "赤道", vietnamese: "Xích đạo" },
  { korean: "산맥", hanja: "山脈", vietnamese: "Dãy núi" },
  { korean: "산봉", hanja: "山峯", vietnamese: "Sơn phong, Đỉnh núi" },
  { korean: "정상", hanja: "頂上", vietnamese: "Đỉnh thượng, Đỉnh núi" },
  { korean: "평야", hanja: "平野", vietnamese: "Bình dã, Đồng bằng" },
  { korean: "고원", hanja: "高原", vietnamese: "Cao nguyên" },
  { korean: "분지", hanja: "盆地", vietnamese: "Bồn địa" },
  { korean: "사막", hanja: "沙漠", vietnamese: "Sa mạc" },
  { korean: "초원", hanja: "草原", vietnamese: "Thảo nguyên" },
  { korean: "산림", hanja: "山林", vietnamese: "Sơn lâm, Rừng núi" },
  { korean: "삼림", hanja: "森林", vietnamese: "Sâm lâm, Rừng rậm" },
  { korean: "습지", hanja: "濕地", vietnamese: "Thấp địa, Đầm lầy" },
  { korean: "하천", hanja: "河川", vietnamese: "Hà xuyên, Sông suối" },
  { korean: "호수", hanja: "湖水", vietnamese: "Hồ thủy, Hồ" },
  { korean: "폭포", hanja: "瀑布", vietnamese: "Bộc bố, Thác nước" },
  { korean: "계곡", hanja: "溪谷", vietnamese: "Khê cốc, Thung lũng" },
  { korean: "동굴", hanja: "洞窟", vietnamese: "Hang động" },
  { korean: "화산", hanja: "火山", vietnamese: "Núi lửa" },
  { korean: "온천", hanja: "溫泉", vietnamese: "Suối nước nóng" },
  { korean: "지하", hanja: "地下", vietnamese: "Địa hạ, Ngầm" },
  { korean: "지상", hanja: "地上", vietnamese: "Địa thượng, Trên mặt đất" },
  { korean: "기온", hanja: "氣溫", vietnamese: "Khí ôn, Nhiệt độ không khí" },
  { korean: "강수량", hanja: "降水量", vietnamese: "Lượng mưa" },
  { korean: "습도", hanja: "濕度", vietnamese: "Độ ẩm" },
  { korean: "일기", hanja: "日氣", vietnamese: "Nhật khí, Thời tiết" },
  { korean: "기상", hanja: "氣象", vietnamese: "Khí tượng" },
  { korean: "기상청", hanja: "氣象廳", vietnamese: "Cơ quan khí tượng" },
  { korean: "수도", hanja: "首都", vietnamese: "Thủ đô" },
  { korean: "도시", hanja: "都市", vietnamese: "Đô thị" },
  { korean: "농촌", hanja: "農村", vietnamese: "Nông thôn" },
  { korean: "어촌", hanja: "漁村", vietnamese: "Ngư thôn, Làng chài" },
  { korean: "지방", hanja: "地方", vietnamese: "Địa phương" },
  { korean: "교외", hanja: "郊外", vietnamese: "Giao ngoại, Ngoại ô" },
  { korean: "도심", hanja: "都心", vietnamese: "Đô tâm, Trung tâm thành phố" },
  { korean: "주택가", hanja: "住宅街", vietnamese: "Khu dân cư" },
  { korean: "상가", hanja: "商街", vietnamese: "Khu thương mại" },
  { korean: "공업단지", hanja: "工業團地", vietnamese: "Khu công nghiệp" },
  { korean: "아시아", hanja: "", vietnamese: "Châu Á" },
  { korean: "유럽", hanja: "", vietnamese: "Châu Âu" },
  { korean: "아프리카", hanja: "", vietnamese: "Châu Phi" },
  { korean: "북미", hanja: "北美", vietnamese: "Bắc Mỹ" },
  { korean: "남미", hanja: "南美", vietnamese: "Nam Mỹ" },
  { korean: "동아시아", hanja: "東아시아", vietnamese: "Đông Á" },
  { korean: "동남아", hanja: "東南아", vietnamese: "Đông Nam Á" },
  { korean: "중동", hanja: "中東", vietnamese: "Trung Đông" },
  { korean: "한국", hanja: "韓國", vietnamese: "Hàn Quốc" },
  { korean: "북한", hanja: "北韓", vietnamese: "Bắc Hàn" },
  { korean: "남한", hanja: "南韓", vietnamese: "Nam Hàn" },
  { korean: "일본", hanja: "日本", vietnamese: "Nhật Bản" },
  { korean: "중국", hanja: "中國", vietnamese: "Trung Quốc" },
  { korean: "베트남", hanja: "", vietnamese: "Việt Nam" },
  { korean: "미국", hanja: "美國", vietnamese: "Mỹ quốc" },
  { korean: "영국", hanja: "英國", vietnamese: "Anh quốc" },
  { korean: "프랑스", hanja: "", vietnamese: "Pháp" },
  { korean: "독일", hanja: "獨逸", vietnamese: "Đức" },
  { korean: "러시아", hanja: "", vietnamese: "Nga" },
  { korean: "인도", hanja: "印度", vietnamese: "Ấn Độ" },
  { korean: "호주", hanja: "濠洲", vietnamese: "Úc" },
];

export const BATCH2_HISTORY = [
  { korean: "역사", hanja: "歷史", vietnamese: "Lịch sử" },
  { korean: "역사가", hanja: "歷史家", vietnamese: "Sử gia" },
  { korean: "사학", hanja: "史學", vietnamese: "Sử học" },
  { korean: "사료", hanja: "史料", vietnamese: "Sử liệu" },
  { korean: "기원", hanja: "起源", vietnamese: "Khởi nguyên, Nguồn gốc" },
  { korean: "유래", hanja: "由來", vietnamese: "Do lai, Xuất xứ" },
  { korean: "고대", hanja: "古代", vietnamese: "Cổ đại" },
  { korean: "중세", hanja: "中世", vietnamese: "Trung thế, Trung cổ" },
  { korean: "근대", hanja: "近代", vietnamese: "Cận đại" },
  { korean: "현대", hanja: "現代", vietnamese: "Hiện đại" },
  { korean: "근세", hanja: "近世", vietnamese: "Cận thế" },
  { korean: "시대", hanja: "時代", vietnamese: "Thời đại" },
  { korean: "세기", hanja: "世紀", vietnamese: "Thế kỷ" },
  { korean: "연대", hanja: "年代", vietnamese: "Niên đại" },
  { korean: "왕조", hanja: "王朝", vietnamese: "Vương triều" },
  { korean: "왕권", hanja: "王權", vietnamese: "Vương quyền" },
  { korean: "왕위", hanja: "王位", vietnamese: "Vương vị, Ngôi vua" },
  { korean: "즉위", hanja: "卽位", vietnamese: "Tức vị, Lên ngôi" },
  { korean: "퇴위", hanja: "退位", vietnamese: "Thoái vị" },
  { korean: "왕자", hanja: "王子", vietnamese: "Vương tử, Hoàng tử" },
  { korean: "공주", hanja: "公主", vietnamese: "Công chúa" },
  { korean: "왕비", hanja: "王妃", vietnamese: "Vương phi, Hoàng hậu" },
  { korean: "왕후", hanja: "王后", vietnamese: "Vương hậu" },
  { korean: "황제", hanja: "皇帝", vietnamese: "Hoàng đế" },
  { korean: "황실", hanja: "皇室", vietnamese: "Hoàng thất" },
  { korean: "귀족", hanja: "貴族", vietnamese: "Quý tộc" },
  { korean: "양반", hanja: "兩班", vietnamese: "Lưỡng ban" },
  { korean: "평민", hanja: "平民", vietnamese: "Bình dân, Thường dân" },
  { korean: "노비", hanja: "奴婢", vietnamese: "Nô tỳ" },
  { korean: "신하", hanja: "臣下", vietnamese: "Thần hạ, Bầy tôi" },
  { korean: "장군", hanja: "將軍", vietnamese: "Tướng quân" },
  { korean: "대신", hanja: "大臣", vietnamese: "Đại thần" },
  { korean: "재상", hanja: "宰相", vietnamese: "Tể tướng" },
  { korean: "관료", hanja: "官僚", vietnamese: "Quan liêu, Quan chức" },
  { korean: "관직", hanja: "官職", vietnamese: "Quan chức" },
  { korean: "과거", hanja: "科擧", vietnamese: "Khoa cử" },
  { korean: "국사", hanja: "國史", vietnamese: "Quốc sử" },
  { korean: "세계사", hanja: "世界史", vietnamese: "Thế giới sử" },
  { korean: "침략", hanja: "侵略", vietnamese: "Xâm lược" },
  { korean: "침공", hanja: "侵攻", vietnamese: "Xâm công" },
  { korean: "정복", hanja: "征服", vietnamese: "Chinh phục" },
  { korean: "식민", hanja: "植民", vietnamese: "Thực dân" },
  { korean: "식민지", hanja: "植民地", vietnamese: "Thuộc địa" },
  { korean: "광복", hanja: "光復", vietnamese: "Quang phục, Giải phóng" },
  { korean: "해방", hanja: "解放", vietnamese: "Giải phóng" },
  { korean: "건국", hanja: "建國", vietnamese: "Kiến quốc, Lập quốc" },
  { korean: "멸망", hanja: "滅亡", vietnamese: "Diệt vong" },
  { korean: "망국", hanja: "亡國", vietnamese: "Vong quốc, Mất nước" },
  { korean: "항쟁", hanja: "抗爭", vietnamese: "Kháng tranh" },
  { korean: "저항", hanja: "抵抗", vietnamese: "Để kháng, Kháng cự" },
  { korean: "항일", hanja: "抗日", vietnamese: "Chống Nhật" },
  { korean: "독립운동", hanja: "獨立運動", vietnamese: "Phong trào độc lập" },
  { korean: "조약", hanja: "條約", vietnamese: "Điều ước" },
  { korean: "동맹국", hanja: "同盟國", vietnamese: "Nước đồng minh" },
  { korean: "중립국", hanja: "中立國", vietnamese: "Nước trung lập" },
  { korean: "강대국", hanja: "强大國", vietnamese: "Cường quốc" },
  { korean: "선조", hanja: "先祖", vietnamese: "Tổ tiên" },
  { korean: "후손", hanja: "後孫", vietnamese: "Hậu tôn, Con cháu" },
  { korean: "조상", hanja: "祖上", vietnamese: "Tổ tiên" },
  { korean: "계승", hanja: "繼承", vietnamese: "Kế thừa" },
  { korean: "계보", hanja: "系譜", vietnamese: "Hệ phổ, Gia phả" },
  { korean: "족보", hanja: "族譜", vietnamese: "Tộc phổ, Gia phả" },
  { korean: "유산", hanja: "遺産", vietnamese: "Di sản" },
  { korean: "문화재", hanja: "文化財", vietnamese: "Văn hóa tài, Di sản văn hóa" },
  { korean: "사적", hanja: "史蹟", vietnamese: "Sử tích, Di tích lịch sử" },
  { korean: "유적", hanja: "遺蹟", vietnamese: "Di tích" },
  { korean: "발굴", hanja: "發掘", vietnamese: "Phát quật, Khai quật" },
  { korean: "고고학", hanja: "考古學", vietnamese: "Khảo cổ học" },
];

export const BATCH2_DAILY = [
  // Sinh hoạt / Đời sống
  { korean: "생활", hanja: "生活", vietnamese: "Sinh hoạt, Đời sống" },
  { korean: "생계", hanja: "生計", vietnamese: "Sinh kế" },
  { korean: "일상", hanja: "日常", vietnamese: "Nhật thường, Hằng ngày" },
  { korean: "일과", hanja: "日課", vietnamese: "Nhật khóa, Lịch trình ngày" },
  { korean: "습관", hanja: "習慣", vietnamese: "Tập quán, Thói quen" },
  { korean: "취미", hanja: "趣味", vietnamese: "Thú vị, Sở thích" },
  { korean: "여가", hanja: "餘暇", vietnamese: "Dư hạ, Thời gian rảnh" },
  { korean: "휴식", hanja: "休息", vietnamese: "Hưu tức, Nghỉ ngơi" },
  { korean: "휴가", hanja: "休暇", vietnamese: "Hưu hạ, Kỳ nghỉ" },
  { korean: "방학", hanja: "放學", vietnamese: "Phóng học, Nghỉ học" },
  { korean: "여행", hanja: "旅行", vietnamese: "Lữ hành, Du lịch" },
  { korean: "관광", hanja: "觀光", vietnamese: "Quan quang, Tham quan" },
  { korean: "관광객", hanja: "觀光客", vietnamese: "Quan quang khách, Du khách" },
  { korean: "명소", hanja: "名所", vietnamese: "Danh sở, Điểm nổi tiếng" },
  { korean: "명승지", hanja: "名勝地", vietnamese: "Danh thắng địa, Thắng cảnh" },
  { korean: "숙박", hanja: "宿泊", vietnamese: "Túc bạc, Nghỉ qua đêm" },
  { korean: "숙소", hanja: "宿所", vietnamese: "Túc sở, Nơi nghỉ" },
  { korean: "호텔", hanja: "", vietnamese: "Khách sạn" },
  { korean: "여관", hanja: "旅館", vietnamese: "Lữ quán, Nhà nghỉ" },
  { korean: "민박", hanja: "民泊", vietnamese: "Dân bạc, Homestay" },
  { korean: "식당", hanja: "食堂", vietnamese: "Thực đường, Quán ăn" },
  { korean: "음식점", hanja: "飮食店", vietnamese: "Ẩm thực điếm, Nhà hàng" },
  { korean: "식사", hanja: "食事", vietnamese: "Thực sự, Bữa ăn" },
  { korean: "조식", hanja: "朝食", vietnamese: "Triêu thực, Bữa sáng" },
  { korean: "중식", hanja: "中食", vietnamese: "Trung thực, Bữa trưa" },
  { korean: "석식", hanja: "夕食", vietnamese: "Tịch thực, Bữa tối" },
  { korean: "간식", hanja: "間食", vietnamese: "Gian thực, Đồ ăn vặt" },
  { korean: "야식", hanja: "夜食", vietnamese: "Dạ thực, Đồ ăn khuya" },
  { korean: "음료", hanja: "飮料", vietnamese: "Ẩm liệu, Đồ uống" },
  { korean: "음주", hanja: "飮酒", vietnamese: "Ẩm tửu, Uống rượu" },
  { korean: "흡연", hanja: "吸煙", vietnamese: "Hút thuốc" },
  { korean: "금연", hanja: "禁煙", vietnamese: "Cấm hút thuốc" },
  { korean: "금주", hanja: "禁酒", vietnamese: "Cấm rượu" },
  { korean: "건강", hanja: "健康", vietnamese: "Sức khỏe" },
  { korean: "위생", hanja: "衛生", vietnamese: "Vệ sinh" },
  { korean: "청결", hanja: "淸潔", vietnamese: "Thanh khiết, Sạch sẽ" },
  { korean: "청소", hanja: "淸掃", vietnamese: "Thanh tảo, Dọn dẹp" },
  { korean: "세탁", hanja: "洗濯", vietnamese: "Tẩy trạc, Giặt giũ" },
  { korean: "정리", hanja: "整理", vietnamese: "Chỉnh lý" },
  { korean: "정돈", hanja: "整頓", vietnamese: "Chỉnh đốn" },
  { korean: "주거", hanja: "住居", vietnamese: "Trú cư, Cư trú" },
  { korean: "주택", hanja: "住宅", vietnamese: "Trú trạch, Nhà ở" },
  { korean: "거주", hanja: "居住", vietnamese: "Cư trú" },
  { korean: "이사", hanja: "移徙", vietnamese: "Di tỉ, Chuyển nhà" },
  { korean: "세입자", hanja: "貰入者", vietnamese: "Người thuê nhà" },
  { korean: "집주인", hanja: "", vietnamese: "Chủ nhà" },
  { korean: "월세", hanja: "月貰", vietnamese: "Nguyệt thuế, Thuê tháng" },
  { korean: "전세", hanja: "傳貰", vietnamese: "Truyền thuế, Thuê ký quỹ" },
  { korean: "임대", hanja: "賃貸", vietnamese: "Nhiệm đại, Cho thuê" },
  { korean: "매매", hanja: "賣買", vietnamese: "Mại mãi, Mua bán" },
  { korean: "부동산", hanja: "不動産", vietnamese: "Bất động sản" },
  { korean: "건물", hanja: "建物", vietnamese: "Kiến vật, Tòa nhà" },
  { korean: "건축", hanja: "建築", vietnamese: "Kiến trúc" },
  { korean: "건축물", hanja: "建築物", vietnamese: "Công trình kiến trúc" },
  { korean: "교통", hanja: "交通", vietnamese: "Giao thông" },
  { korean: "교통수단", hanja: "交通手段", vietnamese: "Phương tiện giao thông" },
  { korean: "차량", hanja: "車輛", vietnamese: "Xa lượng, Phương tiện" },
  { korean: "자가용", hanja: "自家用", vietnamese: "Tự gia dụng, Xe riêng" },
  { korean: "대중교통", hanja: "大衆交通", vietnamese: "Giao thông công cộng" },
  { korean: "지하철", hanja: "地下鐵", vietnamese: "Tàu điện ngầm" },
  { korean: "철도", hanja: "鐵道", vietnamese: "Thiết đạo, Đường sắt" },
  { korean: "선로", hanja: "線路", vietnamese: "Tuyến lộ, Đường ray" },
  { korean: "도로", hanja: "道路", vietnamese: "Đường sá" },
  { korean: "고속도로", hanja: "高速道路", vietnamese: "Đường cao tốc" },
  { korean: "신호등", hanja: "信號燈", vietnamese: "Đèn tín hiệu" },
  { korean: "횡단보도", hanja: "橫斷步道", vietnamese: "Vạch qua đường" },
  { korean: "보행자", hanja: "步行者", vietnamese: "Người đi bộ" },
  { korean: "운전", hanja: "運轉", vietnamese: "Vận chuyển, Lái xe" },
  { korean: "운전자", hanja: "運轉者", vietnamese: "Người lái xe" },
  { korean: "운전면허", hanja: "運轉免許", vietnamese: "Giấy phép lái xe" },
  { korean: "주차", hanja: "駐車", vietnamese: "Trú xa, Đỗ xe" },
  { korean: "주차장", hanja: "駐車場", vietnamese: "Bãi đỗ xe" },
  { korean: "교통사고", hanja: "交通事故", vietnamese: "Tai nạn giao thông" },
  { korean: "사고", hanja: "事故", vietnamese: "Sự cố, Tai nạn" },
  { korean: "부상자", hanja: "負傷者", vietnamese: "Người bị thương" },
  { korean: "사망자", hanja: "死亡者", vietnamese: "Người tử vong" },
  
  // Thời gian
  { korean: "시간", hanja: "時間", vietnamese: "Thời gian" },
  { korean: "시각", hanja: "時刻", vietnamese: "Thời khắc, Giờ khắc" },
  { korean: "시기", hanja: "時期", vietnamese: "Thời kỳ" },
  { korean: "기간", hanja: "期間", vietnamese: "Kỳ gian, Khoảng thời gian" },
  { korean: "순간", hanja: "瞬間", vietnamese: "Thuấn gian, Khoảnh khắc" },
  { korean: "영원", hanja: "永遠", vietnamese: "Vĩnh viễn" },
  { korean: "영구", hanja: "永久", vietnamese: "Vĩnh cửu" },
  { korean: "당시", hanja: "當時", vietnamese: "Đương thời" },
  { korean: "평소", hanja: "平素", vietnamese: "Bình tố, Thường ngày" },
  { korean: "평상시", hanja: "平常時", vietnamese: "Bình thường thời, Bình thường" },
  { korean: "과거", hanja: "過去", vietnamese: "Quá khứ" },
  { korean: "미래", hanja: "未來", vietnamese: "Tương lai" },
  { korean: "장래", hanja: "將來", vietnamese: "Tương lai, Sau này" },
];

export const ALL_BATCH2 = [
  ...BATCH2_SPORTS,
  ...BATCH2_ARTS,
  ...BATCH2_GEOGRAPHY,
  ...BATCH2_HISTORY,
  ...BATCH2_DAILY,
];

console.log("Total batch 2 entries:", ALL_BATCH2.length);
