// Batch 3: Military, Nature, Emotions, Food, Human body, Abstract concepts
export const BATCH3_MILITARY = [
  { korean: "군대", hanja: "軍隊", vietnamese: "Quân đội" },
  { korean: "군인", hanja: "軍人", vietnamese: "Quân nhân" },
  { korean: "병사", hanja: "兵士", vietnamese: "Binh sĩ" },
  { korean: "군사", hanja: "軍事", vietnamese: "Quân sự" },
  { korean: "군사력", hanja: "軍事力", vietnamese: "Quân sự lực, Sức mạnh quân sự" },
  { korean: "육군", hanja: "陸軍", vietnamese: "Lục quân" },
  { korean: "해군", hanja: "海軍", vietnamese: "Hải quân" },
  { korean: "공군", hanja: "空軍", vietnamese: "Không quân" },
  { korean: "해병대", hanja: "海兵隊", vietnamese: "Hải quân lục chiến" },
  { korean: "특수부대", hanja: "特殊部隊", vietnamese: "Đơn vị đặc nhiệm" },
  { korean: "계급", hanja: "階級", vietnamese: "Giai cấp, Cấp bậc" },
  { korean: "대위", hanja: "大尉", vietnamese: "Đại úy" },
  { korean: "중위", hanja: "中尉", vietnamese: "Trung úy" },
  { korean: "소위", hanja: "少尉", vietnamese: "Thiếu úy" },
  { korean: "대령", hanja: "大領", vietnamese: "Đại tá" },
  { korean: "중령", hanja: "中領", vietnamese: "Trung tá" },
  { korean: "소령", hanja: "少領", vietnamese: "Thiếu tá" },
  { korean: "상사", hanja: "上士", vietnamese: "Thượng sĩ" },
  { korean: "중사", hanja: "中士", vietnamese: "Trung sĩ" },
  { korean: "병장", hanja: "兵長", vietnamese: "Binh trưởng, Trưởng binh" },
  { korean: "훈련소", hanja: "訓鍊所", vietnamese: "Trại huấn luyện" },
  { korean: "입대", hanja: "入隊", vietnamese: "Nhập ngũ" },
  { korean: "제대", hanja: "除隊", vietnamese: "Xuất ngũ" },
  { korean: "복무", hanja: "服務", vietnamese: "Phục vụ (quân đội)" },
  { korean: "의무복무", hanja: "義務服務", vietnamese: "Nghĩa vụ quân sự" },
  { korean: "징병", hanja: "徵兵", vietnamese: "Trưng binh" },
  { korean: "예비군", hanja: "豫備軍", vietnamese: "Dự bị quân" },
  { korean: "국방", hanja: "國防", vietnamese: "Quốc phòng" },
  { korean: "국방부", hanja: "國防部", vietnamese: "Bộ Quốc phòng" },
  { korean: "안보", hanja: "安保", vietnamese: "An bảo, An ninh quốc gia" },
  { korean: "무기", hanja: "武器", vietnamese: "Vũ khí" },
  { korean: "총", hanja: "銃", vietnamese: "Súng" },
  { korean: "대포", hanja: "大砲", vietnamese: "Đại bác" },
  { korean: "미사일", hanja: "", vietnamese: "Tên lửa" },
  { korean: "폭탄", hanja: "爆彈", vietnamese: "Bom" },
  { korean: "수류탄", hanja: "手榴彈", vietnamese: "Lựu đạn" },
  { korean: "핵무기", hanja: "核武器", vietnamese: "Vũ khí hạt nhân" },
  { korean: "원자폭탄", hanja: "原子爆彈", vietnamese: "Bom nguyên tử" },
  { korean: "탱크", hanja: "", vietnamese: "Xe tăng" },
  { korean: "전투기", hanja: "戰鬪機", vietnamese: "Máy bay chiến đấu" },
  { korean: "폭격기", hanja: "爆擊機", vietnamese: "Máy bay ném bom" },
  { korean: "군함", hanja: "軍艦", vietnamese: "Tàu chiến" },
  { korean: "잠수함", hanja: "潛水艦", vietnamese: "Tàu ngầm" },
  { korean: "항공모함", hanja: "航空母艦", vietnamese: "Tàu sân bay" },
  { korean: "전투", hanja: "戰鬪", vietnamese: "Chiến đấu" },
  { korean: "공격", hanja: "攻擊", vietnamese: "Công kích, Tấn công" },
  { korean: "방어", hanja: "防禦", vietnamese: "Phòng ngự" },
  { korean: "방위", hanja: "防衛", vietnamese: "Phòng vệ" },
  { korean: "작전", hanja: "作戰", vietnamese: "Tác chiến" },
  { korean: "전략", hanja: "戰略", vietnamese: "Chiến lược" },
  { korean: "전술", hanja: "戰術", vietnamese: "Chiến thuật" },
];

export const BATCH3_NATURE = [
  { korean: "자연", hanja: "自然", vietnamese: "Tự nhiên" },
  { korean: "생물", hanja: "生物", vietnamese: "Sinh vật" },
  { korean: "동물", hanja: "動物", vietnamese: "Động vật" },
  { korean: "식물", hanja: "植物", vietnamese: "Thực vật" },
  { korean: "미생물", hanja: "微生物", vietnamese: "Vi sinh vật" },
  { korean: "곤충", hanja: "昆蟲", vietnamese: "Côn trùng" },
  { korean: "포유류", hanja: "哺乳類", vietnamese: "Động vật có vú" },
  { korean: "조류", hanja: "鳥類", vietnamese: "Loài chim" },
  { korean: "어류", hanja: "魚類", vietnamese: "Loài cá" },
  { korean: "파충류", hanja: "爬蟲類", vietnamese: "Bò sát" },
  { korean: "양서류", hanja: "兩棲類", vietnamese: "Lưỡng cư" },
  { korean: "맹수", hanja: "猛獸", vietnamese: "Mãnh thú" },
  { korean: "가축", hanja: "家畜", vietnamese: "Gia súc" },
  { korean: "야생", hanja: "野生", vietnamese: "Hoang dã" },
  { korean: "멸종", hanja: "滅種", vietnamese: "Diệt chủng, Tuyệt chủng" },
  { korean: "보호", hanja: "保護", vietnamese: "Bảo hộ, Bảo vệ" },
  { korean: "생태", hanja: "生態", vietnamese: "Sinh thái" },
  { korean: "생태계", hanja: "生態系", vietnamese: "Hệ sinh thái" },
  { korean: "종", hanja: "種", vietnamese: "Chủng, Loài" },
  { korean: "종류", hanja: "種類", vietnamese: "Chủng loại" },
  { korean: "품종", hanja: "品種", vietnamese: "Phẩm chủng, Giống" },
  { korean: "수목", hanja: "樹木", vietnamese: "Thụ mộc, Cây cối" },
  { korean: "초목", hanja: "草木", vietnamese: "Cỏ cây" },
  { korean: "화초", hanja: "花草", vietnamese: "Hoa cỏ" },
  { korean: "과일", hanja: "", vietnamese: "Trái cây" },
  { korean: "과수", hanja: "果樹", vietnamese: "Quả thụ, Cây ăn quả" },
  { korean: "곡물", hanja: "穀物", vietnamese: "Cốc vật, Ngũ cốc" },
  { korean: "곡식", hanja: "穀食", vietnamese: "Cốc thực, Lương thực" },
  { korean: "채소", hanja: "菜蔬", vietnamese: "Thái sơ, Rau" },
  { korean: "야채", hanja: "野菜", vietnamese: "Dã thái, Rau" },
  { korean: "풍경", hanja: "風景", vietnamese: "Phong cảnh" },
  { korean: "경치", hanja: "景致", vietnamese: "Cảnh trí" },
  { korean: "경관", hanja: "景觀", vietnamese: "Cảnh quan" },
  { korean: "공기", hanja: "空氣", vietnamese: "Không khí" },
  { korean: "대기", hanja: "大氣", vietnamese: "Đại khí, Khí quyển" },
  { korean: "대기권", hanja: "大氣圈", vietnamese: "Tầng khí quyển" },
  { korean: "오존층", hanja: "", vietnamese: "Tầng ozone" },
  { korean: "온실", hanja: "溫室", vietnamese: "Ôn thất, Nhà kính" },
  { korean: "지구온난화", hanja: "地球溫暖化", vietnamese: "Biến đổi khí hậu, Nóng lên toàn cầu" },
  { korean: "황사", hanja: "黃沙", vietnamese: "Hoàng sa, Bụi vàng" },
  { korean: "미세먼지", hanja: "微細", vietnamese: "Bụi mịn" },
  { korean: "에너지원", hanja: "", vietnamese: "Nguồn năng lượng" },
  { korean: "석유", hanja: "石油", vietnamese: "Dầu mỏ" },
  { korean: "석탄", hanja: "石炭", vietnamese: "Than đá" },
  { korean: "천연가스", hanja: "天然", vietnamese: "Khí thiên nhiên" },
  { korean: "태양광", hanja: "太陽光", vietnamese: "Ánh sáng mặt trời" },
  { korean: "풍력", hanja: "風力", vietnamese: "Phong lực, Sức gió" },
  { korean: "수력", hanja: "水力", vietnamese: "Thủy lực" },
  { korean: "원자력", hanja: "原子力", vietnamese: "Nguyên tử lực, Năng lượng hạt nhân" },
  { korean: "재생에너지", hanja: "再生", vietnamese: "Năng lượng tái tạo" },
  { korean: "자원", hanja: "資源", vietnamese: "Tài nguyên" },
  { korean: "천연자원", hanja: "天然資源", vietnamese: "Tài nguyên thiên nhiên" },
  { korean: "보존", hanja: "保存", vietnamese: "Bảo tồn" },
];

export const BATCH3_EMOTIONS = [
  { korean: "감동", hanja: "感動", vietnamese: "Cảm động" },
  { korean: "감격", hanja: "感激", vietnamese: "Cảm kích" },
  { korean: "감사", hanja: "感謝", vietnamese: "Cảm tạ, Biết ơn" },
  { korean: "환희", hanja: "歡喜", vietnamese: "Hoan hỉ, Vui mừng" },
  { korean: "희열", hanja: "喜悅", vietnamese: "Hỉ duyệt, Vui sướng" },
  { korean: "행복", hanja: "幸福", vietnamese: "Hạnh phúc" },
  { korean: "불행", hanja: "不幸", vietnamese: "Bất hạnh" },
  { korean: "쾌락", hanja: "快樂", vietnamese: "Khoái lạc" },
  { korean: "고통", hanja: "苦痛", vietnamese: "Khổ thống, Đau khổ" },
  { korean: "고뇌", hanja: "苦惱", vietnamese: "Khổ não, Buồn rầu" },
  { korean: "번뇌", hanja: "煩惱", vietnamese: "Phiền não" },
  { korean: "우울", hanja: "憂鬱", vietnamese: "Ưu uất, U uất" },
  { korean: "슬픔", hanja: "", vietnamese: "Nỗi buồn" },
  { korean: "비통", hanja: "悲痛", vietnamese: "Bi thống" },
  { korean: "비애", hanja: "悲哀", vietnamese: "Bi ai" },
  { korean: "분노", hanja: "憤怒", vietnamese: "Phẫn nộ" },
  { korean: "격분", hanja: "激憤", vietnamese: "Kích phẫn" },
  { korean: "증오", hanja: "憎惡", vietnamese: "Tăng ác, Căm ghét" },
  { korean: "원한", hanja: "怨恨", vietnamese: "Oán hận" },
  { korean: "질투", hanja: "嫉妬", vietnamese: "Tật đố, Ghen tỵ" },
  { korean: "시기", hanja: "猜忌", vietnamese: "Sai kỵ, Ganh ghét" },
  { korean: "공포", hanja: "恐怖", vietnamese: "Khủng bố, Sợ hãi" },
  { korean: "두려움", hanja: "", vietnamese: "Nỗi sợ" },
  { korean: "불안", hanja: "不安", vietnamese: "Bất an" },
  { korean: "걱정", hanja: "", vietnamese: "Lo lắng" },
  { korean: "근심", hanja: "", vietnamese: "Lo âu" },
  { korean: "우려", hanja: "憂慮", vietnamese: "Ưu lự, Lo ngại" },
  { korean: "긴장", hanja: "緊張", vietnamese: "Khẩn trương, Căng thẳng" },
  { korean: "안심", hanja: "安心", vietnamese: "An tâm, Yên lòng" },
  { korean: "안정", hanja: "安定", vietnamese: "An định, Ổn định" },
  { korean: "흥분", hanja: "興奮", vietnamese: "Hưng phấn" },
  { korean: "열정", hanja: "熱情", vietnamese: "Nhiệt tình" },
  { korean: "애정", hanja: "愛情", vietnamese: "Ái tình, Tình yêu" },
  { korean: "연애", hanja: "戀愛", vietnamese: "Luyến ái, Yêu đương" },
  { korean: "사랑", hanja: "", vietnamese: "Tình yêu" },
  { korean: "우정", hanja: "友情", vietnamese: "Hữu tình, Tình bạn" },
  { korean: "정", hanja: "情", vietnamese: "Tình, Tình cảm" },
  { korean: "인정", hanja: "人情", vietnamese: "Nhân tình, Tình người" },
  { korean: "동정", hanja: "同情", vietnamese: "Đồng tình, Thương cảm" },
  { korean: "연민", hanja: "憐憫", vietnamese: "Liên mẫn, Thương hại" },
  { korean: "자비", hanja: "慈悲", vietnamese: "Từ bi" },
  { korean: "관용", hanja: "寬容", vietnamese: "Khoan dung" },
  { korean: "인내", hanja: "忍耐", vietnamese: "Nhẫn nại" },
  { korean: "인내심", hanja: "忍耐心", vietnamese: "Lòng nhẫn nại" },
  { korean: "참을성", hanja: "", vietnamese: "Tính kiên nhẫn" },
  { korean: "용기", hanja: "勇氣", vietnamese: "Dũng khí, Can đảm" },
  { korean: "용감", hanja: "勇敢", vietnamese: "Dũng cảm" },
  { korean: "대담", hanja: "大膽", vietnamese: "Đại đảm, Táo bạo" },
  { korean: "비겁", hanja: "卑怯", vietnamese: "Ti khiếp, Hèn nhát" },
  { korean: "겸손", hanja: "謙遜", vietnamese: "Khiêm tốn" },
  { korean: "자만", hanja: "自慢", vietnamese: "Tự mạn, Tự cao" },
  { korean: "오만", hanja: "傲慢", vietnamese: "Ngạo mạn" },
  { korean: "교만", hanja: "驕慢", vietnamese: "Kiêu mạn" },
  { korean: "성실", hanja: "誠實", vietnamese: "Thành thực" },
  { korean: "정직", hanja: "正直", vietnamese: "Chính trực, Thẳng thắn" },
  { korean: "거짓말", hanja: "", vietnamese: "Lời nói dối" },
  { korean: "허풍", hanja: "虛風", vietnamese: "Hư phong, Khoác lác" },
  { korean: "진심", hanja: "眞心", vietnamese: "Chân tâm" },
  { korean: "성의", hanja: "誠意", vietnamese: "Thành ý" },
  { korean: "호의", hanja: "好意", vietnamese: "Hảo ý, Thiện chí" },
  { korean: "악의", hanja: "惡意", vietnamese: "Ác ý" },
  { korean: "만족", hanja: "滿足", vietnamese: "Mãn túc, Hài lòng" },
  { korean: "불만", hanja: "不滿", vietnamese: "Bất mãn" },
  { korean: "후회", hanja: "後悔", vietnamese: "Hậu hối, Hối hận" },
  { korean: "유감", hanja: "遺憾", vietnamese: "Di hám, Đáng tiếc" },
  { korean: "실망", hanja: "失望", vietnamese: "Thất vọng" },
  { korean: "낙심", hanja: "落心", vietnamese: "Lạc tâm, Nản lòng" },
  { korean: "절망", hanja: "絶望", vietnamese: "Tuyệt vọng" },
  { korean: "희망", hanja: "希望", vietnamese: "Hy vọng" },
  { korean: "기대", hanja: "期待", vietnamese: "Kỳ đãi, Mong đợi" },
  { korean: "소망", hanja: "所望", vietnamese: "Sở vọng, Ước muốn" },
  { korean: "욕망", hanja: "慾望", vietnamese: "Dục vọng" },
  { korean: "야망", hanja: "野望", vietnamese: "Dã vọng, Tham vọng" },
];

export const BATCH3_FOOD = [
  { korean: "음식", hanja: "飮食", vietnamese: "Ẩm thực, Thức ăn" },
  { korean: "요리", hanja: "料理", vietnamese: "Liệu lý, Món ăn" },
  { korean: "요리사", hanja: "料理師", vietnamese: "Đầu bếp" },
  { korean: "조리", hanja: "調理", vietnamese: "Điều lý, Nấu ăn" },
  { korean: "식재료", hanja: "食材料", vietnamese: "Nguyên liệu nấu ăn" },
  { korean: "재료", hanja: "材料", vietnamese: "Tài liệu, Nguyên liệu" },
  { korean: "조미료", hanja: "調味料", vietnamese: "Điều vị liệu, Gia vị" },
  { korean: "양념", hanja: "", vietnamese: "Gia vị" },
  { korean: "한식", hanja: "韓食", vietnamese: "Hàn thực, Món Hàn" },
  { korean: "양식", hanja: "洋食", vietnamese: "Dương thực, Món Tây" },
  { korean: "일식", hanja: "日食", vietnamese: "Nhật thực, Món Nhật" },
  { korean: "중식", hanja: "中食", vietnamese: "Trung thực, Món Trung" },
  { korean: "분식", hanja: "粉食", vietnamese: "Phấn thực, Món bột" },
  { korean: "식품", hanja: "食品", vietnamese: "Thực phẩm" },
  { korean: "식료품", hanja: "食料品", vietnamese: "Thực liệu phẩm, Tạp phẩm" },
  { korean: "가공식품", hanja: "加工食品", vietnamese: "Thực phẩm chế biến" },
  { korean: "냉동식품", hanja: "冷凍食品", vietnamese: "Thực phẩm đông lạnh" },
  { korean: "인스턴트", hanja: "", vietnamese: "Ăn liền" },
  { korean: "간편식", hanja: "簡便食", vietnamese: "Giản tiện thực, Ăn nhanh" },
  { korean: "채식", hanja: "菜食", vietnamese: "Thái thực, Ăn chay" },
  { korean: "육식", hanja: "肉食", vietnamese: "Nhục thực, Ăn thịt" },
  { korean: "육류", hanja: "肉類", vietnamese: "Nhục loại, Thịt" },
  { korean: "어류", hanja: "漁類", vietnamese: "Loại cá" },
  { korean: "해산물", hanja: "海産物", vietnamese: "Hải sản" },
  { korean: "유제품", hanja: "乳製品", vietnamese: "Sản phẩm từ sữa" },
  { korean: "과자", hanja: "菓子", vietnamese: "Quả tử, Bánh kẹo" },
  { korean: "빵", hanja: "", vietnamese: "Bánh mì" },
  { korean: "떡", hanja: "", vietnamese: "Bánh gạo" },
  { korean: "국물", hanja: "", vietnamese: "Nước canh" },
  { korean: "국수", hanja: "", vietnamese: "Mì" },
  { korean: "밥", hanja: "", vietnamese: "Cơm" },
  { korean: "반찬", hanja: "飯饌", vietnamese: "Phạn soạn, Món ăn kèm" },
  { korean: "영양", hanja: "營養", vietnamese: "Doanh dưỡng, Dinh dưỡng" },
  { korean: "영양소", hanja: "營養素", vietnamese: "Dưỡng chất" },
  { korean: "칼로리", hanja: "", vietnamese: "Calo" },
  { korean: "단백질", hanja: "蛋白質", vietnamese: "Đản bạch chất, Protein" },
  { korean: "지방", hanja: "脂肪", vietnamese: "Chi phòng, Chất béo" },
  { korean: "탄수화물", hanja: "炭水化物", vietnamese: "Than thủy hóa vật, Carb" },
  { korean: "비타민", hanja: "", vietnamese: "Vitamin" },
  { korean: "미네랄", hanja: "", vietnamese: "Khoáng chất" },
  { korean: "섬유질", hanja: "纖維質", vietnamese: "Chất xơ" },
  { korean: "포만", hanja: "飽滿", vietnamese: "Bão mãn, No" },
  { korean: "공복", hanja: "空腹", vietnamese: "Không phúc, Đói bụng" },
  { korean: "식욕", hanja: "食慾", vietnamese: "Thực dục, Cảm giác thèm ăn" },
  { korean: "식단", hanja: "食單", vietnamese: "Thực đơn" },
  { korean: "메뉴", hanja: "", vietnamese: "Thực đơn" },
  { korean: "예약", hanja: "豫約", vietnamese: "Dự ước, Đặt trước" },
  { korean: "주문", hanja: "注文", vietnamese: "Chú văn, Đặt món" },
  { korean: "배달", hanja: "配達", vietnamese: "Phối đạt, Giao hàng" },
  { korean: "포장", hanja: "包裝", vietnamese: "Bao trang, Đóng gói, Mang về" },
];

export const BATCH3_ABSTRACT = [
  { korean: "가능", hanja: "可能", vietnamese: "Khả năng" },
  { korean: "가능성", hanja: "可能性", vietnamese: "Khả năng tính" },
  { korean: "불가능", hanja: "不可能", vietnamese: "Bất khả năng" },
  { korean: "필요", hanja: "必要", vietnamese: "Tất yếu, Cần thiết" },
  { korean: "필수", hanja: "必須", vietnamese: "Tất tu, Bắt buộc" },
  { korean: "중요", hanja: "重要", vietnamese: "Trọng yếu, Quan trọng" },
  { korean: "긴요", hanja: "緊要", vietnamese: "Khẩn yếu, Cấp thiết" },
  { korean: "긴급", hanja: "緊急", vietnamese: "Khẩn cấp" },
  { korean: "시급", hanja: "時急", vietnamese: "Thời cấp, Gấp gáp" },
  { korean: "위급", hanja: "危急", vietnamese: "Nguy cấp" },
  { korean: "위기", hanja: "危機", vietnamese: "Nguy cơ" },
  { korean: "위험", hanja: "危險", vietnamese: "Nguy hiểm" },
  { korean: "안전", hanja: "安全", vietnamese: "An toàn" },
  { korean: "신뢰", hanja: "信賴", vietnamese: "Tín lại, Tin tưởng" },
  { korean: "신용", hanja: "信用", vietnamese: "Tín dụng" },
  { korean: "신의", hanja: "信義", vietnamese: "Tín nghĩa" },
  { korean: "의리", hanja: "義理", vietnamese: "Nghĩa lý" },
  { korean: "의지", hanja: "意志", vietnamese: "Ý chí" },
  { korean: "의도", hanja: "意圖", vietnamese: "Ý đồ" },
  { korean: "목적", hanja: "目的", vietnamese: "Mục đích" },
  { korean: "목표", hanja: "目標", vietnamese: "Mục tiêu" },
  { korean: "목적지", hanja: "目的地", vietnamese: "Điểm đến" },
  { korean: "방향", hanja: "方向", vietnamese: "Phương hướng" },
  { korean: "방식", hanja: "方式", vietnamese: "Phương thức" },
  { korean: "방안", hanja: "方案", vietnamese: "Phương án" },
  { korean: "대안", hanja: "代案", vietnamese: "Phương án thay thế" },
  { korean: "해결", hanja: "解決", vietnamese: "Giải quyết" },
  { korean: "해답", hanja: "解答", vietnamese: "Giải đáp" },
  { korean: "답안", hanja: "答案", vietnamese: "Đáp án" },
  { korean: "문제", hanja: "問題", vietnamese: "Vấn đề" },
  { korean: "질문", hanja: "質問", vietnamese: "Chất vấn, Câu hỏi" },
  { korean: "의문", hanja: "疑問", vietnamese: "Nghi vấn" },
  { korean: "의심", hanja: "疑心", vietnamese: "Nghi tâm, Nghi ngờ" },
  { korean: "확신", hanja: "確信", vietnamese: "Xác tín, Chắc chắn" },
  { korean: "확정", hanja: "確定", vietnamese: "Xác định" },
  { korean: "결정", hanja: "決定", vietnamese: "Quyết định" },
  { korean: "판단", hanja: "判斷", vietnamese: "Phán đoán" },
  { korean: "결론", hanja: "結論", vietnamese: "Kết luận" },
  { korean: "결과", hanja: "結果", vietnamese: "Kết quả" },
  { korean: "원인", hanja: "原因", vietnamese: "Nguyên nhân" },
  { korean: "이유", hanja: "理由", vietnamese: "Lý do" },
  { korean: "근거", hanja: "根據", vietnamese: "Căn cứ" },
  { korean: "기준", hanja: "基準", vietnamese: "Cơ chuẩn, Tiêu chuẩn" },
  { korean: "표준", hanja: "標準", vietnamese: "Tiêu chuẩn" },
  { korean: "규칙", hanja: "規則", vietnamese: "Quy tắc" },
  { korean: "규정", hanja: "規定", vietnamese: "Quy định" },
  { korean: "원칙", hanja: "原則", vietnamese: "Nguyên tắc" },
  { korean: "질서", hanja: "秩序", vietnamese: "Trật tự" },
  { korean: "혼란", hanja: "混亂", vietnamese: "Hỗn loạn" },
  { korean: "혼돈", hanja: "混沌", vietnamese: "Hỗn độn" },
  { korean: "균형", hanja: "均衡", vietnamese: "Quân hành, Cân bằng" },
  { korean: "조화", hanja: "調和", vietnamese: "Điều hòa, Hài hòa" },
  { korean: "불균형", hanja: "不均衡", vietnamese: "Bất quân hành" },
  { korean: "변화", hanja: "變化", vietnamese: "Biến hóa, Thay đổi" },
  { korean: "변동", hanja: "變動", vietnamese: "Biến động" },
  { korean: "변혁", hanja: "變革", vietnamese: "Biến cách" },
  { korean: "변천", hanja: "變遷", vietnamese: "Biến thiên" },
  { korean: "발전", hanja: "發展", vietnamese: "Phát triển" },
  { korean: "발달", hanja: "發達", vietnamese: "Phát đạt" },
  { korean: "진화", hanja: "進化", vietnamese: "Tiến hóa" },
  { korean: "퇴화", hanja: "退化", vietnamese: "Thoái hóa" },
  { korean: "쇠퇴", hanja: "衰退", vietnamese: "Suy thoái" },
  { korean: "번영", hanja: "繁榮", vietnamese: "Phồn vinh" },
  { korean: "영향", hanja: "影響", vietnamese: "Ảnh hưởng" },
  { korean: "영향력", hanja: "影響力", vietnamese: "Sức ảnh hưởng" },
  { korean: "효과", hanja: "效果", vietnamese: "Hiệu quả" },
  { korean: "효율", hanja: "效率", vietnamese: "Hiệu suất" },
  { korean: "효용", hanja: "效用", vietnamese: "Hiệu dụng, Công dụng" },
  { korean: "장점", hanja: "長點", vietnamese: "Ưu điểm" },
  { korean: "단점", hanja: "短點", vietnamese: "Khuyết điểm" },
  { korean: "약점", hanja: "弱點", vietnamese: "Nhược điểm" },
  { korean: "강점", hanja: "强點", vietnamese: "Điểm mạnh" },
  { korean: "특징", hanja: "特徵", vietnamese: "Đặc trưng" },
  { korean: "특성", hanja: "特性", vietnamese: "Đặc tính" },
  { korean: "성질", hanja: "性質", vietnamese: "Tính chất" },
  { korean: "속성", hanja: "屬性", vietnamese: "Thuộc tính" },
  { korean: "내용", hanja: "內容", vietnamese: "Nội dung" },
  { korean: "형식", hanja: "形式", vietnamese: "Hình thức" },
  { korean: "형태", hanja: "形態", vietnamese: "Hình thái" },
  { korean: "모양", hanja: "模樣", vietnamese: "Mô dạng, Hình dáng" },
  { korean: "구조", hanja: "構造", vietnamese: "Cấu tạo" },
  { korean: "체계", hanja: "體系", vietnamese: "Thể hệ, Hệ thống" },
  { korean: "범위", hanja: "範圍", vietnamese: "Phạm vi" },
  { korean: "한계", hanja: "限界", vietnamese: "Hạn giới, Giới hạn" },
  { korean: "극한", hanja: "極限", vietnamese: "Cực hạn" },
];

export const ALL_BATCH3 = [
  ...BATCH3_MILITARY,
  ...BATCH3_NATURE,
  ...BATCH3_EMOTIONS,
  ...BATCH3_FOOD,
  ...BATCH3_ABSTRACT,
];

console.log("Total batch 3:", ALL_BATCH3.length);
