-- ─── Hanja Pro: Phần 23 (21 từ) ─────────────────────────────────────────────
-- Xóa entry mẫu 가결 (id=2) được tạo trong migration 096
DELETE FROM public.hanja_pro WHERE slug = 'ga-gyeol';

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(200,'노동력','勞動力','no-dong-ryeok','Sức lao động, nhân lực',
'[{"char":"勞","reading":"노","meaning":"lao động"},{"char":"動","reading":"동","meaning":"hoạt động"},{"char":"力","reading":"력","meaning":"sức mạnh"}]',
'[{"ko":"이 공장은 많은 노동력이 필요합니다.","boi":"i gong-jang-eun ma-neun no-dong-ryeok-i pil-yo-hap-ni-da","vi":"Nhà máy này cần rất nhiều sức lao động."},{"ko":"기술 발전이 단순 노동력을 대체하고 있습니다.","boi":"gi-sul bal-jeon-i dan-sun no-dong-ryeok-eul dae-che-ha-go it-seup-ni-da","vi":"Sự phát triển công nghệ đang thay thế sức lao động giản đơn."},{"ko":"노동력 부족 문제를 해결하기 위해 외국인 채용을 늘립니다.","boi":"no-dong-ryeok bu-jok mun-je-reul hae-gyeol-ha-gi wi-hae oe-guk-in chae-yong-eul neul-lip-ni-da","vi":"Để giải quyết thiếu nhân lực, họ tăng tuyển dụng lao động nước ngoài."},{"ko":"우수한 노동력을 유지하기 위해 복지를 개선했습니다.","boi":"u-su-han no-dong-ryeok-eul yu-ji-ha-gi wi-hae bok-ji-reul gae-seon-haet-seup-ni-da","vi":"Cải thiện phúc lợi để duy trì nguồn nhân lực chất lượng."},{"ko":"국가 발전에는 건강한 노동력이 필요합니다.","boi":"guk-ga bal-jeon-e-neun geon-gang-han no-dong-ryeok-i pil-yo-hap-ni-da","vi":"Phát triển quốc gia cần nguồn nhân lực khỏe mạnh."}]',
'[{"word":"노동자","hanja":"勞動者","meaning":"Người lao động (勞動+者)"},{"word":"생산력","hanja":"生産力","meaning":"Sức sản xuất (生産+力)"},{"word":"인력","hanja":"人力","meaning":"Nhân lực (人+力)"}]',
'勞(lao)+動(động)+力(lực) = sức để lao động. Hán Việt: Lao Động Lực.','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(201,'노선','路線','no-seon','Đường lối, lộ tuyến, tuyến đường',
'[{"char":"路","reading":"노","meaning":"con đường, lộ"},{"char":"線","reading":"선","meaning":"đường kẻ, tuyến"}]',
'[{"ko":"이 버스 노선은 시내 중심가를 순환합니다.","boi":"i beo-seu no-seon-eun si-nae jung-sim-ga-reul sun-hwan-hap-ni-da","vi":"Tuyến xe buýt này chạy vòng quanh trung tâm thành phố."},{"ko":"우리 회사의 기본 노선은 고객 중심 경영입니다.","boi":"u-ri hoe-sa-ui gi-bon no-seon-eun go-gaek jung-sim gyeong-yeong-ip-ni-da","vi":"Đường lối cơ bản của công ty là quản trị lấy khách hàng làm trung tâm."},{"ko":"정부의 새로운 경제 노선이 발표되었습니다.","boi":"jeong-bu-ui sae-ro-un gyeong-je no-seon-i bal-pyo-doe-eot-seup-ni-da","vi":"Đường lối kinh tế mới của chính phủ đã được công bố."},{"ko":"지하철 2호선 노선도를 보여주세요.","boi":"ji-ha-cheol i-ho-seon no-seon-do-reul bo-yeo-ju-se-yo","vi":"Hãy cho tôi xem bản đồ tuyến tàu điện ngầm số 2."},{"ko":"그는 자신의 정치적 노선을 확고히 지켰다.","boi":"geu-neun ja-sin-ui jeong-chi-jeok no-seon-eul hwak-go-hi ji-kyeot-da","vi":"Ông ấy kiên định giữ vững đường lối chính trị của mình."}]',
'[{"word":"노정","hanja":"路程","meaning":"Hành trình, quãng đường"},{"word":"방향","hanja":"方向","meaning":"Phương hướng, hướng đi"},{"word":"방침","hanja":"方針","meaning":"Phương châm, chủ trương"}]',
'路(lộ - con đường) + 線(tuyến - đường kẻ) = Lộ Tuyến. Đường có vạch kẻ rõ ràng dẫn bạn đi.','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(202,'노출','露出','no-chul','Sự phơi bày, lộ ra, phô ra',
'[{"char":"露","reading":"노","meaning":"để lộ, sương lộ"},{"char":"出","reading":"출","meaning":"ra ngoài, xuất hiện"}]',
'[{"ko":"태양에 장시간 피부를 노출하면 위험합니다.","boi":"tae-yang-e jang-si-gan pi-bu-reul no-chul-ha-myeon wi-heom-hap-ni-da","vi":"Để da phơi dưới ánh mặt trời quá lâu rất nguy hiểm."},{"ko":"그 문서는 기밀 정보를 노출시켰다.","boi":"geu mun-seo-neun gi-mil jeong-bo-reul no-chul-si-kyeot-da","vi":"Tài liệu đó đã để lộ thông tin mật."},{"ko":"방송 사고로 연예인의 사생활이 노출됐다.","boi":"bang-song sa-go-ro yeon-ye-in-ui sa-saeng-hwal-i no-chul-dwaet-da","vi":"Đời tư người nổi tiếng bị lộ do sự cố phát sóng."},{"ko":"건물 외벽 철근이 노출되어 위험하다.","boi":"geon-mul oe-byeok cheol-geun-i no-chul-doe-eo wi-heom-ha-da","vi":"Cốt thép tường ngoài tòa nhà bị lộ ra, rất nguy hiểm."},{"ko":"광고에 과도한 신체 노출은 자제해야 한다.","boi":"gwang-go-e gwa-do-han sin-che no-chul-eun ja-je-hae-ya han-da","vi":"Cần hạn chế phô bày cơ thể quá mức trong quảng cáo."}]',
'[{"word":"폭로","hanja":"暴露","meaning":"Vạch trần, phơi bày bí mật"},{"word":"발각","hanja":"發覺","meaning":"Bị phát hiện, bị lộ"},{"word":"은폐","hanja":"隱蔽","meaning":"Che giấu, che đậy (trái nghĩa)"}]',
'露(lộ - để lộ) + 出(xuất - ra ngoài) = Lộ Xuất = phơi bày ra ngoài. Khi bí mật "lộ" thì nó "xuất" hiện trước mọi người.','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(203,'노후','老後','no-hu','Tuổi già, giai đoạn về già',
'[{"char":"老","reading":"노","meaning":"già, lão"},{"char":"後","reading":"후","meaning":"sau, phía sau, hậu"}]',
'[{"ko":"노후를 대비해서 꾸준히 저축해야 합니다.","boi":"no-hu-reul dae-bi-hae-seo kku-jun-hi jeo-chuk-hae-ya hap-ni-da","vi":"Phải tiết kiệm đều đặn để chuẩn bị cho tuổi già."},{"ko":"건강한 노후 생활이 중요해요.","boi":"geon-gang-han no-hu saeng-hwal-i jung-yo-hae-yo","vi":"Một cuộc sống tuổi già khỏe mạnh rất quan trọng."},{"ko":"그 부부는 노후 계획을 세우고 있습니다.","boi":"geu bu-bu-neun no-hu gye-hoek-eul se-u-go it-seup-ni-da","vi":"Cặp vợ chồng đó đang lập kế hoạch cho tuổi già."},{"ko":"노후에 취미 생활을 시작할 거예요.","boi":"no-hu-e chwi-mi saeng-hwal-eul si-jak-hal geo-ye-yo","vi":"Tôi sẽ bắt đầu sở thích khi về già."},{"ko":"사회적 노후 보장 제도가 필요합니다.","boi":"sa-hoe-jeok no-hu bo-jang je-do-ga pil-yo-hap-ni-da","vi":"Cần có chế độ an sinh xã hội cho tuổi già."}]',
'[{"word":"노년","hanja":"老年","meaning":"Tuổi già (老+年)"},{"word":"은퇴","hanja":"隱退","meaning":"Nghỉ hưu (隱+退)"},{"word":"장수","hanja":"長壽","meaning":"Sống lâu, trường thọ"}]',
'老(lão - già) đứng ở phía 後(hậu - sau) cuộc đời = Lão Hậu = tuổi già. Giai đoạn phía sau khi đã qua tuổi trẻ.','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(204,'논거','論據','non-geo','Luận cứ, căn cứ lập luận',
'[{"char":"論","reading":"논","meaning":"bàn luận, lập luận"},{"char":"據","reading":"거","meaning":"dựa vào, căn cứ"}]',
'[{"ko":"그 주장에는 충분한 논거가 필요합니다.","boi":"geu ju-jang-e-neun chung-bun-han non-geo-ga pil-yo-hap-ni-da","vi":"Lập luận đó cần có căn cứ đầy đủ."},{"ko":"논거 없이 주장하면 설득력이 없다.","boi":"non-geo eop-si ju-jang-ha-myeon seol-deuk-ryeok-i eop-da","vi":"Lập luận mà không có căn cứ thì không có sức thuyết phục."},{"ko":"명확한 논거를 제시해야 토론에서 이길 수 있다.","boi":"myeong-hwak-han non-geo-reul je-si-hae-ya to-ron-e-seo i-gil su it-da","vi":"Phải đưa ra căn cứ rõ ràng mới thắng trong tranh luận."},{"ko":"그녀의 논문은 탄탄한 논거로 구성되어 있다.","boi":"geu-nyeo-ui non-mun-eun tan-tan-han non-geo-ro gu-seong-doe-eo it-da","vi":"Luận văn của cô ấy được xây dựng trên những luận cứ vững chắc."},{"ko":"반론에 대한 논거를 충분히 준비해야 한다.","boi":"ban-lon-e dae-han non-geo-reul chung-bun-hi jun-bi-hae-ya han-da","vi":"Phải chuẩn bị đầy đủ luận cứ để phản bác."}]',
'[{"word":"논리","hanja":"論理","meaning":"Logic, lý luận"},{"word":"근거","hanja":"根據","meaning":"Căn cứ, cơ sở"},{"word":"주장","hanja":"主張","meaning":"Chủ trương, lập luận"}]',
'論(luận - lập luận) + 據(cứ - căn cứ) = Luận Cứ. Khi tranh luận cần có 논거, không có căn cứ thì thua!','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(205,'논평','論評','non-pyeong','Bình luận, nhận xét, phê bình',
'[{"char":"論","reading":"논","meaning":"bàn luận, thảo luận"},{"char":"評","reading":"평","meaning":"đánh giá, bình phẩm"}]',
'[{"ko":"전문가들이 선거 결과에 대해 논평했습니다.","boi":"jeon-mun-ga-deul-i seon-geo gyeol-gwa-e dae-hae non-pyeong-haet-seup-ni-da","vi":"Các chuyên gia đã bình luận về kết quả bầu cử."},{"ko":"정부는 이 사안에 대해 공식 논평을 발표했다.","boi":"jeong-bu-neun i sa-an-e dae-hae gong-sik non-pyeong-eul bal-pyo-haet-da","vi":"Chính phủ đưa ra bình luận chính thức về vấn đề này."},{"ko":"그 영화에 대한 비평가들의 논평이 엇갈렸다.","boi":"geu yeong-hwa-e dae-han bi-pyeong-ga-deul-ui non-pyeong-i eot-gal-lyeot-da","vi":"Bình luận của các nhà phê bình về bộ phim trái chiều nhau."},{"ko":"그는 시사 논평 프로그램의 진행자입니다.","boi":"geu-neun si-sa non-pyeong peu-ro-geu-raem-ui jin-haeng-ja-ip-ni-da","vi":"Anh ấy là người dẫn chương trình bình luận thời sự."},{"ko":"아무 논평도 하지 않겠다고 했습니다.","boi":"a-mu non-pyeong-do ha-ji an-get-da-go haet-seup-ni-da","vi":"Họ nói sẽ không đưa ra bất kỳ bình luận nào."}]',
'[{"word":"비평","hanja":"批評","meaning":"Phê bình (批+評)"},{"word":"평가","hanja":"評價","meaning":"Đánh giá (評+價)"},{"word":"논의","hanja":"論議","meaning":"Thảo luận (論+議)"}]',
'論(luận - bàn luận) + 評(bình - đánh giá) = Luận Bình = bình luận. Phân tích và đánh giá sự kiện.','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(206,'농담','弄談','nong-dam','Lời nói đùa, trò đùa',
'[{"char":"弄","reading":"농","meaning":"đùa giỡn, chơi đùa"},{"char":"談","reading":"담","meaning":"nói chuyện, đàm"}]',
'[{"ko":"그건 농담이에요, 진지하게 받아들이지 마세요.","boi":"geu-geon nong-dam-i-e-yo, jin-ji-ha-ge bat-a-deul-i-ji ma-se-yo","vi":"Đó chỉ là câu đùa thôi, đừng tiếp nhận một cách nghiêm túc."},{"ko":"그의 농담에 모두가 웃음을 터뜨렸다.","boi":"geu-ui nong-dam-e mo-du-ga u-seum-eul teo-ddeu-ryeot-da","vi":"Mọi người đều phá ra cười vì câu đùa của anh ấy."},{"ko":"농담도 정도가 있어야 한다.","boi":"nong-dam-do jeong-do-ga it-eo-ya han-da","vi":"Đùa cũng phải có chừng mực."},{"ko":"반농담으로 한 말인데 진담처럼 들렸나 봐요.","boi":"ban-nong-dam-eu-ro han mal-in-de jin-dam-cheo-reom deul-lyeot-na bwa-yo","vi":"Tôi nói nửa đùa nửa thật mà nghe có vẻ nghiêm túc."},{"ko":"농담이 아니라 진심이에요.","boi":"nong-dam-i a-ni-ra jin-sim-i-e-yo","vi":"Đây không phải là đùa, đây là thật lòng."}]',
'[{"word":"진담","hanja":"眞談","meaning":"Lời nói thật (眞+談, trái nghĩa)"},{"word":"유머","hanja":"humor","meaning":"Hài hước, khôi hài"},{"word":"농치다","hanja":"弄-","meaning":"Đùa nghịch, đùa cợt"}]',
'弄(nông - đùa giỡn) + 談(đàm - nói chuyện) = Nông Đàm = nói chuyện đùa = lời nói đùa. Trái nghĩa: 진담 (lời thật).','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(207,'농성','籠城','nong-seong','Biểu tình ngồi, đình công cố thủ',
'[{"char":"籠","reading":"농","meaning":"lồng, cố thủ, giam cầm"},{"char":"城","reading":"성","meaning":"thành, thành trì"}]',
'[{"ko":"노동자들이 공장 앞에서 농성을 벌이고 있습니다.","boi":"no-dong-ja-deul-i gong-jang ap-e-seo nong-seong-eul beol-i-go it-seup-ni-da","vi":"Những người lao động đang tổ chức đình công ngồi trước nhà máy."},{"ko":"학생들이 학교 당국에 항의하며 농성에 들어갔다.","boi":"hak-saeng-deul-i hak-gyo dang-guk-e hang-ui-ha-myeo nong-seong-e deul-eo-gat-da","vi":"Học sinh vào đình công ngồi để phản đối nhà trường."},{"ko":"국회의사당 앞에서 시민단체가 철야 농성을 했다.","boi":"guk-hoe-ui-sa-dang ap-e-seo si-min-dan-che-ga cheol-ya nong-seong-eul haet-da","vi":"Tổ chức dân sự thức đêm ngồi biểu tình trước Quốc hội."},{"ko":"농성 사태가 열흘째 이어지고 있다.","boi":"nong-seong sa-tae-ga yeol-heul-jjae i-eo-ji-go it-da","vi":"Tình trạng đình công ngồi kéo dài sang ngày thứ mười."},{"ko":"협상이 타결되면서 농성이 끝났다.","boi":"hyeop-sang-i ta-gyeol-doe-myeo-seo nong-seong-i kkeut-nat-da","vi":"Cuộc đình công ngồi kết thúc khi đàm phán đạt thỏa thuận."}]',
'[{"word":"파업","hanja":"罷業","meaning":"Đình công, ngừng việc"},{"word":"시위","hanja":"示威","meaning":"Biểu tình"},{"word":"항의","hanja":"抗議","meaning":"Phản đối, kháng nghị"}]',
'籠(lung - lồng, cố thủ) + 城(thành - thành trì) = cố thủ trong thành như bị nhốt trong lồng = biểu tình ngồi không chịu rời.','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(208,'누적','累積','nu-jeok','Sự tích lũy, dồn tích, cộng dồn',
'[{"char":"累","reading":"누","meaning":"chồng chất, tích lũy, lũy"},{"char":"積","reading":"적","meaning":"tích lũy, chồng chất"}]',
'[{"ko":"스트레스가 누적되면 건강에 악영향을 미칩니다.","boi":"seu-teu-re-seu-ga nu-jeok-doe-myeon geon-gang-e ak-yeong-hyang-eul mi-chip-ni-da","vi":"Nếu stress tích tụ lại sẽ ảnh hưởng xấu đến sức khỏe."},{"ko":"빚이 누적되어 결국 파산하고 말았다.","boi":"bit-i nu-jeok-doe-eo gyeol-guk pa-san-ha-go ma-rat-da","vi":"Nợ nần tích tụ và cuối cùng đã phá sản."},{"ko":"경험이 누적될수록 실력이 향상됩니다.","boi":"gyeong-heom-i nu-jeok-doel-su-rok sil-ryeok-i hyang-sang-doep-ni-da","vi":"Kinh nghiệm càng tích lũy nhiều thì năng lực càng được nâng cao."},{"ko":"누적 적자가 1조 원을 넘어섰다.","boi":"nu-jeok jeok-ja-ga il-jo won-eul neom-eo-seot-da","vi":"Thâm hụt tích lũy đã vượt 1 nghìn tỷ won."},{"ko":"피로가 누적되지 않도록 충분히 쉬어야 한다.","boi":"pi-ro-ga nu-jeok-doe-ji an-do-rok chung-bun-hi swi-eo-ya han-da","vi":"Phải nghỉ ngơi đầy đủ để mệt mỏi không bị tích tụ."}]',
'[{"word":"축적","hanja":"蓄積","meaning":"Tích lũy, thu thập dần"},{"word":"적체","hanja":"積滯","meaning":"Ứ đọng, tồn đọng"},{"word":"증가","hanja":"增加","meaning":"Tăng thêm, gia tăng"}]',
'累(lũy - chồng chất) + 積(tích - tích lũy) = Lũy Tích. Cả hai chữ cùng nghĩa tích lũy, nhấn mạnh kép. Hình ảnh: đống tuyết ngày càng to.','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(209,'능가','凌駕','neung-ga','Vượt trội, vượt qua, hơn hẳn',
'[{"char":"凌","reading":"능","meaning":"vượt qua, lấn át"},{"char":"駕","reading":"가","meaning":"cưỡi lên, đứng trên"}]',
'[{"ko":"그의 실력은 다른 선수들을 능가합니다.","boi":"geu-ui sil-ryeok-eun da-reun seon-su-deul-eul neung-ga-hap-ni-da","vi":"Năng lực của anh ấy vượt trội so với các vận động viên khác."},{"ko":"이 제품의 성능은 경쟁사 제품을 능가한다.","boi":"i je-pum-ui seong-neung-eun gyeong-jaeng-sa je-pum-eul neung-ga-han-da","vi":"Hiệu suất sản phẩm này vượt trội sản phẩm đối thủ."},{"ko":"예상을 능가하는 결과가 나왔습니다.","boi":"ye-sang-eul neung-ga-ha-neun gyeol-gwa-ga na-wat-seup-ni-da","vi":"Kết quả đã vượt ngoài dự kiến."},{"ko":"인공지능이 인간의 능력을 능가하는 날이 올까요?","boi":"in-gong-ji-neung-i in-gan-ui neung-ryeok-eul neung-ga-ha-neun nal-i ol-kka-yo","vi":"Liệu có ngày AI vượt qua năng lực con người không?"},{"ko":"매출이 작년을 능가하는 성과를 거뒀다.","boi":"mae-chul-i jang-nyeon-eul neung-ga-ha-neun seong-gwa-reul geo-dwot-da","vi":"Đạt thành tích doanh số vượt qua năm ngoái."}]',
'[{"word":"초월","hanja":"超越","meaning":"Vượt qua, siêu việt"},{"word":"압도","hanja":"壓倒","meaning":"Áp đảo, vượt trội hoàn toàn"},{"word":"탁월","hanja":"卓越","meaning":"Xuất sắc, xuất chúng"}]',
'凌(lăng - vượt qua, lấn át) + 駕(giá - cưỡi lên trên) = Lăng Giá = vượt lên cưỡi trên tất cả = vượt trội. Hình ảnh: ngựa phi vượt qua mọi đối thủ.','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(210,'능숙','能熟','neung-suk','Thành thạo, thuần thục, lành nghề',
'[{"char":"能","reading":"능","meaning":"có thể, năng lực"},{"char":"熟","reading":"숙","meaning":"thuần thục, chín, quen thuộc"}]',
'[{"ko":"그는 한국어를 능숙하게 구사합니다.","boi":"geu-neun han-guk-eo-reul neung-suk-ha-ge gu-sa-hap-ni-da","vi":"Anh ấy sử dụng tiếng Hàn một cách thành thạo."},{"ko":"능숙한 솜씨로 요리를 만들었습니다.","boi":"neung-suk-han som-ssi-ro yo-ri-reul man-deul-eot-seup-ni-da","vi":"Nấu món ăn với bàn tay thành thạo."},{"ko":"반복 연습을 통해 능숙해질 수 있습니다.","boi":"ban-bok yeon-seup-eul tong-hae neung-suk-hae-jil su it-seup-ni-da","vi":"Có thể trở nên thành thạo thông qua luyện tập lặp lại."},{"ko":"컴퓨터를 능숙하게 다루는 직원을 원합니다.","boi":"keom-pyu-teo-reul neung-suk-ha-ge da-ru-neun jik-won-eul won-hap-ni-da","vi":"Muốn tuyển nhân viên thành thạo máy tính."},{"ko":"10년의 경험으로 그는 능숙한 전문가가 되었다.","boi":"sip-nyeon-ui gyeong-heom-eu-ro geu-neun neung-suk-han jeon-mun-ga-ga doe-eot-da","vi":"Với 10 năm kinh nghiệm, anh ấy trở thành chuyên gia thành thạo."}]',
'[{"word":"숙련","hanja":"熟練","meaning":"Thành thạo, lành nghề"},{"word":"능력","hanja":"能力","meaning":"Năng lực, khả năng"},{"word":"미숙","hanja":"未熟","meaning":"Chưa thành thạo (trái nghĩa)"}]',
'能(năng - có khả năng) + 熟(thục - chín, thuần thục) = Năng Thục = có khả năng đã chín muồi = thành thạo. Trái nghĩa: 미숙 (chưa chín).','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(211,'다수결','多數決','da-su-gyeol','Quyết định theo đa số, biểu quyết đa số',
'[{"char":"多","reading":"다","meaning":"nhiều, đa"},{"char":"數","reading":"수","meaning":"số, đếm"},{"char":"決","reading":"결","meaning":"quyết định"}]',
'[{"ko":"안건이 다수결로 통과되었습니다.","boi":"an-geon-i da-su-gyeol-lo tong-gwa-doe-eot-seup-ni-da","vi":"Vấn đề đã được thông qua theo nguyên tắc đa số."},{"ko":"다수결 원칙에 따라 의사 결정을 합니다.","boi":"da-su-gyeol won-chik-e dda-ra ui-sa gyeol-jeong-eul hap-ni-da","vi":"Chúng tôi ra quyết định theo nguyên tắc đa số."},{"ko":"다수결이 항상 옳은 것은 아닙니다.","boi":"da-su-gyeol-i hang-sang ol-eun geot-eun a-nip-ni-da","vi":"Quyết định theo đa số không phải lúc nào cũng đúng."},{"ko":"학생회장을 다수결로 선출합니다.","boi":"hak-saeng-hoe-jang-eul da-su-gyeol-lo seon-chul-hap-ni-da","vi":"Bầu chủ tịch hội học sinh theo nguyên tắc đa số."},{"ko":"다수결이 아닌 만장일치로 결정했습니다.","boi":"da-su-gyeol-i a-nin man-jang-il-chi-ro gyeol-jeong-haet-seup-ni-da","vi":"Chúng tôi quyết định bằng nhất trí chứ không phải đa số."}]',
'[{"word":"만장일치","hanja":"滿場一致","meaning":"Nhất trí toàn thể"},{"word":"표결","hanja":"表決","meaning":"Biểu quyết, bỏ phiếu"},{"word":"소수","hanja":"少數","meaning":"Thiểu số (trái nghĩa với 다수)"}]',
'多(đa - nhiều) + 數(số - con số) + 決(quyết - quyết định) = Đa Số Quyết = quyết định theo số đông. Nhớ: 다수결 원칙 (nguyên tắc đa số).','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(212,'단속','團束','dan-sok','Kiểm soát, kiểm tra, bắt giữ vi phạm',
'[{"char":"團","reading":"단","meaning":"đoàn, tập hợp"},{"char":"束","reading":"속","meaning":"bó lại, ràng buộc, kiểm soát"}]',
'[{"ko":"경찰이 음주 운전 단속을 실시하고 있습니다.","boi":"gyeong-chal-i eum-ju un-jeon dan-sok-eul sil-si-ha-go it-seup-ni-da","vi":"Cảnh sát đang tiến hành kiểm soát lái xe say rượu."},{"ko":"불법 주차 단속이 강화되었습니다.","boi":"bul-beop ju-cha dan-sok-i gang-hwa-doe-eot-seup-ni-da","vi":"Việc kiểm tra đỗ xe trái phép đã được tăng cường."},{"ko":"어린 자녀의 스마트폰 사용을 단속해야 합니다.","boi":"eo-rin ja-nyeo-ui seu-ma-teu-pon sa-yong-eul dan-sok-hae-ya hap-ni-da","vi":"Cần kiểm soát việc dùng điện thoại của trẻ nhỏ."},{"ko":"세관에서 밀수품 단속이 강화됐다.","boi":"se-gwan-e-seo mil-su-pum dan-sok-i gang-hwa-dwaet-da","vi":"Kiểm tra hàng lậu tại hải quan được tăng cường."},{"ko":"학교 측이 학생들의 복장 단속을 시작했다.","boi":"hak-gyo jeuk-i hak-saeng-deul-ui bok-jang dan-sok-eul si-jak-haet-da","vi":"Nhà trường bắt đầu kiểm tra trang phục của học sinh."}]',
'[{"word":"통제","hanja":"統制","meaning":"Kiểm soát, điều tiết"},{"word":"규제","hanja":"規制","meaning":"Quy định, hạn chế"},{"word":"관리","hanja":"管理","meaning":"Quản lý, giám sát"}]',
'團(đoàn - tập hợp) + 束(thúc - bó buộc) = Đoàn Thúc = tập hợp để bó buộc vi phạm = kiểm soát. Hình ảnh: cảnh sát đoàn kết bắt giữ vi phạm.','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(213,'단절','斷絶','dan-jeol','Sự cắt đứt, gián đoạn, đứt đoạn',
'[{"char":"斷","reading":"단","meaning":"cắt đứt, đoạn"},{"char":"絶","reading":"절","meaning":"dứt hẳn, tuyệt, không còn"}]',
'[{"ko":"두 나라 사이의 외교 관계가 단절되었습니다.","boi":"du na-ra sa-i-ui oe-gyo gwan-gye-ga dan-jeol-doe-eot-seup-ni-da","vi":"Quan hệ ngoại giao giữa hai nước đã bị cắt đứt."},{"ko":"통신 두절로 외부와의 연락이 단절됐다.","boi":"tong-sin du-jeol-lo oe-bu-wa-ui yeol-lak-i dan-jeol-dwaet-da","vi":"Liên lạc với bên ngoài bị gián đoạn do mất tín hiệu."},{"ko":"그는 가족과의 관계가 완전히 단절되어 있다.","boi":"geu-neun ga-jok-gwa-ui gwan-gye-ga wan-jeon-hi dan-jeol-doe-eo it-da","vi":"Mối quan hệ của anh ấy với gia đình đã hoàn toàn bị cắt đứt."},{"ko":"세대 간의 소통 단절이 심각한 문제다.","boi":"se-dae gan-ui so-tong dan-jeol-i sim-gak-han mun-je-da","vi":"Sự gián đoạn giao tiếp giữa các thế hệ là vấn đề nghiêm trọng."},{"ko":"전쟁으로 인해 철도 연결이 단절되었습니다.","boi":"jeon-jaeng-eu-ro in-hae cheol-do yeol-gyeol-i dan-jeol-doe-eot-seup-ni-da","vi":"Kết nối đường sắt bị gián đoạn do chiến tranh."}]',
'[{"word":"차단","hanja":"遮斷","meaning":"Chặn đứt, ngăn chặn"},{"word":"연결","hanja":"連結","meaning":"Kết nối, liên kết (trái nghĩa)"},{"word":"절연","hanja":"絶緣","meaning":"Cắt đứt quan hệ, cách điện"}]',
'斷(đoạn - cắt đứt) + 絶(tuyệt - không còn gì) = Đoạn Tuyệt = cắt đứt hoàn toàn. Hai chữ đều mang nghĩa dứt đoạn, nhấn mạnh kép.','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(214,'단호','斷乎','dan-ho','Kiên quyết, dứt khoát, cương quyết',
'[{"char":"斷","reading":"단","meaning":"cắt đứt, quyết đoán"},{"char":"乎","reading":"호","meaning":"trợ từ nhấn mạnh (rõ ràng là)"}]',
'[{"ko":"그녀는 단호하게 거절했습니다.","boi":"geu-nyeo-neun dan-ho-ha-ge geo-jeol-haet-seup-ni-da","vi":"Cô ấy đã từ chối một cách kiên quyết."},{"ko":"단호한 태도로 문제에 맞서야 합니다.","boi":"dan-ho-han tae-do-ro mun-je-e mat-seo-ya hap-ni-da","vi":"Phải đối mặt với vấn đề bằng thái độ cứng rắn."},{"ko":"그는 단호히 자신의 입장을 밝혔다.","boi":"geu-neun dan-ho-hi ja-sin-ui ip-jang-eul pal-kyeot-da","vi":"Anh ấy đã bày tỏ lập trường của mình một cách dứt khoát."},{"ko":"이 문제에 대해서는 단호하게 대처해야 한다.","boi":"i mun-je-e dae-hae-seo-neun dan-ho-ha-ge dae-cheo-hae-ya han-da","vi":"Phải xử lý vấn đề này một cách kiên quyết."},{"ko":"단호한 결정을 내리기가 쉽지 않았습니다.","boi":"dan-ho-han gyeol-jeong-eul nae-ri-gi-ga swip-ji an-at-seup-ni-da","vi":"Đưa ra quyết định dứt khoát không phải điều dễ dàng."}]',
'[{"word":"결연","hanja":"決然","meaning":"Cương quyết, quyết tâm"},{"word":"확고","hanja":"確固","meaning":"Kiên định, vững chắc"},{"word":"우유부단","hanja":"優柔不斷","meaning":"Do dự, không quyết đoán (trái nghĩa)"}]',
'斷(đoạn - dứt khoát, quyết đoán) + 乎(hồ - nhấn mạnh) = Đoán Hồ = dứt khoát rõ ràng = kiên quyết. Người 단호한 사람 không bao giờ do dự.','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(215,'달성','達成','dal-seong','Đạt được, hoàn thành mục tiêu',
'[{"char":"達","reading":"달","meaning":"đạt tới, thông đạt"},{"char":"成","reading":"성","meaning":"thành công, hoàn thành"}]',
'[{"ko":"목표를 달성하기 위해 열심히 노력했습니다.","boi":"mok-pyo-reul dal-seong-ha-gi wi-hae yeol-sim-hi no-ryeok-haet-seup-ni-da","vi":"Tôi đã nỗ lực hết mình để đạt được mục tiêu."},{"ko":"이번 분기 매출 목표를 달성했습니다.","boi":"i-beon bun-gi mae-chul mok-pyo-reul dal-seong-haet-seup-ni-da","vi":"Chúng tôi đã đạt mục tiêu doanh số quý này."},{"ko":"꿈을 달성하는 데는 오랜 시간이 걸립니다.","boi":"kkum-eul dal-seong-ha-neun de-neun o-raen si-gan-i geol-lip-ni-da","vi":"Để đạt được giấc mơ cần rất nhiều thời gian."},{"ko":"모든 임무를 성공적으로 달성했습니다.","boi":"mo-deun im-mu-reul seong-gong-jeok-eu-ro dal-seong-haet-seup-ni-da","vi":"Tôi đã hoàn thành tất cả nhiệm vụ thành công."},{"ko":"어려운 과제를 달성했을 때의 성취감은 말할 수 없습니다.","boi":"eo-ryeo-un gwa-je-reul dal-seong-haet-eul ttae-ui seong-chwi-gam-eun mal-hal su eop-seup-ni-da","vi":"Cảm giác thành tựu khi hoàn thành nhiệm vụ khó thật không thể tả."}]',
'[{"word":"성취","hanja":"成就","meaning":"Thành tựu, đạt được kết quả"},{"word":"완성","hanja":"完成","meaning":"Hoàn thành, hoàn tất"},{"word":"실패","hanja":"失敗","meaning":"Thất bại (trái nghĩa)"}]',
'達(đạt - đạt tới) + 成(thành - thành công) = Đạt Thành. Cả hai chữ đều mang nghĩa tích cực. Câu tự nhắc: 목표 달성! (Đạt mục tiêu!)','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(216,'담보','擔保','dam-bo','Sự đảm bảo, thế chấp, bảo đảm',
'[{"char":"擔","reading":"담","meaning":"gánh vác, chịu đựng, đảm"},{"char":"保","reading":"보","meaning":"bảo vệ, giữ gìn, đảm bảo"}]',
'[{"ko":"집을 담보로 대출을 받았습니다.","boi":"jip-eul dam-bo-ro dae-chul-eul bat-seup-ni-da","vi":"Tôi đã vay tiền với nhà làm tài sản thế chấp."},{"ko":"이 계약은 품질을 담보하지 않습니다.","boi":"i gye-yak-eun pum-jil-eul dam-bo-ha-ji an-seup-ni-da","vi":"Hợp đồng này không đảm bảo chất lượng."},{"ko":"담보 없이는 대출이 어렵습니다.","boi":"dam-bo eop-si-neun dae-chul-i eo-ryeop-seup-ni-da","vi":"Khó vay tiền mà không có tài sản thế chấp."},{"ko":"안전을 담보할 수 없는 상황이다.","boi":"an-jeon-eul dam-bo-hal su eom-neun sang-hwang-i-da","vi":"Đây là tình huống không thể đảm bảo an toàn."},{"ko":"담보물을 제공하면 더 낮은 금리로 대출받을 수 있습니다.","boi":"dam-bo-mul-eul je-gong-ha-myeon deo nat-eun geum-ri-ro dae-chul-bat-eul su it-seup-ni-da","vi":"Nếu cung cấp tài sản thế chấp, bạn có thể vay với lãi suất thấp hơn."}]',
'[{"word":"보증","hanja":"保證","meaning":"Bảo lãnh, đảm bảo"},{"word":"저당","hanja":"抵當","meaning":"Thế chấp, cầm cố"},{"word":"신용","hanja":"信用","meaning":"Tín dụng, uy tín"}]',
'擔(đảm - gánh vác) + 保(bảo - bảo vệ) = Đảm Bảo. Gánh vác trách nhiệm bảo vệ = đảm bảo. Khi vay ngân hàng phải 담보 (thế chấp) tài sản.','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(217,'담합','談合','dam-hap','Sự thông đồng, cấu kết (thường trái pháp luật)',
'[{"char":"談","reading":"담","meaning":"nói chuyện, đàm phán"},{"char":"合","reading":"합","meaning":"hợp nhau, thỏa thuận"}]',
'[{"ko":"건설사들이 입찰 담합을 한 혐의로 기소됐습니다.","boi":"geon-seol-sa-deul-i ip-chal dam-hap-eul han hyeom-ui-ro gi-so-dwaet-seup-ni-da","vi":"Các công ty xây dựng bị truy tố với tội danh thông đồng đấu thầu."},{"ko":"가격 담합은 불공정 거래 행위입니다.","boi":"ga-gyeok dam-hap-eun bul-gong-jeong geo-rae haeng-wi-ip-ni-da","vi":"Thông đồng về giá cả là hành vi thương mại không lành mạnh."},{"ko":"경쟁사들 간의 담합이 적발되었습니다.","boi":"gyeong-jaeng-sa-deul gan-ui dam-hap-i jeok-bal-doe-eot-seup-ni-da","vi":"Sự thông đồng giữa các đối thủ đã bị phát hiện."},{"ko":"담합 행위는 법으로 엄격히 금지되어 있습니다.","boi":"dam-hap haeng-wi-neun beop-eu-ro eom-gyeok-hi geum-ji-doe-eo it-seup-ni-da","vi":"Hành vi thông đồng bị pháp luật nghiêm cấm."},{"ko":"정부는 담합 근절을 위한 조치를 강화하고 있습니다.","boi":"jeong-bu-neun dam-hap geun-jeol-eul wi-han jo-chi-reul gang-hwa-ha-go it-seup-ni-da","vi":"Chính phủ tăng cường biện pháp loại trừ thông đồng."}]',
'[{"word":"공모","hanja":"共謀","meaning":"Đồng mưu, cùng âm mưu"},{"word":"결탁","hanja":"結托","meaning":"Cấu kết, thông đồng"},{"word":"협잡","hanja":"挾雜","meaning":"Gian lận, lừa đảo"}]',
'談(đàm - nói chuyện bí mật) + 合(hợp - thỏa thuận) = Đàm Hợp = bí mật thỏa thuận cùng nhau = thông đồng. 가격 담합 (thông đồng giá) là vi phạm pháp luật.','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(218,'당국','當局','dang-guk','Nhà chức trách, cơ quan đương cục',
'[{"char":"當","reading":"당","meaning":"đương, phụ trách, chịu trách nhiệm"},{"char":"局","reading":"국","meaning":"cục, cơ quan, bộ phận"}]',
'[{"ko":"당국은 사건 조사에 착수했습니다.","boi":"dang-guk-eun sa-geon jo-sa-e chak-su-haet-seup-ni-da","vi":"Nhà chức trách đã bắt đầu điều tra vụ việc."},{"ko":"보건 당국은 전염병 확산 방지에 나섰습니다.","boi":"bo-geon dang-guk-eun jeon-yeom-byeong hwak-san bang-ji-e na-seot-seup-ni-da","vi":"Cơ quan y tế ra tay ngăn chặn sự lây lan của dịch bệnh."},{"ko":"당국의 허가 없이는 진행할 수 없습니다.","boi":"dang-guk-ui heo-ga eop-si-neun jin-haeng-hal su eop-seup-ni-da","vi":"Không thể tiến hành mà không có sự cho phép của nhà chức trách."},{"ko":"세관 당국이 화물을 검사했습니다.","boi":"se-gwan dang-guk-i hwa-mul-eul geom-sa-haet-seup-ni-da","vi":"Cơ quan hải quan đã kiểm tra hàng hóa."},{"ko":"관계 당국에 신고해야 할 사항입니다.","boi":"gwan-gye dang-guk-e sin-go-hae-ya hal sa-hang-ip-ni-da","vi":"Đây là vấn đề cần báo cáo với cơ quan chức năng liên quan."}]',
'[{"word":"관계당국","hanja":"關係當局","meaning":"Cơ quan chức năng liên quan"},{"word":"정부","hanja":"政府","meaning":"Chính phủ"},{"word":"기관","hanja":"機關","meaning":"Cơ quan, tổ chức"}]',
'當(đương - phụ trách, đang) + 局(cục - cơ quan) = Đương Cục = cơ quan đang phụ trách = nhà chức trách. Hay gặp: 당국에 따르면... (Theo nhà chức trách...).','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(219,'당면','當面','dang-myeon','Đối mặt, trước mắt, đang phải đối diện',
'[{"char":"當","reading":"당","meaning":"đương, đang, trực tiếp"},{"char":"面","reading":"면","meaning":"mặt, đối diện, phía trước"}]',
'[{"ko":"당면한 문제를 먼저 해결해야 합니다.","boi":"dang-myeon-han mun-je-reul meon-jeo hae-gyeol-hae-ya hap-ni-da","vi":"Phải giải quyết vấn đề trước mắt trước tiên."},{"ko":"우리가 당면한 과제는 매우 어렵습니다.","boi":"u-ri-ga dang-myeon-han gwa-je-neun mae-u eo-ryeop-seup-ni-da","vi":"Nhiệm vụ chúng ta đang đối mặt rất khó khăn."},{"ko":"경제 위기라는 당면 현실을 직시해야 한다.","boi":"gyeong-je wi-gi-ra-neun dang-myeon hyeon-sil-eul jik-si-hae-ya han-da","vi":"Phải nhìn thẳng vào thực tế trước mắt là khủng hoảng kinh tế."},{"ko":"당면 과제 해결을 위한 특별위원회가 구성됐다.","boi":"dang-myeon gwa-je hae-gyeol-eul wi-han teuk-byeol-wi-won-hoe-ga gu-seong-dwaet-da","vi":"Ủy ban đặc biệt thành lập để giải quyết các vấn đề trước mắt."},{"ko":"모든 어려움에 당면하더라도 포기하지 마세요.","boi":"mo-deun eo-ryeo-um-e dang-myeon-ha-deo-ra-do po-gi-ha-ji ma-se-yo","vi":"Dù phải đối mặt với mọi khó khăn, đừng từ bỏ."}]',
'[{"word":"직면","hanja":"直面","meaning":"Trực tiếp đối mặt, đương đầu"},{"word":"현안","hanja":"懸案","meaning":"Vấn đề hiện tại cần giải quyết"},{"word":"과제","hanja":"課題","meaning":"Nhiệm vụ, vấn đề cần giải quyết"}]',
'當(đương - đang, trực tiếp) + 面(diện - mặt) = Đương Diện = đang đối mặt trực tiếp. Hay dùng: 당면 과제 (nhiệm vụ trước mắt), 당면한 문제 (vấn đề đang đối mặt).','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

INSERT INTO public.hanja_pro (id,hangul,hanja,slug,meaning_vn,hanja_breakdown,examples,related_words,mnemonic,raw) VALUES
(220,'당선','當選','dang-seon','Trúng cử, đắc cử, được bầu chọn',
'[{"char":"當","reading":"당","meaning":"đương, đúng, được"},{"char":"選","reading":"선","meaning":"lựa chọn, bầu chọn, tuyển"}]',
'[{"ko":"그는 이번 선거에서 당선되었습니다.","boi":"geu-neun i-beon seon-geo-e-seo dang-seon-doe-eot-seup-ni-da","vi":"Anh ấy đã trúng cử trong cuộc bầu cử lần này."},{"ko":"당선 소감을 밝혀 주시겠어요?","boi":"dang-seon so-gam-eul pal-kyeo ju-si-get-eo-yo","vi":"Anh/Chị có thể chia sẻ cảm nghĩ khi trúng cử không?"},{"ko":"그녀는 세 번이나 국회의원에 당선됐다.","boi":"geu-nyeo-neun se beon-i-na guk-hoe-ui-won-e dang-seon-dwaet-da","vi":"Cô ấy đã trúng cử đại biểu quốc hội đến ba lần."},{"ko":"가장 많은 득표를 받은 후보가 당선됩니다.","boi":"ga-jang ma-neun deuk-pyo-reul bat-eun hu-bo-ga dang-seon-doep-ni-da","vi":"Ứng viên nhận được nhiều phiếu nhất sẽ trúng cử."},{"ko":"당선 가능성이 높은 후보를 지지합니다.","boi":"dang-seon ga-neung-seong-i no-peun hu-bo-reul ji-ji-hap-ni-da","vi":"Tôi ủng hộ ứng viên có khả năng trúng cử cao."}]',
'[{"word":"낙선","hanja":"落選","meaning":"Thất cử, không trúng cử (trái nghĩa)"},{"word":"출마","hanja":"出馬","meaning":"Ra tranh cử, ứng cử"},{"word":"득표","hanja":"得票","meaning":"Nhận phiếu bầu, số phiếu đạt được"}]',
'當(đương - được, đúng) + 選(tuyển - được chọn) = Đương Tuyển = được chọn đúng vào vị trí = trúng cử. Trái nghĩa: 낙선 (lạc tuyển - rớt bầu cử).','')
ON CONFLICT (slug) DO UPDATE SET hangul=EXCLUDED.hangul,hanja=EXCLUDED.hanja,meaning_vn=EXCLUDED.meaning_vn,hanja_breakdown=EXCLUDED.hanja_breakdown::jsonb,examples=EXCLUDED.examples::jsonb,related_words=EXCLUDED.related_words::jsonb,mnemonic=EXCLUDED.mnemonic;

SELECT setval('hanja_pro_id_seq', GREATEST((SELECT MAX(id) FROM public.hanja_pro), 300));
