-- Migration: Seed Đề 1 + Đề 2 EPS-TOPIK vào DB (idempotent).
-- Auto-generated by scripts/gen-eps-exam-seed.mjs from
--   src/data/eps_de1.ts (DE1_QUESTIONS + DE1_EXPLANATIONS + DE1_INFO)
--   src/data/eps_de2.ts (DE2_QUESTIONS + DE2_EXPLANATIONS + DE2_INFO)
-- Re-run safe: dùng deterministic UUID + upsert on conflict.
-- Đừng sửa file này thủ công — chạy lại script khi đề tĩnh đổi.

begin;

-- ── Đề 1 ─────────────────────────────────────────────
insert into public.eps_exams (id, slug, title, year, exam_no, description, total_questions, time_minutes, is_published)
values ('11111111-de01-4000-8000-000000000001'::uuid, 'eps-de-1', 'ĐỀ SỐ 01', 2025, 1, 'Đề thi EPS-TOPIK thật (40 câu — 20 đọc + 20 nghe). Có audio + giải thích chi tiết.', 40, 50, true)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  total_questions = excluded.total_questions,
  time_minutes = excluded.time_minutes,
  is_published = excluded.is_published,
  updated_at = now();

insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 1, 'image', 'reading', 'image', '다음 내용과 관계있는 그림을 고르십시오.', '냉장고입니다.', NULL, '["에어컨","세탁기","식기세척기","냉장고"]'::jsonb, '["/de1/p2_img3.webp","/de1/p2_img4.webp","/de1/p2_img5.webp","/de1/p2_img6.webp"]'::jsonb, NULL, NULL, NULL, '냉장고 = tủ lạnh, dùng bảo quản thực phẩm. Phân biệt: 에어컨(điều hòa), 세탁기(máy giặt), 식기세척기(máy rửa chén).', 4)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 2, 'image', 'reading', 'image', '다음 내용과 관계있는 그림을 고르십시오.', '빵을 자르고 있습니다.', NULL, '["빵 자르기","감자 깎기","반죽하기","채칼 사용"]'::jsonb, '["/de1/p2_img8.webp","/de1/p2_img7.webp","/de1/p2_img10.webp","/de1/p2_img9.webp"]'::jsonb, NULL, NULL, NULL, '빵을 자르다 = cắt bánh mì. Hình ① có dao và ổ bánh mì. Phân biệt: 감자 깎다(gọt khoai), 반죽하다(nhào bột), 채칼(dụng cụ bào).', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 3, 'reading', 'reading', 'text', '다음 내용과 관계있는 것을 고르십시오.', '독서', NULL, '["위치","국적","취미","가족"]'::jsonb, NULL, NULL, NULL, NULL, '독서(đọc sách) là một loại 취미(sở thích). Phân biệt: 위치(vị trí), 국적(quốc tịch), 가족(gia đình).', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 4, 'reading', 'reading', 'text', '다음 내용과 관계있는 것을 고르십시오.', '건강, 경치, 사이, 분위기', NULL, '["위치","국적","하다","가족"]'::jsonb, NULL, NULL, NULL, NULL, '건강(sức khỏe), 경치(cảnh sắc), 사이(quan hệ), 분위기(không khí) → đều kết hợp 좋다 hoặc 하다 để mô tả trạng thái. Nhóm từ này liên quan đến 하다.', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 5, 'reading', 'reading', 'text', '다음 중 밑줄 친 부분이 맞는 문장을 고르십시오.', NULL, NULL, '["밥을 먹으면서 TV를 봅니다.","우리 언니는 피아노를 치하면서 노래를 해요.","운전으면서 전화하지 마세요.","학교에 다니하면서 아르바이트를 해요."]'::jsonb, NULL, NULL, NULL, NULL, 'Câu ①: 먹으면서 TV를 봅니다 — đúng cú pháp. Câu khác sai: 치하면서→치면서, 운전으면서→운전하면서, 다니하면서→다니면서.', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 6, 'reading', 'reading', 'text', '빈칸에 들어갈 가장 알맞은 것을 고르십시오.', '리한 씨와 저는 5월 12일에 태어났습니다. 우리는 태어난 해는 다르지만 ______이/가 같아서 함께 파티를 했습니다.', NULL, '["나이","생일","성격","외모"]'::jsonb, NULL, NULL, NULL, NULL, 'Cùng ngày tháng sinh (5월 12일) nhưng khác năm → cùng 생일(ngày sinh), không phải cùng 나이(tuổi).', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 7, 'reading', 'reading', 'text', '빈칸에 들어갈 가장 알맞은 것을 고르십시오.', '다음 주에 동료들과 여행을 가려고 합니다. 그래서 오늘 우리가 머물 숙소를 ______.', NULL, '["받았습니다.","주었습니다.","정리했습니다.","예약했습니다."]'::jsonb, NULL, NULL, NULL, NULL, '숙소를 예약하다 = đặt chỗ ở trước. 받다(nhận), 주다(cho), 정리하다(dọn dẹp) không phù hợp ngữ cảnh.', 4)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 8, 'reading', 'reading', 'text', '빈칸에 들어갈 가장 알맞은 것을 고르십시오.', '요즘은 일이 많아서 스트레스가 많습니다. 하지만 ______ 친구들을 만나서 이야기를 하면 스트레스가 풀립니다.', NULL, '["너무","가끔","벌써","제일"]'::jsonb, NULL, NULL, NULL, NULL, '가끔 = thỉnh thoảng — ngữ cảnh: đôi khi gặp bạn bè nói chuyện thì giải tỏa stress. 너무(quá), 벌써(đã rồi), 제일(nhất) không phù hợp.', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 9, 'reading', 'reading', 'text', '빈칸에 들어갈 가장 알맞은 것을 고르십시오.', '지난주에 시장에 가서 두꺼운 외투를 한 벌 샀습니다. 그 옷을 입으면 이번 겨울은 _____않을 것 같습니다.', NULL, '["춥지","덥지","바쁘지","기쁘지"]'::jsonb, NULL, NULL, NULL, NULL, '두꺼운 외투(áo khoác dày) → mặc khi mùa đông → 춥지 않을 것 (sẽ không lạnh). 덥지/바쁘지/기쁘지 không hợp ngữ cảnh.', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 10, 'reading', 'reading', 'text', '이 표지는 무슨 뜻입니까?', NULL, '/de1/p3_img3.webp', '["직진 및 좌회전 할 수 있습니다.","직진 및 우회전 할 수 있습니다.","직진만 할 수 있습니다.","좌우회전 할 수 있습니다."]'::jsonb, NULL, NULL, NULL, NULL, 'Biển giao thông mũi tên thẳng ↑ và rẽ phải → = 직진 및 우회전. Không phải rẽ trái hay chỉ thẳng.', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 11, 'reading', 'reading', 'text', '빈칸에 들어갈 가장 알맞은 것을 고르십시오.', '제가 세탁기를 ______.', NULL, '["쓸게요","돌릴게요","닦을게요","할게요"]'::jsonb, NULL, NULL, NULL, NULL, '세탁기를 돌리다 = cho chạy/bật máy giặt. Động từ đặc trưng của máy giặt là 돌리다, không phải 쓰다/닦다/하다.', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 12, 'reading', 'reading', 'text', '빈칸에 들어갈 가장 알맞은 것을 고르십시오.', '가: 손을 씻고 싶은데요. ____가/이 있으면 좀 주시겠어요?
나: 네, 여기 있어요.', NULL, '["장갑","거울","비누","치약"]'::jsonb, NULL, NULL, NULL, NULL, '손을 씻다(rửa tay) → cần 비누(xà phòng). 장갑(găng tay), 거울(gương), 치약(kem đánh răng) không liên quan.', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 13, 'reading', 'reading', 'text', '이 것을 사용하는 곳은 어디입니까?', NULL, '/de1/p3_img4.webp', '["청소년입니다.","수영장입니다.","오천 원입니다.","이월 이십일입니다."]'::jsonb, NULL, NULL, NULL, NULL, 'Vé có in 수영장, độ tuổi, giá tiền, ngày → dùng tại 수영장(bể bơi). Các đáp án kia là thông tin trên vé, không phải nơi dùng.', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 14, 'reading', 'reading', 'text', '직장인이 한국어를 배우는 이유에 대한 설명으로 맞는 것은 무엇입니까?', NULL, '/de1/p4_img1.webp', '["한국 회사에서 일하려고 배운다는 응답이 제일 적습니다.","드라마 이해를 위해 배운다는 응답이 두 번째로 많습니다.","학교를 다니기 위해 배운다는 응답이 절반에 가깝습니다.","한국인 친구를 사귀려고 배운다는 응답이 가장 많습니다."]'::jsonb, NULL, NULL, NULL, NULL, 'Biểu đồ tròn: cột ''học để đi học'' chiếm gần 50% → đáp án ③ đúng. Đáp án khác không khớp số liệu.', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 15, 'reading', 'reading', 'text', '다음은 무엇에 대한 설명입니까?', '초콜릿은 달아서 사람의 기분을 좋게 합니다. 그래서 사람들이 초콜릿을 자주 먹습니다. 그런데 말을 많이 할 때나 발표를 해야 할 때는 초콜릿을 먹지 않는 것이 좋습니다. 초콜릿을 먹으면 목이 마르게 되어서 목소리가 잘 안 나오기 때문입니다. 그래서 가수들도 공연 전에는 초콜릿을 먹지 않습니다.', NULL, '["초콜릿의 단점과 장점.","초콜릿의 가격","초콜릿을 먹는 이유.","초콜릿을 좋아하는 이유."]'::jsonb, NULL, NULL, NULL, NULL, 'Đoạn văn nói cả điểm tốt (làm vui) lẫn điểm xấu (làm khô họng) của chocolate → chủ đề là 단점과 장점(ưu và nhược điểm).', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 16, 'reading', 'reading', 'text', '다음은 무엇에 대한 설명입니까?', '작업장의 공구들은 여러 사람이 사용합니다. 사용한 다음에는 원래 있던 그대로 놓아두는 것이 가장 좋습니다. 제자리에 갖다 놓지 않거나 섞어 놓으면 다음에 사용하는 사람이 불편할 수 있습니다.', NULL, '["공구 절약","공구 정리","공구 종류","공구 수리"]'::jsonb, NULL, NULL, NULL, NULL, 'Bài nói về việc trả dụng cụ về đúng chỗ sau khi dùng → chủ đề là 공구 정리(sắp xếp dụng cụ).', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 17, 'reading', 'reading', 'text', '다음 글을 읽고 내용과 같은 것을 고르십시오.', '한복은 한국의 전통 의상으로 색상이 화려하고 디자인이 아름답습니다. 한국 사람들은 설날이나 결혼식과 같이 특별하고 중요한 날에 한복을 입습니다. 최근에는 전통 한복을 개량하여 만든 생활한복이 인기를 끌고 있습니다. 생활한복은 디자인이 단순하고 실용적이어서 일상생활에서도 편하게 입을 수 있습니다.', NULL, '["생활한복은 화려하고 디자인이 아름답습니다.","최근에 한국 사람들이 전통 한복을 많이 입습니다.","생활한복은 일상생활에서 편하게 입을 수 있습니다.","한국의 전통 의상은 색상이 단순하여 인기가 많습니다."]'::jsonb, NULL, NULL, NULL, NULL, 'Bài viết nói rõ ''생활한복은 실용적이어서 일상생활에서도 편하게 입을 수 있습니다'' → đáp án ③.', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 18, 'reading', 'reading', 'text', '다음 글을 읽고 내용과 같은 것을 고르십시오.', '양궁은 쉬워 보이지만 판단력과 인내심이 필요한 운동이다. 양궁에서는 활을 쏘는 순간이 제일 중요하다. 특히 언제 활을 쏘아야 할지 판단하는 것이 핵심이다. 또한 활을 쏘는 그 순간까지 숨을 멈추고 기다리는 인내심이 요구된다. 그렇기 때문에 판단력이 부족한 사람이나 인내심이 필요한 사람에게 매우 좋은 운동이라고 할 수 있다.', NULL, '["양궁으로 판단력을 높일 수 있다.","양궁의 핵심은 숨을 참는 것이다.","양궁으로 참을성을 기르기가 어렵다.","양궁은 단순한 운동이라 주목을 받았다."]'::jsonb, NULL, NULL, NULL, NULL, 'Bài nói bắn cung tốt cho người thiếu 판단력(phán đoán) và 인내심(kiên nhẫn) → có thể rèn 판단력 → đáp án ①.', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 19, 'reading', 'reading', 'text', '다음 설명에 알맞은 어휘를 고르십시오.', '도로에서 색이 있는 불빛으로 통행 차량이나 사람의 통행을 지시하는 장치입니다.', NULL, '["노선도","육교","신호등","화물선"]'::jsonb, NULL, NULL, NULL, NULL, '신호등 = đèn giao thông, dùng ánh sáng màu điều tiết xe cộ và người đi bộ. 노선도(sơ đồ tuyến), 육교(cầu vượt bộ hành), 화물선(tàu hàng).', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 20, 'reading', 'reading', 'text', '다음 설명에 알맞은 어휘를 고르십시오.', '매일(날마다) 세수할 때 필요한 용품입니다.', NULL, '["면도기","화장품","세면도구","비누"]'::jsonb, NULL, NULL, NULL, NULL, '세면도구 = dụng cụ vệ sinh cá nhân (rửa mặt hàng ngày). 면도기(dao cạo), 화장품(mỹ phẩm), 비누(xà phòng — chỉ 1 loại, không phải tập hợp).', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 21, 'listening', 'listening', 'text', '들은 것을 고르십시오.', '구 _________', NULL, '["구함","구입","구경","구청"]'::jsonb, NULL, '구경', NULL, 'Nghe: 1 từ ghép bắt đầu bằng ''구''', 'Nghe: ''구경'' — từ ghép bắt đầu bằng 구. Phân biệt: 구함(tìm), 구입(mua), 구경(ngắm/tham quan), 구청(ủy ban quận).', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 22, 'listening', 'listening', 'text', '들은 것을 고르십시오.', NULL, NULL, '["좋지 않았습니다.","가까워지 않습니다.","청소하지 않습니다.","좋아하지 않습니다."]'::jsonb, NULL, '청소하지 않습니다', NULL, 'Nghe: 1 câu phủ định', 'Nghe câu phủ định: ''청소하지 않습니다''. Cấu trúc: động từ + 지 않다 = phủ định.', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 23, 'listening', 'listening', 'image', '들은 것을 고르십시오.', NULL, NULL, '[".....",".....",".....","....."]'::jsonb, '["/de1/p5_img1.webp","/de1/p5_img2.webp","/de1/p5_img3.webp","/de1/p5_img4.webp"]'::jsonb, '저는 매일 지하철을 타고 회사에 갑니다.', NULL, 'Nghe cách di chuyển → chọn hình phương tiện đúng', 'Nghe: ''매일 지하철을 타고 회사에 갑니다'' → phương tiện là 지하철(tàu điện ngầm). Hình ② = tàu điện ngầm.', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 24, 'listening', 'listening', 'image', '들은 것을 고르십시오.', NULL, NULL, '[".....",".....",".....","....."]'::jsonb, '["/de1/p6_img2.webp","/de1/p6_img3.webp","/de1/p6_img4.webp","/de1/p6_img5.webp"]'::jsonb, '여자가 요리를 하고 있습니다.', NULL, 'Nghe mô tả hành động của người phụ nữ → chọn hình đúng', 'Nghe: ''여자가 요리를 하고 있습니다'' → người phụ nữ đang nấu ăn. Hình ① = nấu ăn.', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 25, 'listening', 'listening', 'text', '이것은 무엇입니까?', NULL, '/de1/p6_img6.webp', '[".....",".....",".....","....."]'::jsonb, NULL, '이것은 매일 아침 세수할 때 사용합니다. 손이나 얼굴을 깨끗이 씻을 수 있습니다.', '["세면도구입니다.","청소도구입니다.","주방용품입니다.","사무용품입니다."]'::jsonb, 'Nghe mô tả đồ vật dùng khi rửa mặt', 'Nghe mô tả đồ vật dùng rửa mặt mỗi sáng → 세면도구(dụng cụ vệ sinh mặt).', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 26, 'listening', 'listening', 'text', '여기는 어디입니까?', NULL, '/de1/p6_img7.webp', '[".....",".....",".....","....."]'::jsonb, NULL, '두 사람이 앉아서 음료를 마시며 이야기하고 있습니다. 자판기도 있습니다.', '["공장 식당입니다.","휴게실입니다.","회의실입니다.","사무실입니다."]'::jsonb, 'Nghe mô tả nơi có máy bán hàng tự động, nghỉ ngơi', 'Nghe: ''두 사람이 음료를 마시며 이야기하고 있습니다. 자판기도 있습니다'' → nơi nghỉ ngơi có máy bán hàng = 휴게실.', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 27, 'listening', 'listening', 'text', '이 사람은 무엇을 하고 있습니까?', NULL, '/de1/p6_img8.webp', '[".....",".....",".....","....."]'::jsonb, NULL, '이 사람은 용접 작업을 하고 있습니다.', '["청소하고 있습니다.","용접하고 있습니다.","운전하고 있습니다.","요리하고 있습니다."]'::jsonb, 'Nghe mô tả công việc → chọn đáp án đúng', 'Nghe: ''용접 작업을 하고 있습니다'' → người đang hàn (용접하다). Nhìn hình để xác nhận.', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 28, 'listening', 'listening', 'text', '그릇이 몇 개 있습니까?', NULL, '/de1/p6_img1.webp', '[".....",".....",".....","....."]'::jsonb, NULL, '그릇이 네 개 있습니다.', '["한 개입니다.","두 개입니다.","세 개입니다.","네 개입니다."]'::jsonb, 'Nhìn hình → Nghe số lượng → chọn đúng', 'Nghe: ''그릇이 네 개 있습니다'' → 4 cái bát. Nhìn ảnh đếm số bát.', 4)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 29, 'listening', 'listening', 'text', '수건은 어디에 있습니까?', NULL, '/de1/p7_img1.webp', '[".....",".....",".....","....."]'::jsonb, NULL, '수건이 선반 왼쪽 위에 있습니다.', '["선반 왼쪽 위에 있습니다.","선반 오른쪽에 있습니다.","세면대 위에 있습니다.","욕조 안에 있습니다."]'::jsonb, 'Nhìn hình kệ phòng tắm → Nghe vị trí khăn', 'Nghe: ''수건이 선반 왼쪽 위에 있습니다'' → khăn tắm ở trên góc trái kệ (선반 왼쪽 위).', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 30, 'listening', 'listening', 'text', '다음을 듣고 질문에 알맞은 대답을 고르십시오.', NULL, NULL, '["서울에 살아요.","힘들지만 재미있어요.","저년에 한국에 왔어요.","비행기로 다섯 시간 걸려요."]'::jsonb, NULL, '한국 생활이 어때요?', NULL, 'Câu hỏi: Cuộc sống ở Hàn Quốc thế nào?', 'Câu hỏi: ''한국 생활이 어때요?'' → trả lời phù hợp: ''힘들지만 재미있어요''(vất vả nhưng thú vị).', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 31, 'listening', 'listening', 'text', '다음을 듣고 질문에 알맞은 대답을 고르십시오.', NULL, NULL, '["저는 벌써 먹었는데요.","아직 안 들어왔는데요.","저는 영수 친구가 아닌데요.","오늘은 바빠서 못 가는데요."]'::jsonb, NULL, '영수 씨 아직 안 왔어요?', NULL, 'Câu hỏi: Anh Yeongsu chưa về à?', 'Câu hỏi: ''Anh Yeongsu chưa về à?'' → trả lời: ''아직 안 들어왔는데요''(chưa vào). Các đáp án khác lạc đề.', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 32, 'listening', 'listening', 'text', '다음을 듣고 질문에 알맞은 대답을 고르십시오.', NULL, NULL, '["아버지 마음이 아프시겠어요.","축의금을 많이 보내 드려야겠어요.","퇴근 후에 장례식장에 가야겠네요.","많이 다치지 않았으면 좋겠어요."]'::jsonb, NULL, '이 씨 아버지가 어제 돌아가셨대요.', NULL, 'Thông báo: Bố anh ấy mất rồi', 'Thông báo bố mất → phản ứng phù hợp: đi viếng đám tang sau giờ làm ''퇴근 후에 장례식장에 가야겠네요''.', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 33, 'listening', 'listening', 'text', '다음을 듣고 질문에 알맞은 대답을 고르십시오.', NULL, NULL, '["값이 싸고 쇼핑이 편리해서요.","인터넷 쇼핑을 하기 쉽지 않아요.","인터넷으로 쇼핑을 해 본 적이 없어요.","회원가입을 하려면 신분증이 필요해요."]'::jsonb, NULL, '왜 인터넷으로 쇼핑을 해요?', NULL, 'Câu hỏi: Tại sao mua hàng qua mạng?', 'Câu hỏi: ''Tại sao mua hàng online?'' → ''값이 싸고 쇼핑이 편리해서요''(rẻ và tiện lợi).', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 34, 'listening', 'listening', 'text', '다음을 듣고 이어지는 말을 고르십시오.', NULL, NULL, '["여기 표시한 데까지 해 주시면 돼요.","한 번도 옷을 고쳐 본 적이 없어요.","바지 길이가 조금 줄어들었나 봐요.","급하지 않으니까 천천히 해 주세요."]'::jsonb, NULL, '이 바지 길이를 좀 줄여 주실 수 있어요?', NULL, 'Yêu cầu sửa quần → phản hồi tiếp theo là gì?', 'Yêu cầu sửa ống quần → đáp án: ''여기 표시한 데까지 해 주시면 돼요''(làm đến chỗ tôi đánh dấu là được).', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 35, 'listening', 'listening', 'text', '다음을 듣고 이어지는 말을 고르십시오.', NULL, NULL, '["그러니까 조금 기다렸다가 가세요.","그러니까 집을 빨리 알아보면 돼요.","그래서 집을 못 구할까 봐 걱정이에요.","그래서 이제 마음 편하게 잘 수 있겠네요."]'::jsonb, NULL, '드디어 마음에 드는 집을 구했어요!', NULL, 'Thông báo tìm được nhà → phản hồi tiếp theo là gì?', 'Thông báo tìm được nhà → ''그래서 이제 마음 편하게 잘 수 있겠네요''(giờ có thể ngủ ngon rồi).', 4)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 36, 'listening', 'listening', 'image', '잘 듣고 들은 내용과 관계 있는 그림을 고르십시오.', NULL, NULL, '["두 명 수영 중","한 명 물화사하기","중간에서 체조","수영장 나가는 중"]'::jsonb, '["/de1/p8_img1.webp","/de1/p8_img2.webp","/de1/p8_img3.webp","/de1/p8_img4.webp"]'::jsonb, '남자: 오늘 수영장에 누가 왔어요? 여자: 남자와 여자 두 명이 수영장 안에서 공을 가지고 놀고 있었어요.', NULL, 'Hội thoại về cảnh bể bơi → chọn đúng hình mô tả', 'Nghe: hai người đang chơi bóng trong bể bơi → hình ① = hai người bơi/chơi trong bể.', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 37, 'listening', 'listening', 'image', '잘 듣고 들은 내용과 관계 있는 그림을 고르십시오.', NULL, NULL, '["직원이 어린이에게 보여주기","남자가 진열대 구경","여직원이 남성에게 건네주기","직원이 구매 거절"]'::jsonb, '["/de1/p8_img5.webp","/de1/p8_img6.webp","/de1/p8_img7.webp","/de1/p8_img8.webp"]'::jsonb, '여자 직원이 남자 손님에게 카메라를 건네주고 있습니다.', NULL, 'Mô tả cảnh cửa hàng máy ảnh → chọn đúng hình', 'Nghe: nhân viên nữ đưa máy ảnh cho khách nam → hình ③ = 여직원이 남성에게 건네주기.', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 38, 'listening', 'listening', 'text', '다음 중 들은 내용과 같은 것은 무엇입니까?', NULL, NULL, '["쓰레기봉투는 한 종류밖에 없다.","쓰레기양을 줄여서 환경을 보호한다.","정해진 장소에 쓰레기를 버리지 않아도 됩니다.","쓰레기 버릴 때는 돈이 들지 않습니다."]'::jsonb, NULL, '한국에서는 쓰레기를 버릴 때 종량제 봉투를 사용해야 합니다. 종량제 봉투는 크기에 따라 가격이 다릅니다. 이 제도는 쓰레기의 양을 줄여서 환경을 보호하기 위해 만들어졌습니다. 쓰레기는 반드시 정해진 장소에 버려야 합니다.', NULL, 'Đoạn thông báo về hệ thống túi rác tính theo khối lượng ở Hàn Quốc', 'Nghe về hệ thống túi rác: mục đích là ''giảm lượng rác, bảo vệ môi trường'' → 쓰레기양을 줄여서 환경을 보호한다.', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 39, 'listening', 'listening', 'text', '들은 내용과 같은 것을 고르십시오.', NULL, NULL, '["남자는 검진 결과를 보러 왔다.","여자는 검진을 받으려고 기다리고 있다.","여자는 남자와 이곳에서 만나기로 약속했다.","여자는 건강을 위해 음식에 신경 써야 합니다."]'::jsonb, NULL, '남자: 안녕하세요. 오늘 건강 검진을 받으러 왔는데요. 여자: 네, 어서 오세요. 검진 결과가 나왔는데요, 혈압이 조금 높게 나왔어요. 음식에 신경 쓰시는 게 좋을 것 같아요. 남자: 아, 그렇군요. 어떤 음식을 조심해야 할까요? 여자: 짠 음식을 줄이시고 채소를 많이 드세요.', NULL, 'Hội thoại tại phòng khám: bệnh nhân và bác sĩ', 'Bác sĩ khuyên: cần chú ý ăn uống (ít đồ mặn, ăn nhiều rau) → ''여자는 건강을 위해 음식에 신경 써야 합니다''.', 4)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de01-4000-8000-000000000001'::uuid, 40, 'listening', 'listening', 'text', '들은 내용과 같은 것을 고르십시오.', NULL, NULL, '["여자는 어제 일이 많았습니다.","여자는 어제 결혼을 했습니다.","남자는 어제 회사에서 일했습니다.","남자는 결혼식에서 여자를 만났습니다."]'::jsonb, NULL, '남자: 어제 결혼식에 갔어요? 여자: 네, 정말 예쁜 결혼식이었어요. 남자: 맞아요. 저도 거기서 여러 사람을 만났어요. 여자: 그래요? 누구 만났어요? 남자: 오랜만에 여자 씨를 거기서 만났잖아요. 여자: 맞다, 그렇군요.', NULL, 'Hội thoại về đám cưới hôm qua', 'Hội thoại về đám cưới: nam nói ''오랜만에 여자 씨를 거기서 만났잖아요'' → gặp người phụ nữ tại đám cưới.', 4)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;

-- ── Đề 2 ─────────────────────────────────────────────
insert into public.eps_exams (id, slug, title, year, exam_no, description, total_questions, time_minutes, is_published)
values ('11111111-de02-4000-8000-000000000002'::uuid, 'eps-de-2', 'Đề số 02', 2025, 2, 'Đề thi EPS-TOPIK thật (40 câu — 20 đọc + 20 nghe). Có audio + giải thích chi tiết.', 40, 50, true)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  total_questions = excluded.total_questions,
  time_minutes = excluded.time_minutes,
  is_published = excluded.is_published,
  updated_at = now();

insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 1, 'image', 'reading', 'image', '다음 내용과 관계있는 그림을 고르십시오.', '미용실입니다.', NULL, '["병원","회사","이용실/미용실","약국"]'::jsonb, '["/de2/p10_img2.webp","/de2/p10_img3.webp","/de2/p10_img4.webp","/de2/p10_img5.webp"]'::jsonb, NULL, NULL, NULL, '미용실 = tiệm cắt tóc/làm đẹp. Hình ③ có biển △△이용실 và cái kéo. Phân biệt: 병원(bệnh viện), 회사(công ty), 약국(nhà thuốc).', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 2, 'image', 'reading', 'image', '다음 내용과 관계있는 그림을 고르십시오.', '(그물을) 수선하다', NULL, '["어망 걷기","어망 세척","어망 건조","어망 수선"]'::jsonb, '["/de2/p10_img6_1.webp","/de2/p10_img6_2.webp","/de2/p10_img6_3.webp","/de2/p10_img6_4.webp"]'::jsonb, NULL, NULL, NULL, '수선하다 = sửa chữa, vá víu. Hình ④ thể hiện người ngồi tay vá lưới. Phân biệt: ①kéo lưới từ thuyền, ②rửa lưới bằng vòi, ③phơi lưới.', 4)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 3, 'reading', 'reading', 'text', '다음 단어의 비슷한 말을 고르십시오.', '채소', NULL, '["야채","고기","과일","음료"]'::jsonb, NULL, NULL, NULL, NULL, '채소 = rau củ → từ đồng nghĩa: 야채(rau). Phân biệt: 고기(thịt), 과일(trái cây), 음료(đồ uống).', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 4, 'reading', 'reading', 'text', '다음 단어와 관계있는 것은 무엇입니까?', '상 / 연극 / 시험 / 면접', NULL, '["쓰다","보다","만들다","주다"]'::jsonb, NULL, NULL, NULL, NULL, '상/연극/시험/면접 đều dùng với động từ 보다: 상을 보다(xem giải), 연극을 보다(xem kịch), 시험을 보다(thi), 면접을 보다(phỏng vấn).', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 5, 'reading', 'reading', 'text', '다음 중 밑줄 친 부분이 맞는 문장을 고르십시오.', NULL, NULL, '["책이 읽어요.","물을 마셔요.","전화에 해요.","신문는 봐요."]'::jsonb, NULL, NULL, NULL, NULL, 'Tiếng Hàn dùng trợ từ đối tượng 을/를: 물을 마셔요 (O). 책이→책을, 전화를 하다, 신문을 봐요.', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 6, 'reading', 'reading', 'text', '다음 중 밑줄 친 부분이 맞는 문장을 고르십시오.', NULL, NULL, '["실내에서 담배를 피우면 안 돼요.","한국에서는 밥을 먹을 때 코를 풀으면 안 돼요.","운전 중에 전화면 안 돼요.","수업 시간에는 영어로 말으면 안 돼요."]'::jsonb, NULL, NULL, NULL, NULL, 'Cấu trúc đúng: V+(으)면 안 돼요. ''실내에서 담배를 피우면 안 돼요'' → 피우다+면 = 피우면 ✓. Các câu còn lại lỗi chia động từ.', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 7, 'reading', 'reading', 'text', '빈칸에 들어갈 가장 알맞은 것을 고르십시오.', '직장 상사나 나이가 많은 동료에게 _____ 어깨에 손을 올리면 예의가 아닙니다.', NULL, '["포옹하는지","악수하는지","악수하거나","포옹하거나"]'::jsonb, NULL, NULL, NULL, NULL, '포옹하거나 어깨에 손을 올리면 = ''ôm hoặc đặt tay lên vai'' đều vô lễ với cấp trên. -거나 = hoặc (lựa chọn).', 4)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 8, 'reading', 'reading', 'text', '빈칸에 들어갈 가장 알맞은 것을 고르십시오.', '이번 주말에 제가 좋아하는 가수의 공연이 있습니다. 저는 두 달 전에 표를 미리 샀습니다. 공연을 빨리 _______.', NULL, '["보고 싶습니다.","본 적이 있어요.","보고 있어요.","본 것 같아요."]'::jsonb, NULL, NULL, NULL, NULL, '보고 싶다 = muốn xem. Ngữ cảnh: đã mua vé từ 2 tháng trước, nóng lòng muốn xem biểu diễn sớm.', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 9, 'reading', 'reading', 'text', '빈칸에 들어갈 가장 알맞은 것을 고르십시오.', '학생들이 너무 ________저는 교수님의 말을 못 들었어요.', NULL, '["미끄러져서","미끄러지고","시끄러워서","시끄럽고"]'::jsonb, NULL, NULL, NULL, NULL, '시끄러워서 = vì ồn ào. -아/어서 chỉ nguyên nhân. 미끄럽다=trơn, 시끄럽다=ồn ào.', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 10, 'reading', 'reading', 'text', '빈칸에 들어갈 가장 알맞은 것을 고르십시오.', '많은 사람들이 이용하는 공공장소에서는 예의를 지켜야 합니다. 함부로 쓰레기를 ______ 소리로 떠들면 안 됩니다.', NULL, '["떨거나","쓸거나","버리거나","정리하거나"]'::jsonb, NULL, NULL, NULL, NULL, '버리거나 소리로 떠들면 = vứt rác hoặc gây ồn → 버리다+거나 = 버리거나.', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 11, 'reading', 'reading', 'text', '빈칸에 들어갈 가장 알맞은 것을 고르십시오.', '가: 밖에 유리창이 너무 더러워______ 싶은데 걸레가 어디에 있어요?
나: 나도 모르는데 한번 화장실 문 뒤에 보세요.', NULL, '["정리하고","닦고","뿌리고","버리고"]'::jsonb, NULL, NULL, NULL, NULL, '닦고 싶다 = muốn lau. 유리창을 닦다 = lau kính cửa sổ. 정리하다=dọn dẹp, 뿌리다=phun, 버리다=vứt.', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 12, 'reading', 'reading', 'text', '빈칸에 들어갈 가장 알맞은 것을 고르십시오.', '주말에 친구하고 _______ 운동장에 갈 거예요.', NULL, '["운동한","운동하러","운동하니까","운동해서"]'::jsonb, NULL, NULL, NULL, NULL, '-러 가다 = đi để làm gì. 운동하러 운동장에 가다 = đi sân để tập thể dục.', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 13, 'reading', 'reading', 'text', '다음 그래프에 대한 설명으로 맞는 것을 고르십시오.', NULL, '/de2/p11_img3.webp', '["4개국 중에 영국이 코로나 영향을 제일 많이 받았다.","미국보다 이탈리아의 영향을 더 심하게 보인다.","4개국 중에 스페인이 두 번째로 영향을 받는 나라로 보인다.","스페인보다 미국이 영향을 덜 받는 나라로 보인다."]'::jsonb, NULL, NULL, NULL, NULL, 'Biểu đồ: 미국(40)>스페인(30)>이탈리아(20)>영국(10). Đáp án ③ đúng: Tây Ban Nha đứng thứ 2.', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 14, 'reading', 'reading', 'text', '표지는 무슨 뜻입니까?', NULL, '/de2/p12_img2.webp', '["기대면 안 됩니다.","물로 불을 끄면 안 됩니다.","스위치를 만지면 안 됩니다.","이 장소를 지나가면 안 됩니다."]'::jsonb, NULL, NULL, NULL, NULL, 'Biển báo cấm bật/tắt công tắc điện. Hình ảnh: công tắc có dấu X = 스위치를 만지면 안 됩니다.', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 15, 'reading', 'reading', 'text', '다음은 무엇에 대한 설명입니까?', '한국의 은행은 평일 오전 9시 반에 문을 열고 오후 4시 반에 문을 닫습니다. 토요일과 일요일에는 문을 열지 않습니다. 그런데 저는 오전 9시부터 오후 7시까지 회사에서 일해야 하기 때문에 은행에 가기 어렵습니다. 그래서 점심시간에 빨리 갔다 옵니다.', NULL, '["이용 시간","이용 안내","이용 방법","이용 사람"]'::jsonb, NULL, NULL, NULL, NULL, 'Đoạn văn mô tả giờ làm việc của ngân hàng (9:30-16:30) → chủ đề: 이용 시간 (giờ phục vụ).', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 16, 'reading', 'reading', 'text', '다음은 무엇에 대한 설명입니까?', '한국 생활에서 화재나 응급 환자가 생겼을 때는 119번에 전화를 하면 됩니다. 그 외에도 범죄를 신고할 때는 112번, 전화번호를 알고 싶을 때는 114번, 일기예보가 궁금할 때는 131번을 이용하면 됩니다. 도움이 필요할 때 언제든지 이런 전화번호들을 이용할 수 있습니다.', NULL, '["전화의 장점과 거는 방법","외국인들을 위한 상담 안내","알고 있으면 유용한 전화번호","환자가 생겼을 때 대처 방법"]'::jsonb, NULL, NULL, NULL, NULL, 'Đoạn văn liệt kê số điện thoại hữu ích (119/112/114/131) → chủ đề: 알고 있으면 유용한 전화번호.', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 17, 'reading', 'reading', 'text', '다음 글을 읽고 내용과 같은 것을 고르십시오.', '스마트팜은 생산성을 향상시키기 위하여 정보통신기술을 활용하는 농업 방식입니다. 빅데이터와 인공지능 기술을 활용하여 농작물의 성장 조건을 최적화하기 때문에 노동력을 줄이는 데도 도움을 줍니다. 한국에서는 스마트팜을 활용하여 과일, 쌈채소뿐만 아니라 허브류 재배도 하고 있습니다. 그리고 정부에서는 스마트팜 보급과 발전을 위해 다양한 정책으로 지원하고 있습니다.', NULL, '["스마트팜은 정부의 지원 없이 운영되고 있습니다.","스마트팜 방식을 이용하면 사람이 해야 할 일이 많아집니다.","한국에서는 스마트팜 방식으로 쌈채소를 재배하지 않습니다.","스마트팜은 농작물의 성장을 위해 인공지능 기술을 활용합니다."]'::jsonb, NULL, NULL, NULL, NULL, 'Đáp án ④ đúng: ''Nông nghiệp thông minh sử dụng AI để tối ưu điều kiện sinh trưởng''. ①②③ đều sai theo nội dung.', 4)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 18, 'reading', 'reading', 'text', '다음 글을 읽고 내용과 같은 것을 고르십시오.', '고용허가제는 고용노동부가 한국 내의 인력 부족 문제를 해결하고 외국인 노동자를 합법적으로 고용하기 위해 마련한 제도입니다. 자국에서 선발 시험을 통과한 지원자들은 사업주와 계약 후 한국 비자를 받을 수 있습니다. 한국에 온 후에는 한국인 노동자들과 동등하게 노동법이 정한 기본적인 권리를 보장 받으며 일할 수 있습니다.', NULL, '["지원자들은 한국에 입국한 후 사업주와 고용 계약을 합니다.","고용허가제는 한국에 살고 있는 외국인을 위한 취업 제도입니다.","지원자들은 시험에 통과해야 한국에서 일할 기회를 얻을 수 있습니다.","고용허가제로 한국에 온 외국인은 한국인들과 다른 노동법의 보호를 받습니다."]'::jsonb, NULL, NULL, NULL, NULL, 'Đáp án ③: Ứng viên phải qua kỳ thi tuyển chọn ở nước mình mới được cơ hội làm việc tại Hàn. ①②④ đều mâu thuẫn với nội dung.', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 19, 'reading', 'reading', 'text', '다음 설명에 알맞은 어휘를 고르십시오.', '에어리스 스프레이 건으로 페인트를 분사한 후 붓으로 페인트칠을 마무리합니다.', NULL, '["포장 작업","도장 작업","연마 작업","재단 작업"]'::jsonb, NULL, NULL, NULL, NULL, '도장 작업 = công việc sơn phủ bề mặt (painting/coating). Phân biệt: 포장(đóng gói), 연마(đánh bóng), 재단(cắt vải/vật liệu).', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 20, 'reading', 'reading', 'text', '다음은 무엇에 대한 설명입니까?', '이 보험에는 귀국 시 필요한 비용을 준비하기 위해서 근로자가 자기쪽으로 80일 이내에 일시금을 내고 가입해야 합니다.', NULL, '["국민연금보험","산재보험","출국만기보험","귀국비용보험"]'::jsonb, NULL, NULL, NULL, NULL, '출국만기보험 = bảo hiểm hết hạn xuất cảnh. Mục đích: chuẩn bị chi phí về nước. Đóng trong 80 ngày trước khi xuất cảnh.', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 21, 'listening', 'listening', 'text', '들은 것을 고르십시오.', '_____지', NULL, '["봉지","반지","번지","방지"]'::jsonb, NULL, '번지', NULL, 'Nghe kỹ phụ âm đầu: 봉/반/번/방', '번지 = số nhà/địa chỉ (số + 번지). Phân biệt nghe: 봉(bông), 반(nửa/nhóm), 번(số/lần), 방(phòng).', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 22, 'listening', 'listening', 'text', '들은 것을 고르십시오.', '제 어머니는 _________.', NULL, '["주무세요","주모세요","주부세요","주마세요"]'::jsonb, NULL, '주무세요', NULL, 'Nghe động từ honorific: 주무세요 = đang ngủ (lịch sự)', '주무세요 = kính ngữ của 자다 (ngủ). Dùng cho người lớn tuổi hơn. Phân biệt: 주무세요 ≠ 주모세요/주부세요.', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 23, 'listening', 'listening', 'image', '들은 것을 고르십시오.', NULL, NULL, '[".....",".....",".....","....."]'::jsonb, '["/de2/p13_img1.webp","/de2/p13_img2.webp","/de2/p13_img3.webp","/de2/p13_img4.webp"]'::jsonb, '여자아이가 바닥에 앉아서 책을 읽고 있습니다.', NULL, 'Nghe hành động của trẻ em → chọn hình đúng', '여자아이가 바닥에 앉아서 책을 읽고 있습니다 = cô bé đang ngồi đọc sách. → Chọn hình ① (bé gái đọc sách).', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 24, 'listening', 'listening', 'image', '들은 것을 고르십시오.', NULL, NULL, '[".....",".....",".....","....."]'::jsonb, '["/de2/p13_img5.webp","/de2/p13_img6.webp","/de2/p13_img7.webp","/de2/p13_img8.webp"]'::jsonb, '이 동물은 흑백 줄무늬가 있고 말과 비슷하게 생겼습니다.', NULL, 'Nghe mô tả đặc điểm động vật → chọn hình đúng', '흑백 줄무늬 + 말과 비슷 = sọc đen trắng + giống ngựa → 얼룩말 (ngựa vằn). Phân biệt: 사자(sư tử), 코끼리(voi), 곰(gấu).', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 25, 'listening', 'listening', 'text', '이것은 무엇입니까?', NULL, '/de2/p14_img1.webp', '[".....",".....",".....","....."]'::jsonb, NULL, '이것으로 상점에서 물건을 살 수 있습니다. 현금이 없을 때 편리합니다.', NULL, 'Nghe mô tả đồ vật → xem ảnh thẻ', 'Thẻ ngân hàng dùng mua hàng thay tiền mặt → 카드. 현금(tiền mặt), 통장(sổ ngân hàng), 영수증(hóa đơn).', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 26, 'listening', 'listening', 'text', '여기는 어디입니까?', NULL, '/de2/p14_img2.webp', '[".....",".....",".....","....."]'::jsonb, NULL, '여기는 샤워기가 있고 몸을 씻을 수 있는 곳입니다.', NULL, 'Nhìn ảnh phòng tắm → nghe mô tả', 'Nơi có vòi hoa sen, dùng để tắm → 욕실 (phòng tắm). Phân biệt: 부엌(bếp), 거실(phòng khách), 창고(nhà kho).', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 27, 'listening', 'listening', 'text', '이 사람은 무엇을 하고 있습니까?', NULL, '/de2/p14_img3.webp', '[".....",".....",".....","....."]'::jsonb, NULL, '이 사람은 마스크를 쓰고 털이개로 먼지를 털고 있습니다.', NULL, 'Nhìn ảnh người đang làm vệ sinh → nghe mô tả', 'Người đeo khẩu trang, dùng cây phủi bụi → 청소하고 있습니다 (đang lau dọn).', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 28, 'listening', 'listening', 'text', '연필이 얼마나 있습니까?', NULL, '/de2/p14_img4.webp', '[".....",".....",".....","....."]'::jsonb, NULL, '연필이 여섯 자루 있습니다.', NULL, 'Nhìn hình đếm bút chì → nghe đáp án', 'Nhìn hình: 6 cây bút chì → 여섯 자루. Đếm: 세(3), 네(4), 다섯(5), 여섯(6).', 4)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 29, 'listening', 'listening', 'text', '은행은 어디에 있습니까?', NULL, '/de2/p15_img1.webp', '[".....",".....",".....","....."]'::jsonb, NULL, '은행은 편의점 위에 있습니다.', NULL, 'Nhìn sơ đồ vị trí → nghe mô tả vị trí ngân hàng', 'Bản đồ: hàng 1=병원/약국, hàng 2=은행/서점, hàng 3=편의점/우체국. Ngân hàng nằm phía trên cửa hàng tiện lợi → 편의점 위.', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 30, 'listening', 'listening', 'text', '다음을 듣고 질문에 알맞은 대답을 고르십시오.', NULL, NULL, '["네, 만 원짜리를 주시면 돼요.","네, 만 원짜리로 두 장 주시면 돼요.","네, 그럼 제가 사만 원을 거슬러 드릴게요.","네, 천 원짜리로 열 장 드릴게요."]'::jsonb, NULL, '이거 만 원인데요, 천 원짜리로 좀 바꿔 주시겠어요?', NULL, 'Đổi tiền: 10.000 won → tiền lẻ 1.000 won', '10.000 won → tiền lẻ 1.000 won: 10 tờ 1.000 won = 만 원. Đáp án: 천 원짜리로 열 장.', 4)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 31, 'listening', 'listening', 'text', '다음을 듣고 질문에 알맞은 대답을 고르십시오.', NULL, NULL, '["내일 도착해도 괜찮아요.","영수증만 있으면 조회할 수 있어요.","늦어도 내일 오후에는 도착할 거예요.","지금 출발하니까 조금만 기다려 주세요."]'::jsonb, NULL, '제가 보낸 택배가 아직 안 왔어요. 언제쯤 받을 수 있을까요?', NULL, 'Câu hỏi về thời gian nhận hàng', 'Chưa nhận được bưu kiện → hỏi khi nào đến. Đáp án hợp lý: 늦어도 내일 오후에는 도착할 거예요.', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 32, 'listening', 'listening', 'text', '다음을 듣고 질문에 알맞은 대답을 고르십시오.', NULL, NULL, '["건강보험증을 꼭 만들어야 해요.","약은 꾸준히 잘 챙겨 먹으려고 해요.","병원에 자주 다녀도 안 나아서 걱정이네요.","뼈를 다쳤을지도 모르니까 병원에 가 보세요."]'::jsonb, NULL, '어제 넘어져서 발목이 너무 아파요.', NULL, 'Thông báo bị ngã, đau mắt cá', 'Bị ngã đau mắt cá → có thể bị gãy xương. Khuyên: 뼈를 다쳤을지도 모르니까 병원에 가 보세요.', 4)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 33, 'listening', 'listening', 'text', '다음을 듣고 질문에 알맞은 대답을 고르십시오.', NULL, NULL, '["그 식당은 음식이 별로 맛이 없어요.","그럼 회식 끝나고 직원들하고 이야기해 봐요.","고기를 먹고 싶으면 다른 곳으로 바꿔도 돼요.","그 식당에는 다른 메뉴도 많으니까 괜찮을 거예요."]'::jsonb, NULL, '이번 회식 장소가 고깃집인데 저는 고기를 못 먹어요.', NULL, 'Thông báo không ăn được thịt tại buổi tiệc công ty', 'Tiệc công ty ở nhà hàng thịt nhưng không ăn thịt được → 그 식당에는 다른 메뉴도 많으니까 괜찮을 거예요.', 4)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 34, 'listening', 'listening', 'text', '다음을 듣고 이어지는 말을 고르십시오.', NULL, NULL, '["서른 살이에요.","시월 일일이에요.","저는 이영수입니다.","다음 주에 갈 거예요."]'::jsonb, NULL, '생일이 언제예요?', NULL, 'Câu hỏi về ngày sinh nhật', '생일이 언제예요? (Sinh nhật khi nào?) → Trả lời ngày tháng: 시월 일일이에요 (1 tháng 10). 서른 살=30 tuổi (không phải câu trả lời ngày sinh).', 2)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 35, 'listening', 'listening', 'text', '다음을 듣고 이어지는 말을 고르십시오.', NULL, NULL, '["드라이버 하는 게 좋아요.","네, 제가 가져다 줄게요.","네, 여기 있어요.","네, 집에 없어요."]'::jsonb, NULL, '드라이버 좀 빌릴 수 있어요?', NULL, 'Xin mượn tua vít → cách trả lời tự nhiên', '드라이버 빌릴 수 있어요? (Cho mượn tua vít không?) → Có sẵn thì nói: 네, 여기 있어요.', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 36, 'listening', 'listening', 'image', '잘 듣고 들은 내용과 관계 있는 그림을 고르십시오.', NULL, NULL, '["남자→여자 상자 건네기","여자 상자 들고 이동","여자 방에 들어오기","남녀 서류 교환"]'::jsonb, '["/de2/p16_img1.webp","/de2/p16_img2.webp","/de2/p16_img3.webp","/de2/p16_img4.webp"]'::jsonb, '남자가 여자에게 큰 상자를 건네주고 있습니다.', NULL, 'Hội thoại về việc giao nhận hộp → chọn hình phù hợp', '남자가 여자에게 상자를 건네주고 있습니다 = nam đưa hộp cho nữ → hình ① (hai người đứng/ngồi đối diện, nam đưa hộp qua bàn).', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 37, 'listening', 'listening', 'image', '잘 듣고 들은 내용과 관계 있는 그림을 고르십시오.', NULL, NULL, '["웨이터 서빙","물건 보여주기","은행 창구 거래","교실에서 전달"]'::jsonb, '["/de2/p16_img5.webp","/de2/p16_img6.webp","/de2/p16_img7.webp","/de2/p16_img8.webp"]'::jsonb, '여자가 은행 창구에서 남자 직원에게 무언가를 건네주고 있습니다.', NULL, 'Cảnh ở ngân hàng → chọn hình đúng', '여자가 은행 창구에서 남자 직원에게 건네주고 있습니다 → hình ③ (nữ tại quầy ngân hàng, nam phía sau quầy).', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 38, 'listening', 'listening', 'text', '대화 후 여자는 가장 먼저 무엇을 하겠습니까?', NULL, NULL, '["페인트 통을 정리한다.","바닥을 닦는다.","페인트 칠을 한다.","붓을 씻으러 간다."]'::jsonb, NULL, '남자: 오늘 페인트 칠이 다 끝났어요? 여자: 네, 방금 끝났어요. 남자: 그럼 붓부터 씻고 나서 바닥 닦고, 마지막으로 페인트 통 정리해 주세요. 여자: 네, 알겠어요.', NULL, 'Thứ tự công việc sau khi sơn xong: nghe kỹ thứ tự', 'Thứ tự: 붓 씻기 → 바닥 닦기 → 페인트 통 정리. Việc ĐẦU TIÊN = 붓을 씻으러 간다.', 4)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 39, 'listening', 'listening', 'text', '다음 중 들은 내용과 같은 것은 무엇입니까?', NULL, NULL, '["여자는 계약 기간 연장을 원하지 않는다.","여자는 가구 공장으로 옮길 예정이다.","여자는 현재 기숙사 생활을 하고 있다.","여자는 작업 환경 개선을 요청하고 있다."]'::jsonb, NULL, '남자: 계약 기간이 다음 달에 끝나는데 연장할 생각이 있어요? 여자: 네, 저는 여기서 계속 일하고 싶어요. 그런데 기숙사가 많이 낡아서 좀 고쳐 주셨으면 해요. 남자: 그렇군요, 알겠어요.', NULL, 'Hội thoại gia hạn hợp đồng và điều kiện ký túc xá', 'Nữ muốn gia hạn hợp đồng (계속 일하고 싶어요) và than ký túc xá cũ → Đang sống ở ký túc xá: 현재 기숙사 생활을 하고 있다.', 3)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
insert into public.eps_questions (exam_id, order_no, question_type, section, option_type, question_text, content, content_image, options, option_images, audio_script, audio_options, audio_hint, explanation, correct_answer)
values ('11111111-de02-4000-8000-000000000002'::uuid, 40, 'listening', 'listening', 'text', '다음 중 들은 내용과 같은 것은 무엇입니까?', NULL, NULL, '["여자는 다음 주에 음악회에 갑니다.","남자는 아버지의 선물을 준비했습니다.","남자는 부모님과 음악회에 가고 싶어합니다.","여자는 인터넷으로 공연을 찾아보려고 합니다."]'::jsonb, NULL, '여자: 다음 주에 부모님이랑 음악회에 가는데 같이 갈래요? 남자: 저도 음악회에 가고 싶어요. 그런데 표를 구할 수 있을까요? 여자: 지금 인터넷으로 찾아보고 있어요.', NULL, 'Hội thoại về buổi hòa nhạc và mua vé', 'Nữ nói ''dạo tới (다음 주에) đi xem hòa nhạc'' → Đáp án ①: 여자는 다음 주에 음악회에 갑니다. ③ sai vì nam muốn đi cùng nữ (không phải cùng bố mẹ nam).', 1)
on conflict (exam_id, order_no) do update set
  question_type = excluded.question_type,
  section = excluded.section,
  option_type = excluded.option_type,
  question_text = excluded.question_text,
  content = excluded.content,
  content_image = excluded.content_image,
  options = excluded.options,
  option_images = excluded.option_images,
  audio_script = excluded.audio_script,
  audio_options = excluded.audio_options,
  audio_hint = excluded.audio_hint,
  explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;

commit;
